/** Naga's Voice: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 016, terrain 016). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_16 = {
 id: 'chapter-16', rom: '016', terrainFile: '016', width: 22, height: 30,
 rows: [
   "iiii11111111111111iiii",
   "iiii111iii11111111iiii",
   "iiii111iii11111111iiii",
   "iiii1i1iii1111ii11iiii",
   "iii11i1iii1111ii111iii",
   "iii11i11ii111ii1111iii",
   "iii11111ii111ii1111iii",
   "iii11111ii111ii111iiii",
   "iiii11i1i111111111iiii",
   "i1ii11i1i111i11111iiii",
   "i1ii11iii111i11111iiii",
   "i1ii11iii111i11111iiii",
   "i11111iii11111111iiiii",
   "i11111i1111iiii11iiiii",
   "i11111i111111ii11iiiii",
   "i111i11111111111iiiiii",
   "i1iii11i11111111iiiiii",
   "i1iii11i11111111iiii11",
   "iiiii11i1iii1111iiii11",
   "iiii111i11111111iiii11",
   "iiii111i111111111ii111",
   "iii11111111ii1111ii111",
   "iii11111ii1ii1111ii111",
   "iii11111ii1111111ii1i1",
   "iii11111ii1111111ii1i1",
   "ii111111111111ii1ii111",
   "ii111111111111ii1ii111",
   "ii111iiii111iiiiiiii11",
   "ii111iiii111iiiiiiii11",
   "ii111iiii111iiiiiiii11"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[9,25],"to":[9,25],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[11,23],"to":[11,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[5,24],"to":[5,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[6,24],"to":[6,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[10,24],"to":[10,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[12,24],"to":[12,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[6,25],"to":[6,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[8,25],"to":[8,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[11,25],"to":[11,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[5,26],"to":[5,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[7,26],"to":[7,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[11,26],"to":[11,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","at":[13,26],"to":[13,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_016_ボス","team":"enemy","at":[12,1],"to":[12,1],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Tomahawk","Bullion (M)"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_016_盗賊","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["normal","hard","lunatic"],"class":"Thief","items":["Steel Sword","Bullion (M)"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(16,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(16,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_016_盗賊","team":"enemy","at":[5,13],"to":[5,13],"difficulties":["normal","hard","lunatic"],"class":"Thief","items":["Steel Sword","Speedwing"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(11,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(11,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_016_盗賊","team":"enemy","at":[1,17],"to":[1,17],"difficulties":["normal","hard","lunatic"],"class":"Thief","items":["Steel Sword","Master Seal"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(6,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(6,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[15,20],"to":[15,20],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[6,19],"to":[6,19],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ペガサスナイト","team":"enemy","at":[3,18],"to":[3,18],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Beast Killer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[11,17],"to":[11,17],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[5,14],"to":[5,14],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[15,14],"to":[15,14],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[8,17],"to":[8,17],"difficulties":["hard","lunatic"],"class":"Hero","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[12,12],"to":[12,12],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Killer Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[9,10],"to":[9,10],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[17,10],"to":[17,10],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ペガサスナイト","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ファルコンナイト","team":"enemy","at":[6,9],"to":[6,9],"difficulties":["normal","hard","lunatic"],"class":"Falcon Knight","items":["Silver Lance","Mend"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[14,9],"to":[14,9],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_スナイパー","team":"enemy","at":[11,8],"to":[11,8],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Master Seal"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ボウナイト","team":"enemy","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ボウナイト","team":"enemy","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ペガサスナイト","team":"enemy","at":[6,4],"to":[6,4],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ファルコンナイト","team":"enemy","at":[19,3],"to":[19,3],"difficulties":["normal","hard","lunatic"],"class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[10,11],"to":[10,11],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[16,11],"to":[16,11],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[12,5],"to":[12,5],"difficulties":["normal"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[16,4],"to":[16,4],"difficulties":["normal"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["normal"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[12,5],"to":[12,5],"difficulties":["hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_016_戦士","team":"enemy","at":[16,4],"to":[16,4],"difficulties":["hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_016_ウォーリアー","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[11,3],"to":[11,3],"difficulties":["hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_016_勇者","team":"enemy","at":[17,3],"to":[17,3],"difficulties":["hard","lunatic"],"class":"Hero","items":["Tomahawk"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Reinforce01","pid":"PID_016_戦士","team":"enemy","at":[2,29],"to":[2,27],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_016_戦士","team":"enemy","at":[4,29],"to":[4,28],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_016_勇者","team":"enemy","at":[3,29],"to":[3,26],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_016_勇者","team":"enemy","at":[4,29],"to":[4,27],"difficulties":["hard","lunatic"],"class":"Hero","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_016_スナイパー","team":"enemy","at":[3,29],"to":[3,28],"difficulties":["lunatic"],"class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_016_戦士","team":"enemy","at":[9,29],"to":[9,28],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_016_戦士","team":"enemy","at":[11,29],"to":[11,27],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Short Axe","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_016_ウォーリアー","team":"enemy","at":[10,29],"to":[10,26],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_016_ウォーリアー","team":"enemy","at":[9,29],"to":[9,27],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_016_スナイパー","team":"enemy","at":[10,29],"to":[10,28],"difficulties":["lunatic"],"class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_016_ペガサスナイト","team":"enemy","at":[0,10],"to":[1,10],"difficulties":["normal"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_016_ファルコンナイト","team":"enemy","at":[0,10],"to":[1,10],"difficulties":["hard","lunatic"],"class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_016_ファルコンナイト","team":"enemy","at":[0,11],"to":[1,11],"difficulties":["lunatic"],"class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_016_ペガサスナイト","team":"enemy","at":[0,22],"to":[1,22],"difficulties":["normal"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_016_ファルコンナイト","team":"enemy","at":[0,22],"to":[1,22],"difficulties":["hard","lunatic"],"class":"Falcon Knight","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_016_ペガサスナイト","team":"enemy","at":[21,21],"to":[20,21],"difficulties":["normal"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_016_ファルコンナイト","team":"enemy","at":[21,21],"to":[20,21],"difficulties":["hard","lunatic"],"class":"Falcon Knight","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_016_ペガサスナイト","team":"enemy","at":[21,8],"to":[20,8],"difficulties":["normal"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_016_ファルコンナイト","team":"enemy","at":[21,8],"to":[20,8],"difficulties":["hard","lunatic"],"class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_016_ファルコンナイト","team":"enemy","at":[21,9],"to":[20,9],"difficulties":["lunatic"],"class":"Falcon Knight","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_016_ボウナイト","team":"enemy","at":[3,29],"to":[3,27],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_016_ボウナイト","team":"enemy","at":[4,29],"to":[4,27],"difficulties":["hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_016_ボウナイト","team":"enemy","at":[2,29],"to":[2,27],"difficulties":["lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_016_ボウナイト","team":"enemy","at":[10,29],"to":[10,27],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_016_ボウナイト","team":"enemy","at":[9,29],"to":[9,27],"difficulties":["hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_016_ボウナイト","team":"enemy","at":[11,29],"to":[11,27],"difficulties":["lunatic"],"class":"Bow Knight","items":["Silver Bow","Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
