/** Warrior Realm: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 003, terrain 003). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_3 = {
 id: 'chapter-3', rom: '003', terrainFile: '003', width: 23, height: 17,
 rows: [
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "EEEEEEEEEEEEEEEEEEEEEEE",
   "YYYxxxtttttttttttxxxxYY",
   "YYYxxxtttttttttttxxxxYY",
   "xxYyxxxYYYtttxxxxxxyxYY",
   "xxxxxxYYYxxkxxxxxxxxYYY",
   "xxxxxxYYYxxxxxxxxxxYYYY",
   "EEGEEEYYYYxyxxxxxEEEGEE",
   "EExEEEYYYYxxxxxxxEEEYEE",
   "EExEEEEEEEEEEEEEEEEEYEE",
   "EExEEEEEEEEEEEEEEEEEYEE",
   "XXXXXXEEEEEEEEEEEXXXXXX",
   "XXXXXXEEEEEEEEEEEXXXXXX",
   "XX33XXXXXXXXXXXXXXX33XX",
   "XXXXXXXXXXXXXXXXXXXXXXX",
   "XX3XXXXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXXXXXXXX"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[11,15],"to":[11,15],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[10,14],"to":[10,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[13,15],"to":[13,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[11,14],"to":[11,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[14,15],"to":[14,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[9,15],"to":[9,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_003_ボス","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["normal","hard","lunatic"],"name":"Raimi","class":"Knight","items":["Javelin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["hard"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[3,12],"to":[3,12],"difficulties":["normal","hard"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[1,13],"to":[1,13],"difficulties":["normal","hard"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーチャー_落下","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["normal","hard"],"name":"Feroxi","class":"Archer","items":["Iron Bow","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[21,13],"to":[21,13],"difficulties":["normal","hard"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[19,12],"to":[19,12],"difficulties":["normal","hard"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[20,12],"to":[20,12],"difficulties":["hard"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_003_傭兵_落下","team":"enemy","at":[20,11],"to":[20,11],"difficulties":["normal","hard"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[2,15],"to":[2,15],"difficulties":["lunatic"],"name":"Feroxi","class":"Knight","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["lunatic"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[3,12],"to":[3,12],"difficulties":["lunatic"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーチャー_落下","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["lunatic"],"name":"Feroxi","class":"Archer","items":["Iron Bow","Door Key"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[19,14],"to":[19,14],"difficulties":["lunatic"],"name":"Feroxi","class":"Knight","items":["Iron Lance","Heal"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[21,13],"to":[21,13],"difficulties":["lunatic"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_ソルジャー","team":"enemy","at":[19,12],"to":[19,12],"difficulties":["lunatic"],"name":"Feroxi","class":"Soldier","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[20,12],"to":[20,12],"difficulties":["lunatic"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_傭兵_落下","team":"enemy","at":[20,11],"to":[20,11],"difficulties":["lunatic"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword","Door Key"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["normal","hard"],"name":"Feroxi","class":"Knight","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[20,5],"to":[20,5],"difficulties":["normal","hard"],"name":"Feroxi","class":"Knight","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_003_傭兵","team":"enemy","at":[7,4],"to":[7,4],"difficulties":["normal","hard"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_傭兵","team":"enemy","at":[15,4],"to":[15,4],"difficulties":["normal","hard"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_003_戦士","team":"enemy","at":[9,7],"to":[9,7],"difficulties":["normal","hard"],"name":"Feroxi","class":"Fighter","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_戦士","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["normal","hard"],"name":"Feroxi","class":"Fighter","items":["Hammer"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["hard"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["hard"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["lunatic"],"name":"Feroxi","class":"Knight","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_アーマーナイト","team":"enemy","at":[20,5],"to":[20,5],"difficulties":["lunatic"],"name":"Feroxi","class":"Knight","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_傭兵","team":"enemy","at":[7,4],"to":[7,4],"difficulties":["lunatic"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_傭兵","team":"enemy","at":[15,4],"to":[15,4],"difficulties":["lunatic"],"name":"Feroxi","class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_戦士","team":"enemy","at":[9,7],"to":[9,7],"difficulties":["lunatic"],"name":"Feroxi","class":"Fighter","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_戦士","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["lunatic"],"name":"Feroxi","class":"Fighter","items":["Hammer"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["lunatic"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_003_アーチャー","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["lunatic"],"name":"Feroxi","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_カラム","team":"ally","at":[6,14],"to":[6,14],"difficulties":["normal","hard","lunatic"],"name":"Kellam","class":"Knight","items":["Iron Lance","Javelin","Vulnerary"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Support01","pid":"PID_スミア","team":"player","name":"Sumia","at":[12,16],"to":[12,15],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
