/** Sibling Blades: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 018, terrain 018). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_18 = {
 id: 'chapter-18', rom: '018', terrainFile: '018', width: 17, height: 32,
 rows: [
   "LLLLLLLLLLLLLLLLL",
   "LLLLLLLJJLLLLLLLL",
   "LLJJxJJJJJLLJJLLL",
   "LLJJJJJJJJLLJJJLL",
   "LLLJLLLJxJJJJJJLL",
   "LLJJJLLJJJLJJxJLL",
   "LLJJJLLxLLLLLJJLL",
   "LLLJJLLJJLLLLJLLL",
   "LLJxLLLJxJLLJJLLL",
   "LLLJJJJJJJLJJJLLL",
   "LLxJJLLLJLLLJLLLL",
   "LLJJJLJJxJLLJJJLL",
   "LLJLLLJJJJLLxJJLL",
   "LLJxJLJxJLLLJJLLL",
   "LLJJJLxLLLLLJLLLL",
   "LLLLJJJJLJJLJLLLL",
   "LLLLLJJJJJJJJJLLL",
   "LLJJJJJLJJLLJxJLL",
   "LLJxJJLLJJLLJHJLL",
   "LLJHLJJxxJJLJJLLL",
   "LLLLLJJLxxJLJLLLL",
   "LLLLJJJLJxJJJxJLL",
   "LLJxJJJLLxLLJHJLL",
   "LLJHJLJJxxLLJJJLL",
   "LLJLLLJxxJLLxJLLL",
   "LLxJLLLxLLLLJJJLL",
   "LLJLLJLxLJJLJJJLL",
   "LLJJLJLxxJJLJLLLL",
   "LLJJJJJJxJJJJJJLL",
   "LLLJLJJLJJJLJJJLL",
   "LLLLLLLLJJLLLLLLL",
   "LLLLLLLLLLLLLLLLL"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[8,4],"to":[8,4],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[9,3],"to":[9,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[7,5],"to":[7,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[9,5],"to":[9,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[2,5],"to":[2,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[4,5],"to":[4,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[3,6],"to":[3,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[13,3],"to":[13,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[12,4],"to":[12,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[14,4],"to":[14,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[13,5],"to":[13,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_018_ボス","team":"enemy","at":[8,28],"to":[8,28],"difficulties":["normal","hard","lunatic"],"name":"Yen'fay","class":"Swordmaster","items":["Amatsu","Noble Rapier"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[7,8],"to":[7,8],"difficulties":["normal"],"name":"Valmese","class":"Paladin","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[7,8],"to":[7,8],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[8,9],"to":[8,9],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[3,9],"to":[3,9],"difficulties":["normal"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[3,9],"to":[3,9],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["normal"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[12,10],"to":[12,10],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[8,11],"to":[8,11],"difficulties":["normal"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Concoction"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[7,12],"to":[7,12],"difficulties":["normal"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[8,11],"to":[8,11],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow","Concoction"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[7,12],"to":[7,12],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[6,13],"to":[6,13],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[8,13],"to":[8,13],"difficulties":["lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["normal"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[13,13],"to":[13,13],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[4,13],"to":[4,13],"difficulties":["normal"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[2,14],"to":[2,14],"difficulties":["normal"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[4,13],"to":[4,13],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[2,14],"to":[2,14],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["normal"],"name":"Valmese","class":"Paladin","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":7},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[7,16],"to":[7,16],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":7},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["normal"],"name":"Valmese","class":"Paladin","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["normal"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[14,17],"to":[14,17],"difficulties":["lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[3,18],"to":[3,18],"difficulties":["normal"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[3,18],"to":[3,18],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":9},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":9},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["normal"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[8,21],"to":[8,21],"difficulties":["normal"],"name":"Valmese","class":"Paladin","items":["Killer Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":10},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[8,21],"to":[8,21],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Killer Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":10},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[9,18],"to":[9,18],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":10},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":10},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[6,19],"to":[6,19],"difficulties":["normal"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[5,22],"to":[5,22],"difficulties":["normal"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[6,19],"to":[6,19],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":11},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[5,22],"to":[5,22],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":11},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[3,22],"to":[3,22],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":11},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[2,23],"to":[2,23],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":11},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[14,21],"to":[14,21],"difficulties":["normal"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[13,23],"to":[13,23],"difficulties":["normal"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[14,21],"to":[14,21],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":12},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[13,23],"to":[13,23],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":12},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[12,22],"to":[12,22],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":12},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[14,23],"to":[14,23],"difficulties":["lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":12},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[2,24],"to":[2,24],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Armorslayer"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[8,24],"to":[8,24],"difficulties":["normal"],"name":"Valmese","class":"Warrior","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[7,25],"to":[7,25],"difficulties":["normal"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[8,24],"to":[8,24],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":13},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[7,25],"to":[7,25],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":13},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[9,26],"to":[9,26],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[2,27],"to":[2,27],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ソードマスター","team":"enemy","at":[12,27],"to":[12,27],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[4,28],"to":[4,28],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[6,28],"to":[6,28],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_パラディン","team":"enemy","at":[11,28],"to":[11,28],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Paladin","items":["Spear"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_賢者","team":"enemy","at":[13,28],"to":[13,28],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_ウォーリアー","team":"enemy","at":[3,29],"to":[3,29],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_018_グリフォンナイト","team":"enemy","at":[12,29],"to":[12,29],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_018_エクセライEV","team":"enemy","at":[9,28],"to":[9,28],"difficulties":["normal","hard","lunatic"],"name":"Excellus","class":"Sage","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
