/** The Sword or the Knee: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 020, terrain 020). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_20 = {
 id: 'chapter-20', rom: '020', terrainFile: '020', width: 23, height: 32,
 rows: [
   "EEEEEEEEEEEEEEEEEEEEEEE",
   "ExxxxEExxxxAxxxxEExxxxE",
   "ExHHxEExxxxxxxxxEExHHxE",
   "ExxxxEExxxxxxxxxEExxxxE",
   "ExxxxEExxxxxxxxxEExxxxE",
   "EEGGEEExxxxxxxxxEEEGGEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxxxxxxxxxxxxxxxxxxEE",
   "EExxxxxxxxxxxxxxxxxxxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExExxxxxExEEExxEE",
   "EExxEEExxxxxxxxxEEExxEE",
   "EExxEEEEEExxxEEEEEExxEE",
   "EExxEEEEEExxxEEEEEExxEE",
   "xxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxx",
   "EExxEEEEEExxxEEEEEExxEE"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[11,29],"to":[11,29],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[10,29],"to":[10,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[12,29],"to":[12,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[9,30],"to":[9,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[10,30],"to":[10,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[12,30],"to":[12,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[13,30],"to":[13,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[6,29],"to":[6,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[7,29],"to":[7,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[6,30],"to":[6,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[7,30],"to":[7,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[15,29],"to":[15,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[16,29],"to":[16,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","name":"Panne","at":[15,30],"to":[15,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[16,30],"to":[16,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_020_ボス","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["normal","hard"],"name":"Walhart","class":"Conqueror","items":["Wolf Berg","Bullion (L)"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_020_ボス","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["lunatic"],"name":"Walhart","class":"Conqueror","items":["Wolf Berg","Bullion (L)"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4,"boss":true},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[2,29],"to":[2,29],"difficulties":["normal"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[3,29],"to":[3,29],"difficulties":["normal"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[2,29],"to":[2,29],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[3,29],"to":[3,29],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[2,30],"to":[2,30],"difficulties":["lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[3,30],"to":[3,30],"difficulties":["lunatic"],"name":"Valmese","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[19,29],"to":[19,29],"difficulties":["normal"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[20,29],"to":[20,29],"difficulties":["normal"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[19,29],"to":[19,29],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[20,29],"to":[20,29],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[19,30],"to":[19,30],"difficulties":["lunatic"],"name":"Valmese","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[20,30],"to":[20,30],"difficulties":["lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_セルバンテス","team":"enemy","at":[11,21],"to":[11,21],"difficulties":["normal","hard","lunatic"],"name":"Cervantes","class":"General","items":["Tomahawk","Dracoshield"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[10,26],"to":[10,26],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[12,26],"to":[12,26],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[10,24],"to":[10,24],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[12,24],"to":[12,24],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[15,23],"to":[15,23],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_スナイパー","team":"enemy","at":[7,20],"to":[7,20],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sniper","items":["Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_スナイパー","team":"enemy","at":[15,20],"to":[15,20],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sniper","items":["Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[9,19],"to":[9,19],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[13,19],"to":[13,19],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[7,26],"to":[7,26],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[15,26],"to":[15,26],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[3,22],"to":[3,22],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword","Elixir"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[2,23],"to":[2,23],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[3,20],"to":[3,20],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[2,21],"to":[2,21],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[19,22],"to":[19,22],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[20,23],"to":[20,23],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[20,21],"to":[20,21],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_020_盗賊","team":"enemy","at":[19,20],"to":[19,20],"difficulties":["normal"],"name":"Ruffian","class":"Thief","items":["Steel Sword"],"ai":{"start":"Turn","startParam":"2","mission":"Treasure","missionParam":"pos(20,2)","attack":"Null","move":"TrasureToEscape","moveParam":"pos(20,2),0,pos(21,10)"},"group":0},
  {"faction":"Enemy","pid":"PID_020_盗賊","team":"enemy","at":[19,20],"to":[19,20],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Treasure","missionParam":"pos(20,2)","attack":"Null","move":"TrasureToEscape","moveParam":"pos(20,2),0,pos(21,10)"},"group":0},
  {"faction":"Enemy","pid":"PID_020_エクセライ","team":"enemy","at":[11,11],"to":[11,11],"difficulties":["normal","hard","lunatic"],"name":"Excellus","class":"Sage","items":["Bolganone"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[11,14],"to":[11,14],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[10,13],"to":[10,13],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[12,13],"to":[12,13],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[7,13],"to":[7,13],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ウォーリアー","team":"enemy","at":[15,13],"to":[15,13],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_スナイパー","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_スナイパー","team":"enemy","at":[13,12],"to":[13,12],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[7,12],"to":[7,12],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[15,12],"to":[15,12],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_ジェネラル","team":"enemy","at":[20,7],"to":[20,7],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_020_バトルモンク","team":"enemy","at":[8,4],"to":[8,4],"difficulties":["normal","hard"],"name":"Valmese","class":"War Monk","items":["Silver Axe","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_020_バトルモンク","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["normal","hard"],"name":"Valmese","class":"War Monk","items":["Silver Axe","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["normal","hard"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["normal","hard"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_020_バトルモンク","team":"enemy","at":[8,4],"to":[8,4],"difficulties":["lunatic"],"name":"Valmese","class":"War Monk","items":["Silver Axe","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToMustHeal","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_020_バトルモンク","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["lunatic"],"name":"Valmese","class":"War Monk","items":["Silver Axe","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToMustHeal","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_020_勇者","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToMustHeal","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_020_賢者","team":"enemy","at":[13,2],"to":[13,2],"difficulties":["lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToMustHeal","move":"NearestEnemy"},"group":4},
  {"faction":"Reinforce01","pid":"PID_020_ジェネラル","team":"enemy","at":[10,31],"to":[10,29],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_ジェネラル","team":"enemy","at":[12,31],"to":[12,29],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_勇者","team":"enemy","at":[11,31],"to":[11,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_賢者","team":"enemy","at":[10,31],"to":[9,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_賢者","team":"enemy","at":[12,31],"to":[13,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_勇者","team":"enemy","at":[10,31],"to":[10,30],"difficulties":["lunatic"],"name":"Valmese","class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_勇者","team":"enemy","at":[12,31],"to":[12,30],"difficulties":["lunatic"],"name":"Valmese","class":"Hero","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_ジェネラル","team":"enemy","at":[11,31],"to":[11,29],"difficulties":["lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_ウォーリアー","team":"enemy","at":[10,31],"to":[9,29],"difficulties":["lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_020_ウォーリアー","team":"enemy","at":[12,31],"to":[13,29],"difficulties":["lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_020_ジェネラル","team":"enemy","at":[2,31],"to":[1,30],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_020_ウォーリアー","team":"enemy","at":[2,31],"to":[2,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_020_ジェネラル","team":"enemy","at":[3,31],"to":[3,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_020_ウォーリアー","team":"enemy","at":[3,31],"to":[4,30],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_020_賢者","team":"enemy","at":[19,31],"to":[18,30],"difficulties":["hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_020_ジェネラル","team":"enemy","at":[19,31],"to":[19,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_020_賢者","team":"enemy","at":[20,31],"to":[20,30],"difficulties":["normal","hard","lunatic"],"name":"Valmese","class":"Sage","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_020_ジェネラル","team":"enemy","at":[20,31],"to":[21,30],"difficulties":["hard","lunatic"],"name":"Valmese","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
