/** An Ill Presage: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 022, terrain 022). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_22 = {
 id: 'chapter-22', rom: '022', terrainFile: '022', width: 27, height: 25,
 rows: [
   "4444444ttttttttttttt4444444",
   "444444444444444444444444444",
   "444v44444444444444444444444",
   "444vv44444444444444444v4444",
   "1444v44444444444444444vv444",
   "111444444444111444444444444",
   "111114444441111444444414444",
   "111111444441111114444111144",
   "1vv111114411111111111111111",
   "111111111111111111111111111",
   "111111111v1111111111111vv11",
   "111111111v1111111111111vv11",
   "11v11111111111111v111111111",
   "11vvv111111111111v111111111",
   "111vvvv11111111111vvv111111",
   "11111111v11111111v111111111",
   "11111111v11111111v111111111",
   "11111111v11111111v111111111",
   "1111111vv11111111111v111111",
   "111vv1111111111111vvv111111",
   "111vvv111111111111v11111111",
   "111111111111111111111111v11",
   "111111vv1111111111vvv111v11",
   "1111111v1111111111v1111vv11",
   "111111111111111111vv111vv11"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[13,22],"to":[13,22],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[12,20],"to":[12,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[14,20],"to":[14,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[11,21],"to":[11,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[13,21],"to":[13,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[15,21],"to":[15,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[12,22],"to":[12,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[14,22],"to":[14,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[11,23],"to":[11,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[12,23],"to":[12,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[13,23],"to":[13,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[14,23],"to":[14,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[15,23],"to":[15,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_022_ボス","team":"enemy","at":[13,1],"to":[13,1],"difficulties":["normal","hard","lunatic"],"name":"Aversa","class":"Dark Flier","items":["Goetia","Goddess Icon"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_022_アインス","team":"enemy","at":[22,18],"to":[22,18],"difficulties":["normal"],"name":"Mus","class":"General","items":["Brave Lance"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴァイ","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["normal"],"name":"Bovis","class":"Bow Knight","items":["Brave Bow"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ドライ","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["normal"],"name":"Tigris","class":"Warrior","items":["Helswath"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_フィーア","team":"enemy","at":[15,5],"to":[15,5],"difficulties":["normal"],"name":"Lepus","class":"War Cleric","items":["Brave Axe","Recover"],"ai":{"start":"TurnAttackRangeHealRange","startParam":"6","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_022_フュンフ","team":"enemy","at":[23,15],"to":[23,15],"difficulties":["normal"],"name":"Draco","class":"Sniper","items":["Yewfelle"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ゼクス","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["normal"],"name":"Anguilla","class":"Dark Knight","items":["Thoron"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ズィーベン","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["normal"],"name":"Equus","class":"Paladin","items":["Gungnir"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_アハト","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["normal"],"name":"Ovis","class":"Sage","items":["Rexcalibur"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_022_ノイン","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["normal"],"name":"Simia","class":"Swordmaster","items":["Balmung"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_022_ツェーン","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["normal"],"name":"Gallus","class":"Sorcerer","items":["Waste"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_022_エルフ","team":"enemy","at":[24,17],"to":[24,17],"difficulties":["normal"],"name":"Canis","class":"Valkyrie","items":["Valflame"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴェルフ","team":"enemy","at":[21,16],"to":[21,16],"difficulties":["normal"],"name":"Porcus","class":"Assassin","items":["Brave Sword"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_アインス","team":"enemy","at":[22,18],"to":[22,18],"difficulties":["hard"],"name":"Mus","class":"General","items":["Brave Lance"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴァイ","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["hard"],"name":"Bovis","class":"Bow Knight","items":["Brave Bow"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ドライ","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["hard"],"name":"Tigris","class":"Warrior","items":["Helswath"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_フィーア","team":"enemy","at":[15,5],"to":[15,5],"difficulties":["hard"],"name":"Lepus","class":"War Cleric","items":["Brave Axe","Recover"],"ai":{"start":"TurnAttackRangeHealRange","startParam":"5","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_フュンフ","team":"enemy","at":[23,15],"to":[23,15],"difficulties":["hard"],"name":"Draco","class":"Sniper","items":["Yewfelle"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ゼクス","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["hard"],"name":"Anguilla","class":"Dark Knight","items":["Thoron"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ズィーベン","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["hard"],"name":"Equus","class":"Paladin","items":["Gungnir"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_アハト","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["hard"],"name":"Ovis","class":"Sage","items":["Rexcalibur"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_ノイン","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["hard"],"name":"Simia","class":"Swordmaster","items":["Balmung"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_ツェーン","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["hard"],"name":"Gallus","class":"Sorcerer","items":["Waste"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_エルフ","team":"enemy","at":[24,17],"to":[24,17],"difficulties":["hard"],"name":"Canis","class":"Valkyrie","items":["Valflame"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴェルフ","team":"enemy","at":[21,16],"to":[21,16],"difficulties":["hard"],"name":"Porcus","class":"Assassin","items":["Brave Sword"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_アインス","team":"enemy","at":[22,18],"to":[22,18],"difficulties":["lunatic"],"name":"Mus","class":"General","items":["Brave Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴァイ","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["lunatic"],"name":"Bovis","class":"Bow Knight","items":["Brave Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ドライ","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["lunatic"],"name":"Tigris","class":"Warrior","items":["Helswath"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_フィーア","team":"enemy","at":[15,5],"to":[15,5],"difficulties":["lunatic"],"name":"Lepus","class":"War Cleric","items":["Brave Axe","Recover"],"ai":{"start":"TurnAttackRangeHealRange","startParam":"3","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_フュンフ","team":"enemy","at":[23,15],"to":[23,15],"difficulties":["lunatic"],"name":"Draco","class":"Sniper","items":["Yewfelle"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ゼクス","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["lunatic"],"name":"Anguilla","class":"Dark Knight","items":["Thoron"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_ズィーベン","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["lunatic"],"name":"Equus","class":"Paladin","items":["Gungnir"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_022_アハト","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["lunatic"],"name":"Ovis","class":"Sage","items":["Rexcalibur"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_ノイン","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["lunatic"],"name":"Simia","class":"Swordmaster","items":["Balmung"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_ツェーン","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["lunatic"],"name":"Gallus","class":"Sorcerer","items":["Waste"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_022_エルフ","team":"enemy","at":[24,17],"to":[24,17],"difficulties":["lunatic"],"name":"Canis","class":"Valkyrie","items":["Valflame"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_022_ツヴェルフ","team":"enemy","at":[21,16],"to":[21,16],"difficulties":["lunatic"],"name":"Porcus","class":"Assassin","items":["Brave Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Event02","pid":"PID_022_ファウダーEV","team":"enemy","at":[12,0],"to":[12,3],"difficulties":["normal","hard","lunatic"],"name":"Validar","class":"Sorcerer","ai":{"start":"Null","mission":"Null","attack":"Null","move":"Null"},"group":0},
 ],
} as const;
