/** Incursion: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 007, terrain 007). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_7 = {
 id: 'chapter-7', rom: '007', terrainFile: '007', width: 22, height: 18,
 rows: [
   "7777777777777777777777",
   "7777777777777777777777",
   "7777777776777777777771",
   "7777777766667777717711",
   "7777777761616777611111",
   "7777777111131666611311",
   "6667771131111111111111",
   "6666711311113111131111",
   "6661111111111131111999",
   "6611111113111111199999",
   "1111311991113919999999",
   "1111119999119999999999",
   "1131199999939999999999",
   "1119999999999999999999",
   "1199999999999999999999",
   "9999999999999999999999",
   "9999999999999999999999",
   "9999999999999999999999"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[4,9],"to":[4,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[4,11],"to":[4,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[3,10],"to":[3,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[3,11],"to":[3,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[3,12],"to":[3,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[2,9],"to":[2,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[1,10],"to":[1,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[1,11],"to":[1,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[1,13],"to":[1,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_007_ボス","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["normal","hard","lunatic"],"name":"Vasto","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[6,1],"to":[6,1],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe","Concoction"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[15,1],"to":[15,1],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[8,15],"to":[8,15],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[12,14],"to":[12,14],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[15,12],"to":[15,12],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[18,10],"to":[18,10],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[6,1],"to":[6,1],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[15,1],"to":[15,1],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[8,15],"to":[8,15],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[12,14],"to":[12,14],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[15,12],"to":[15,12],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[18,10],"to":[18,10],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["normal"],"name":"Plegian","class":"Archer","items":["Iron Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[10,8],"to":[10,8],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_盗賊","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["normal"],"name":"Plegian","class":"Thief","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Iron Axe","Hammer"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["normal"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_盗賊","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["normal"],"name":"Plegian","class":"Thief","items":["Steel Sword","Bullion (M)"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[16,8],"to":[16,8],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[18,6],"to":[18,6],"difficulties":["normal"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[10,8],"to":[10,8],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_盗賊","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Thief","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["hard"],"name":"Plegian","class":"Barbarian","items":["Iron Axe","Hammer"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["hard"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_盗賊","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["hard"],"name":"Plegian","class":"Thief","items":["Steel Sword","Bullion (M)"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[16,8],"to":[16,8],"difficulties":["hard"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["hard"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[18,6],"to":[18,6],"difficulties":["hard"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe","Hammer"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["lunatic"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_盗賊","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["lunatic"],"name":"Plegian","class":"Thief","items":["Steel Sword","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[16,8],"to":[16,8],"difficulties":["lunatic"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_蛮族","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_007_アーチャー","team":"enemy","at":[18,6],"to":[18,6],"difficulties":["lunatic"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[0,15],"to":[2,15],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Support02","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[17,17],"to":[17,8],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Reinforce01","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[0,9],"to":[1,9],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[0,10],"to":[1,10],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_007_ドラゴンナイト","team":"enemy","at":[0,11],"to":[1,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_007_神官EV","team":"ally","at":[0,11],"to":[7,8],"difficulties":["normal","hard","lunatic"],"name":"Hierarch","class":"Priest","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_クロム","team":"player","name":"Chrom","at":[17,6],"to":[17,6],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_プレイヤー男","team":"player","at":[18,6],"to":[18,6],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_リズ","team":"player","name":"Lissa","at":[19,5],"to":[19,5],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[20,6],"to":[20,6],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[17,8],"to":[17,8],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_007_エメリナEV","team":"ally","at":[18,7],"to":[18,7],"difficulties":["normal","hard","lunatic"],"name":"Emmeryn","class":"Sage","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_007_フィレインEV","team":"ally","at":[18,8],"to":[18,8],"difficulties":["normal","hard","lunatic"],"name":"Phila","class":"Falcon Knight","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
