/** Emmeryn: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 009, terrain 009). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_9 = {
 id: 'chapter-9', rom: '009', terrainFile: '009', width: 22, height: 22,
 rows: [
   "44444444EE111ttttttttt",
   "44444441EE111ttttttttt",
   "44444441EE111ttttttttt",
   "44444444EE111ttttttttt",
   "44444444EE111ttttttttt",
   "44444bbbEE111ttttttttt",
   "44444444EE111111111111",
   "44444441EE111111111111",
   "44bb4441EE11bb11111111",
   "44bb4441EE11bb11111111",
   "44444411EE111111bb1111",
   "44444411EE111111111111",
   "44444411EE111111111111",
   "444bb411EEEEE111EEEEEE",
   "444bb111EEEEE111EEEEEE",
   "444bb11111111j1j111111",
   "4444411111111111111111",
   "4444441j11111111111bb1",
   "4444444j44111111b11bb1",
   "4444444444bb1111b11111",
   "4444444444411111b11111",
   "4444444444411111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[4,5],"to":[4,5],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[3,7],"to":[3,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[6,6],"to":[6,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[4,6],"to":[4,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[2,5],"to":[2,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[6,4],"to":[6,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[2,4],"to":[2,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[4,3],"to":[4,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[2,3],"to":[2,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_009_ボス","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["normal","hard","lunatic"],"name":"Campari","class":"General","items":["Short Spear","Dracoshield"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[1,10],"to":[1,10],"difficulties":["lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[1,11],"to":[1,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Javelin"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[6,11],"to":[6,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_魔道士","team":"enemy","at":[3,12],"to":[3,12],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[5,13],"to":[5,13],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[7,12],"to":[7,12],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[4,14],"to":[4,14],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"ExcludePerson","attackParam":"PID_リベラ","move":"NearestEnemyExcludePerson","moveParam":"PID_リベラ"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[1,17],"to":[1,17],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ダークマージ","team":"enemy","at":[6,20],"to":[6,20],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_魔道士","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["normal"],"name":"Plegian","class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,16],"to":[10,16],"difficulties":["normal"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["normal"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["normal"],"name":"Plegian","class":"Archer","items":["Killer Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_サーリャ","team":"enemy","at":[15,19],"to":[15,19],"difficulties":["normal"],"name":"Tharja","class":"Dark Mage","items":["Elthunder","Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[17,20],"to":[17,20],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[18,16],"to":[18,16],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_009_魔道士","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["hard"],"name":"Plegian","class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,16],"to":[10,16],"difficulties":["hard"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["hard"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["hard"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["hard"],"name":"Plegian","class":"Archer","items":["Killer Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["hard"],"name":"Plegian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_サーリャ","team":"enemy","at":[15,19],"to":[15,19],"difficulties":["hard"],"name":"Tharja","class":"Dark Mage","items":["Elthunder","Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[17,20],"to":[17,20],"difficulties":["hard"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[18,16],"to":[18,16],"difficulties":["hard"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_魔道士","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["lunatic"],"name":"Plegian","class":"Mage","items":["Elfire"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,16],"to":[10,16],"difficulties":["lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ソルジャー","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["lunatic"],"name":"Plegian","class":"Archer","items":["Killer Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_アーチャー","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["lunatic"],"name":"Plegian","class":"Archer","items":["Killer Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_サーリャ","team":"enemy","at":[15,19],"to":[15,19],"difficulties":["lunatic"],"name":"Tharja","class":"Dark Mage","items":["Elthunder","Nosferatu"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[17,20],"to":[17,20],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[18,16],"to":[18,16],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_009_インバース","team":"enemy","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"name":"Aversa","class":"Dark Flier","items":["Goetia"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_009_ギャンレル","team":"enemy","at":[17,8],"to":[17,8],"difficulties":["normal","hard","lunatic"],"name":"Gangrel","class":"Trickster","items":["Levin Sword","Dragonstone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_リベラ","team":"ally","at":[2,20],"to":[2,20],"difficulties":["normal","hard"],"name":"Libra","class":"War Monk","items":["Killer Axe","Mend","Ward","Concoction"],"ai":{"start":"Everytime","mission":"Talk","missionParam":"PID_クロム","attack":"Attack","move":"Person","moveParam":"PID_クロム"},"group":0},
  {"faction":"Enemy","pid":"PID_リベラ","team":"ally","at":[2,20],"to":[2,20],"difficulties":["lunatic"],"name":"Libra","class":"War Monk","items":["Killer Axe","Mend","Ward","Concoction"],"ai":{"start":"Everytime","mission":"Talk","missionParam":"PID_クロム","attack":"Attack","move":"Person","moveParam":"PID_クロム"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[1,0],"to":[1,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[2,0],"to":[2,1],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[3,0],"to":[3,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[4,0],"to":[4,1],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[5,0],"to":[5,2],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_009_ドラゴンナイト","team":"enemy","at":[6,0],"to":[6,1],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_009_ソルジャー","team":"enemy","at":[13,15],"to":[13,15],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Reinforce02","pid":"PID_009_魔道士","team":"enemy","at":[15,15],"to":[15,15],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Mage","items":["Elwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Event01","pid":"PID_009_Ｐナイト１EV","team":"ally","at":[13,21],"to":[13,10],"difficulties":["normal","hard","lunatic"],"name":"Soldier","class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_009_フィレインEV","team":"ally","at":[14,21],"to":[14,10],"difficulties":["normal","hard","lunatic"],"name":"Phila","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_009_Ｐナイト２EV","team":"ally","at":[15,21],"to":[15,10],"difficulties":["normal","hard","lunatic"],"name":"Soldier","class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーEV","team":"enemy","at":[16,8],"to":[16,8],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーＢＴEV","team":"enemy","at":[19,9],"to":[19,9],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーEV","team":"enemy","at":[17,11],"to":[17,11],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーＢＴ２EV","team":"enemy","at":[14,9],"to":[14,9],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーEV","team":"enemy","at":[15,8],"to":[15,8],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーEV","team":"enemy","at":[18,7],"to":[18,7],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_009_アーチャーＢＴ３EV","team":"enemy","at":[16,11],"to":[16,11],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event03","pid":"PID_クロム","team":"player","name":"Chrom","at":[14,11],"to":[14,11],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event03","pid":"PID_プレイヤー男","team":"player","at":[15,12],"to":[15,12],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event03","pid":"PID_リズ","team":"player","name":"Lissa","at":[17,12],"to":[17,12],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event03","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[13,13],"to":[13,13],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event04","pid":"PID_009_バジーリオEV","team":"ally","at":[14,21],"to":[14,13],"difficulties":["normal","hard","lunatic"],"name":"Basilio","class":"Warrior","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event04","pid":"PID_009_フラヴィアEV","team":"ally","at":[15,21],"to":[15,13],"difficulties":["normal","hard","lunatic"],"name":"Flavia","class":"Hero","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
