/** Awakening: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 024, terrain 024). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_24 = {
 id: 'chapter-24', rom: '024', terrainFile: '024', width: 28, height: 23,
 rows: [
   "8888888888888888888888888888",
   "1111888888888888888888888888",
   "1111111111888888888888888888",
   "1111111111111118888888888888",
   "1133311111111111111188888888",
   "113j331133111111111111118888",
   "1111111111111113331111111111",
   "1111111111113313331131111111",
   "1111111113113313333331131111",
   "11331113331j133311vv31331131",
   "11331133v31133331133j1331131",
   "11111133v31133333vv311311131",
   "11111133v13333333vv311111111",
   "11111133313333v3113331111111",
   "11111111113333v3113333111111",
   "111111vv13333333111131111111",
   "111331111333333j331131331131",
   "1111133j13333311vv3111333131",
   "1111133333333331v33111333111",
   "1111133313331133333311333111",
   "11113331133vvv13331j11113111",
   "1113333111333333311333333311",
   "1111111111111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[3,13],"to":[3,13],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[3,6],"to":[3,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[4,9],"to":[4,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[5,11],"to":[5,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[2,14],"to":[2,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[5,14],"to":[5,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[3,16],"to":[3,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[4,18],"to":[4,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","at":[5,19],"to":[5,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","at":[3,20],"to":[3,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_024_ボス","team":"enemy","at":[25,13],"to":[25,13],"difficulties":["normal"],"class":"Great Knight","items":["Tomahawk","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_024_ボス","team":"enemy","at":[25,13],"to":[25,13],"difficulties":["hard"],"class":"Great Knight","items":["Tomahawk","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[24,12],"to":[24,12],"difficulties":["hard"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[24,14],"to":[24,14],"difficulties":["hard"],"class":"Great Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_024_ボス","team":"enemy","at":[25,13],"to":[25,13],"difficulties":["lunatic"],"class":"Great Knight","items":["Tomahawk","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[24,12],"to":[24,12],"difficulties":["lunatic"],"class":"Great Knight","items":["Tomahawk"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[24,14],"to":[24,14],"difficulties":["lunatic"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_024_パラディン","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_パラディン","team":"enemy","at":[9,20],"to":[9,20],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[10,18],"to":[10,18],"difficulties":["hard","lunatic"],"class":"Great Knight","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ヴァルキュリア","team":"enemy","at":[11,15],"to":[11,15],"difficulties":["normal","hard","lunatic"],"class":"Valkyrie","items":["Bolganone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ヴァルキュリア","team":"enemy","at":[11,17],"to":[11,17],"difficulties":["lunatic"],"class":"Valkyrie","items":["Rexcalibur"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ヴァルキュリア","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["hard","lunatic"],"class":"Valkyrie","items":["Thoron"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_パラディン","team":"enemy","at":[12,10],"to":[12,10],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Sword","Elixir"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ヴァルキュリア","team":"enemy","at":[13,21],"to":[13,21],"difficulties":["normal","hard","lunatic"],"class":"Valkyrie","items":["Thoron"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ボウナイト","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_パラディン","team":"enemy","at":[15,13],"to":[15,13],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[16,15],"to":[16,15],"difficulties":["lunatic"],"class":"Great Knight","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_パラディン","team":"enemy","at":[16,20],"to":[16,20],"difficulties":["hard","lunatic"],"class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ボウナイト","team":"enemy","at":[17,18],"to":[17,18],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_グレートナイト","team":"enemy","at":[18,10],"to":[18,10],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ヴァルキュリア","team":"enemy","at":[21,14],"to":[21,14],"difficulties":["normal","hard","lunatic"],"class":"Valkyrie","items":["Rexcalibur"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[16,11],"to":[16,11],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[19,7],"to":[19,7],"difficulties":["hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[20,13],"to":[20,13],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[20,17],"to":[20,17],"difficulties":["hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[22,5],"to":[22,5],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[22,21],"to":[22,21],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[23,7],"to":[23,7],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[23,19],"to":[23,19],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[25,8],"to":[25,8],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[25,18],"to":[25,18],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[20,10],"to":[20,10],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_024_ドラゴンマスター","team":"enemy","at":[19,20],"to":[19,20],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_024_パラディン","team":"enemy","at":[15,16],"to":[15,16],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_024_グレートナイト","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_024_グレートナイト","team":"enemy","at":[7,17],"to":[7,17],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_024_パラディン","team":"enemy","at":[3,5],"to":[3,5],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
