/** Two Falchions: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 004, terrain 004). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_4 = {
 id: 'chapter-4', rom: '004', terrainFile: '004', width: 16, height: 16,
 rows: [
   "EEExxxxxxxxxxEEE",
   "EExxxxxxxxxxxxEE",
   "ExxxxxxxxxxxxxxE",
   "xxxxxxxxxxxxxxxx",
   "xxyxxxxxxxxxxyxx",
   "xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxx",
   "xxyxxxxxxxxxxyxx",
   "xxxxxxxxxxxxxxxx",
   "ExxxxxxxxxxxxxxE",
   "EExxxxxxxxxxxxEE",
   "EEExxxxxxxxxxEEE"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[8,13],"to":[8,13],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[7,13],"to":[7,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[6,14],"to":[6,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[7,14],"to":[7,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[8,14],"to":[8,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_004_マルス","team":"enemy","at":[8,1],"to":[8,1],"difficulties":["normal","hard"],"class":"Lord","items":["Parallel Falchion"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_004_マルス","team":"enemy","at":[8,1],"to":[8,1],"difficulties":["lunatic"],"class":"Lord","items":["Parallel Falchion"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_004_戦士","team":"enemy","at":[1,10],"to":[1,10],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_戦士","team":"enemy","at":[14,10],"to":[14,10],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_魔道士","team":"enemy","at":[1,5],"to":[1,5],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Thunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_魔道士","team":"enemy","at":[14,5],"to":[14,5],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Thunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_アーマーナイト","team":"enemy","at":[5,2],"to":[5,2],"difficulties":["normal","hard","lunatic"],"class":"Knight","items":["Iron Lance","Vulnerary"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_アーマーナイト","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["normal","hard","lunatic"],"class":"Knight","items":["Iron Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_戦士","team":"enemy","at":[2,3],"to":[2,3],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Hand Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_004_戦士","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Hand Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_ロンクー","team":"player","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
