/** Shepherds: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 002, terrain 002). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_2 = {
 id: 'chapter-2', rom: '002', terrainFile: '002', width: 17, height: 22,
 rows: [
   "11111111111111111",
   "11111111111111331",
   "11311611111111331",
   "11116666111311131",
   "11136161111161111",
   "11111111311116661",
   "gggg1111j11j11161",
   "111ggg13111131111",
   "11111ggg111111311",
   "1113311gg11ggg111",
   "11111111geeg1gggg",
   "11111111111111111",
   "11331111j11j13311",
   "11331131111111111",
   "11111131111311111",
   "11161131111133111",
   "11166111111133111",
   "11666111111133111",
   "11111111111111111",
   "11113111111113311",
   "11133111113311111",
   "11111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[8,19],"to":[8,19],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,19],"to":[9,19],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[7,20],"to":[7,20],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[6,20],"to":[6,20],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[10,19],"to":[10,19],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[7,18],"to":[7,18],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[10,20],"to":[10,20],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[9,18],"to":[9,18],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[6,15],"to":[6,15],"difficulties":["normal"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[11,14],"to":[11,14],"difficulties":["normal"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[8,12],"to":[8,12],"difficulties":["normal"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["normal"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[10,9],"to":[10,9],"difficulties":["normal"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["normal"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["normal"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー_落下","team":"enemy","at":[5,6],"to":[5,6],"difficulties":["normal"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_傭兵_落下","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["normal"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["normal"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["normal"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ボス","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal"],"class":"Barbarian","items":["Hand Axe"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[4,16],"to":[4,16],"difficulties":["lunatic"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[13,16],"to":[13,16],"difficulties":["lunatic"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[6,15],"to":[6,15],"difficulties":["hard","lunatic"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[11,14],"to":[11,14],"difficulties":["hard","lunatic"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["hard","lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[14,13],"to":[14,13],"difficulties":["hard","lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[8,12],"to":[8,12],"difficulties":["hard","lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["hard","lunatic"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[10,9],"to":[10,9],"difficulties":["hard","lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["hard"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["hard"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ソルジャー_落下","team":"enemy","at":[5,6],"to":[5,6],"difficulties":["hard"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_傭兵_落下","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["hard"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["hard"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["hard"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ボス","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["hard"],"class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_002_傭兵","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["lunatic"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["lunatic"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ソルジャー_落下","team":"enemy","at":[5,6],"to":[5,6],"difficulties":["lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_傭兵_落下","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["lunatic"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_蛮族","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["lunatic"],"class":"Barbarian","items":["Iron Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ソルジャー","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["lunatic"],"class":"Soldier","items":["Iron Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_002_ボス","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["lunatic"],"class":"Barbarian","items":["Hand Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Support01","pid":"PID_ミリエル","team":"player","at":[8,21],"to":[8,20],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
