/** Renewal: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 010, terrain 010). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_10 = {
 id: 'chapter-10', rom: '010', terrainFile: '010', width: 26, height: 18,
 rows: [
   "22222222222222222222222222",
   "bb222222222222222222222222",
   "bb2j2222222222j22222222222",
   "bb22222222222222222222bbb2",
   "bb22bbbb22222222bbbb22bbb2",
   "bb22bbbb22bbbb22bbbb22bbb2",
   "bb22bbbb22bbbb22bbbb22bjb2",
   "bb22bbbb22bbbb22bbbb22bjb2",
   "bb22bbjb22bbbb22bbbb22bbb2",
   "bb22bbjb22bbbb22bbbb22bbb2",
   "2222bbbb22bbbb22bbbb22bbb2",
   "2222bbbb22bbbb22bbbb22bbb2",
   "2222bbbb22bbbb22bbbb222222",
   "2222222222bbbb222222222222",
   "22222222222222222222222j22",
   "222222222222j2222222222222",
   "22222222222222222222222222",
   "22222222222222222222222222"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[19,15],"to":[19,15],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[17,15],"to":[17,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[18,14],"to":[18,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[18,15],"to":[18,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[18,16],"to":[18,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[19,13],"to":[19,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[20,14],"to":[20,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[20,16],"to":[20,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[21,14],"to":[21,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[21,15],"to":[21,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[22,13],"to":[22,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[22,15],"to":[22,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[22,16],"to":[22,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_010_ボス","team":"enemy","at":[3,2],"to":[3,2],"difficulties":["normal","hard","lunatic"],"name":"Mustafa","class":"Berserker","items":["Short Axe","Beaststone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_010_盗賊","team":"enemy","at":[21,6],"to":[21,6],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Steel Sword","Bullion (M)"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(2,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(2,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_010_盗賊","team":"enemy","at":[15,10],"to":[15,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Wyrmslayer"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(2,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(2,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_010_盗賊","team":"enemy","at":[8,16],"to":[8,16],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Steel Sword","Master Seal"],"ai":{"start":"Everytime","mission":"EscapeSlow","missionParam":"pos(2,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(2,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_010_盗賊","team":"enemy","at":[1,16],"to":[1,16],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Steel Sword","Seraph Robe"],"ai":{"start":"Turn","startParam":"2","mission":"EscapeSlow","missionParam":"pos(2,1)","attack":"Null","move":"EscapeSlow","moveParam":"pos(2,1)"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[21,9],"to":[21,9],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[20,8],"to":[20,8],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[21,7],"to":[21,7],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[14,11],"to":[14,11],"difficulties":["lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[14,9],"to":[14,9],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[15,8],"to":[15,8],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[18,2],"to":[18,2],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[24,3],"to":[24,3],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[8,10],"to":[8,10],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[6,13],"to":[6,13],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[1,13],"to":[1,13],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[23,1],"to":[23,1],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[17,1],"to":[17,1],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[16,3],"to":[16,3],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Javelin"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[10,4],"to":[10,4],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[9,6],"to":[9,6],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[4,5],"to":[4,5],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["normal"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[5,1],"to":[5,1],"difficulties":["normal"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["normal"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_ソルジャー","team":"enemy","at":[5,1],"to":[5,1],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_010_蛮族","team":"enemy","at":[4,3],"to":[4,3],"difficulties":["lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Reinforce01","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[6,8],"to":[6,8],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[6,9],"to":[6,9],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[23,6],"to":[23,6],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[23,7],"to":[23,7],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_010_ドラゴンナイト","team":"enemy","at":[23,14],"to":[23,14],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_010_ソルジャー","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Soldier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_010_蛮族","team":"enemy","at":[12,15],"to":[12,15],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_010_オリヴィエEV","team":"ally","at":[2,0],"to":[2,2],"difficulties":["normal","hard","lunatic"],"name":"Olivia","class":"Dancer","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
