/** The Grimleal: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 008, terrain 008). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_8 = {
 id: 'chapter-8', rom: '008', terrainFile: '008', width: 18, height: 24,
 rows: [
   "444444444444444444",
   "444444411444444444",
   "4444444444RR444444",
   "44RRR44444RR444444",
   "44RRR44411444ttt44",
   "4444444b11444ttt44",
   "4444444bb11444m444",
   "444444444114444444",
   "41444444411b444444",
   "414444RR4444bb4444",
   "4444444R4444bb4444",
   "444444441114bbb444",
   "4ttt444411144bb444",
   "4ttt444111444bb444",
   "44m411411144444444",
   "444b44411441444444",
   "44bbb4444411444444",
   "44bbb4444411444444",
   "41bbb11444414ttt44",
   "4gbbb11444444ttt44",
   "4gbbgg11441144m444",
   "4gbbggg14114444444",
   "4gggggg14114444444",
   "444444444444444444"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[7,2],"to":[7,2],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[6,3],"to":[6,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[8,3],"to":[8,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[5,2],"to":[5,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[8,2],"to":[8,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[6,1],"to":[6,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[7,1],"to":[7,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_008_ボス","team":"enemy","at":[9,22],"to":[9,22],"difficulties":["normal","hard","lunatic"],"name":"Chalard","class":"Dark Mage","items":["Nosferatu","Energy Drop"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[7,21],"to":[7,21],"difficulties":["normal"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[10,21],"to":[10,21],"difficulties":["normal"],"name":"Unknown","class":"Myrmidon","items":["Killing Edge"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[13,21],"to":[13,21],"difficulties":["normal"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[7,21],"to":[7,21],"difficulties":["hard"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[10,21],"to":[10,21],"difficulties":["hard"],"name":"Unknown","class":"Myrmidon","items":["Killing Edge"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[13,21],"to":[13,21],"difficulties":["hard"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[9,20],"to":[9,20],"difficulties":["hard"],"name":"Unknown","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[12,22],"to":[12,22],"difficulties":["hard"],"name":"Unknown","class":"Dark Mage","items":["Wind"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[7,21],"to":[7,21],"difficulties":["lunatic"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[10,21],"to":[10,21],"difficulties":["lunatic"],"name":"Unknown","class":"Myrmidon","items":["Killing Edge"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[13,21],"to":[13,21],"difficulties":["lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[9,20],"to":[9,20],"difficulties":["lunatic"],"name":"Unknown","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[12,22],"to":[12,22],"difficulties":["lunatic"],"name":"Unknown","class":"Dark Mage","items":["Wind"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[1,15],"to":[1,15],"difficulties":["normal"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[1,15],"to":[1,15],"difficulties":["hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[1,17],"to":[1,17],"difficulties":["hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Wind"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[13,1],"to":[13,1],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[1,4],"to":[1,4],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Fire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[4,6],"to":[4,6],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[12,6],"to":[12,6],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ソシアルナイト","team":"enemy","at":[7,8],"to":[7,8],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ソシアルナイト","team":"enemy","at":[4,11],"to":[4,11],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[14,14],"to":[14,14],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_戦士","team":"enemy","at":[11,16],"to":[11,16],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[15,16],"to":[15,16],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Thunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ダークマージ","team":"enemy","at":[5,17],"to":[5,17],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_剣士","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ソシアルナイト","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_008_ソシアルナイト","team":"enemy","at":[6,20],"to":[6,20],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_ノノ","team":"player","name":"Nowi","at":[17,15],"to":[13,15],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Support02","pid":"PID_グレゴ","team":"player","name":"Gregor","at":[17,15],"to":[14,15],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
