/** Of Sacred Blood: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 013, terrain 013). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_13 = {
 id: 'chapter-13', rom: '013', terrainFile: '013', width: 18, height: 28,
 rows: [
   "111111111111111111",
   "111111888888111311",
   "11j111eeeeee11j111",
   "111311888888811111",
   "111181811111813111",
   "111181813111811111",
   "111181111118811111",
   "111181111318111131",
   "111188111118131111",
   "111118811188111111",
   "113111881181111111",
   "111111181181111111",
   "131111181188111311",
   "111131881188111111",
   "11111181111811j111",
   "111j11813118811111",
   "111118811138811111",
   "111118111111811111",
   "113118111111818111",
   "111118111311818111",
   "111818111133118131",
   "111818111111118811",
   "111811111111118811",
   "111811111311111811",
   "118811j11j11j11811",
   "118111111111111811",
   "118111111111111811",
   "111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[9,17],"to":[9,17],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[8,15],"to":[8,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[8,16],"to":[8,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[10,16],"to":[10,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[7,17],"to":[7,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[8,18],"to":[8,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[10,18],"to":[10,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[7,19],"to":[7,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[11,19],"to":[11,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[8,20],"to":[8,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[10,20],"to":[10,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_013_ボス","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"name":"Risen Chief","class":"Warrior","items":["Short Axe","Secret Book"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[8,25],"to":[8,25],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[10,25],"to":[10,25],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[7,26],"to":[7,26],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[11,26],"to":[11,26],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[5,25],"to":[5,25],"difficulties":["hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[13,25],"to":[13,25],"difficulties":["hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[4,21],"to":[4,21],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[1,20],"to":[1,20],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Hand Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[3,17],"to":[3,17],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[13,19],"to":[13,19],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[16,18],"to":[16,18],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[14,15],"to":[14,15],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Longbow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[4,13],"to":[4,13],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Longbow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_スナイパー","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[3,10],"to":[3,10],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Hand Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[1,9],"to":[1,9],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Longbow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Longbow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_スナイパー","team":"enemy","at":[15,10],"to":[15,10],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Hand Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[3,3],"to":[3,3],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"MustAttack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_ウォーリアー","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Warrior","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_剣士","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[9,6],"to":[9,6],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Hand Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_戦士","team":"enemy","at":[5,5],"to":[5,5],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_013_アーチャー","team":"enemy","at":[10,5],"to":[10,5],"difficulties":["hard","lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_ヘンリー","team":"player","name":"Henry","at":[9,27],"to":[9,27],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Support02","pid":"PID_マルス","team":"player","name":"Lucina","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Reinforce01","pid":"PID_013_剣士","team":"enemy","at":[6,24],"to":[6,24],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_013_戦士","team":"enemy","at":[9,24],"to":[9,24],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_013_剣士","team":"enemy","at":[12,24],"to":[12,24],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_013_ウォーリアー","team":"enemy","at":[6,24],"to":[6,24],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Warrior","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_013_ウォーリアー","team":"enemy","at":[9,24],"to":[9,24],"difficulties":["hard","lunatic"],"name":"Risen","class":"Warrior","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_013_ウォーリアー","team":"enemy","at":[12,24],"to":[12,24],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Warrior","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_013_戦士","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_013_剣士","team":"enemy","at":[14,14],"to":[14,14],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_013_剣士","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_013_戦士","team":"enemy","at":[14,14],"to":[14,14],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_013_戦士","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_013_剣士","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce09","pid":"PID_013_スナイパー","team":"enemy","at":[3,15],"to":[3,15],"difficulties":["lunatic"],"name":"Risen","class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce10","pid":"PID_013_スナイパー","team":"enemy","at":[14,14],"to":[14,14],"difficulties":["lunatic"],"name":"Risen","class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_013_屍兵EV","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Assassin","items":["Killing Edge"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event02","pid":"PID_013_マルスEV","team":"ally","at":[3,0],"to":[7,2],"difficulties":["normal","hard","lunatic"],"name":"Marth","class":"Lord","items":["Parallel Falchion"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event03","pid":"PID_クロム","team":"player","name":"Chrom","at":[8,2],"to":[8,2],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event03","pid":"PID_プレイヤー男","team":"player","at":[10,2],"to":[10,2],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
