/** Flames on the Blue: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 014, terrain 014). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_14 = {
 id: 'chapter-14', rom: '014', terrainFile: '014', width: 22, height: 22,
 rows: [
   "=ccc=hhhh===hhhh====hh",
   "cC-Cc=hh=ccc=hh=cCCc=h",
   "c-C-Cc==ccccc===c--C==",
   "--C--c==c---c==c---Cc=",
   "--d--c=c--C--c=c----c=",
   "-----c=c--C--c=c----c=",
   "-----c=c--d--c=c---Hc=",
   "-----c=c-----c=c---Hc=",
   "-----c=c-----------Cc=",
   "-------------c==c-CC==",
   "-------------c==cccc=h",
   "-----c=c-----c=======h",
   "cC--cc=cC----c==h=hhhh",
   "cc-cc==cC----c==hhhhhh",
   "=ccc==h=cC---===hhhhhh",
   "==c==hh=cccc-===hhhhhh",
   "h===hhhh====-cc==hhhhh",
   "hhhhhhhhh===---c==hhhh",
   "hhhhhhhhh==c---Hc=hhhh",
   "hhhhhhhhh==c---Cc=hhhh",
   "hhhhhhhhh==c---Cc=hhhh",
   "hhhhhhhhh==c----c==hhh"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[10,9],"to":[10,9],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,6],"to":[9,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[9,7],"to":[9,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[10,7],"to":[10,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[9,8],"to":[9,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[11,8],"to":[11,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[11,9],"to":[11,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[9,10],"to":[9,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[10,10],"to":[10,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[9,11],"to":[9,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[11,11],"to":[11,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[10,12],"to":[10,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_014_ボス","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear","Master Seal"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[4,4],"to":[4,4],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[4,5],"to":[4,5],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[16,3],"to":[16,3],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[17,4],"to":[17,4],"difficulties":["hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[6,17],"to":[6,17],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[4,19],"to":[4,19],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[8,19],"to":[8,19],"difficulties":["hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[19,12],"to":[19,12],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[20,16],"to":[20,16],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ペガサスナイト","team":"enemy","at":[17,19],"to":[17,19],"difficulties":["lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["normal"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["normal"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[3,11],"to":[3,11],"difficulties":["normal"],"class":"Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[4,7],"to":[4,7],"difficulties":["normal"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["normal"],"class":"Cavalier","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[2,9],"to":[2,9],"difficulties":["normal"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["normal"],"class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["normal"],"class":"Mage","items":["Elwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,10],"to":[1,10],"difficulties":["normal"],"class":"Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["normal"],"class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_グレートナイト","team":"enemy","at":[1,6],"to":[1,6],"difficulties":["normal"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["hard"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["hard"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[3,11],"to":[3,11],"difficulties":["hard"],"class":"Knight","items":["Short Spear"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[4,7],"to":[4,7],"difficulties":["hard"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["hard"],"class":"Cavalier","items":["Short Spear"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[2,9],"to":[2,9],"difficulties":["hard"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["hard"],"class":"Mage","items":["Elfire"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["hard"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,10],"to":[1,10],"difficulties":["hard"],"class":"Mage","items":["Elthunder"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["hard"],"class":"General","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_グレートナイト","team":"enemy","at":[1,6],"to":[1,6],"difficulties":["hard"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["lunatic"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["lunatic"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[3,11],"to":[3,11],"difficulties":["lunatic"],"class":"Knight","items":["Short Spear"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[4,7],"to":[4,7],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["lunatic"],"class":"Cavalier","items":["Short Spear"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[2,9],"to":[2,9],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[1,10],"to":[1,10],"difficulties":["lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["lunatic"],"class":"General","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_グレートナイト","team":"enemy","at":[1,6],"to":[1,6],"difficulties":["lunatic"],"class":"Great Knight","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[17,8],"to":[17,8],"difficulties":["normal","hard"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[17,6],"to":[17,6],"difficulties":["normal","hard"],"class":"Knight","items":["Short Spear","Chest Key"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[16,4],"to":[16,4],"difficulties":["normal","hard"],"class":"Cavalier","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[17,2],"to":[17,2],"difficulties":["normal","hard"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["normal","hard"],"class":"Mage","items":["Elthunder"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[19,4],"to":[19,4],"difficulties":["normal","hard"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_グレートナイト","team":"enemy","at":[18,3],"to":[18,3],"difficulties":["normal","hard"],"class":"Great Knight","items":["Short Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[17,8],"to":[17,8],"difficulties":["lunatic"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[17,6],"to":[17,6],"difficulties":["lunatic"],"class":"Knight","items":["Short Spear","Chest Key"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[16,4],"to":[16,4],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[17,2],"to":[17,2],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[19,4],"to":[19,4],"difficulties":["lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_グレートナイト","team":"enemy","at":[18,3],"to":[18,3],"difficulties":["lunatic"],"class":"Great Knight","items":["Short Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[14,17],"to":[14,17],"difficulties":["normal"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["normal"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["normal"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[14,18],"to":[14,18],"difficulties":["normal"],"class":"Cavalier","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["normal"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[14,19],"to":[14,19],"difficulties":["normal"],"class":"General","items":["Silver Lance","Talisman"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[14,17],"to":[14,17],"difficulties":["hard"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["hard"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["hard"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[14,18],"to":[14,18],"difficulties":["hard"],"class":"Cavalier","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["hard"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[14,19],"to":[14,19],"difficulties":["hard"],"class":"General","items":["Silver Lance","Talisman"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[14,17],"to":[14,17],"difficulties":["lunatic"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_アーマーナイト","team":"enemy","at":[12,19],"to":[12,19],"difficulties":["lunatic"],"class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[13,18],"to":[13,18],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ソシアルナイト","team":"enemy","at":[14,18],"to":[14,18],"difficulties":["lunatic"],"class":"Cavalier","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_魔道士","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_014_ジェネラル","team":"enemy","at":[14,19],"to":[14,19],"difficulties":["lunatic"],"class":"General","items":["Silver Lance","Talisman"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_014_ペガサスナイト","team":"enemy","at":[5,21],"to":[5,19],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_014_ペガサスナイト","team":"enemy","at":[6,21],"to":[6,20],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_014_ペガサスナイト","team":"enemy","at":[7,21],"to":[7,20],"difficulties":["hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_014_ペガサスナイト","team":"enemy","at":[21,13],"to":[20,13],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_014_ペガサスナイト","team":"enemy","at":[21,14],"to":[20,14],"difficulties":["hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_014_ペガサスナイト","team":"enemy","at":[21,15],"to":[19,15],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_014_ペガサスナイト","team":"enemy","at":[7,0],"to":[7,1],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_014_ペガサスナイト","team":"enemy","at":[6,0],"to":[6,2],"difficulties":["normal","hard","lunatic"],"class":"Pegasus Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_014_ペガサスナイト","team":"enemy","at":[6,0],"to":[6,1],"difficulties":["hard","lunatic"],"class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
