/** The Exalt and the King: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 005, terrain 005). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_5 = {
 id: 'chapter-5', rom: '005', terrainFile: '005', width: 18, height: 22,
 rows: [
   "888881111188888888",
   "811111111111111111",
   "111j1111111111j111",
   "11j131111188811111",
   "111111111188881111",
   "888811113188888888",
   "888888111111118888",
   "8888888j1311111111",
   "888888818888811111",
   "111188818888881131",
   "111111118888881118",
   "111111131111181118",
   "13j11111131j111318",
   "811888111111111111",
   "811888888881111111",
   "811888888881881111",
   "111111888881888888",
   "111111111111888888",
   "113111111111188888",
   "111j11111311111111",
   "111111111133111111",
   "111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[10,19],"to":[10,19],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[10,18],"to":[10,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[11,18],"to":[11,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[12,19],"to":[12,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[13,19],"to":[13,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[9,20],"to":[9,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[11,20],"to":[11,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[12,20],"to":[12,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[14,20],"to":[14,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_005_ボス","team":"enemy","at":[8,1],"to":[8,1],"difficulties":["normal"],"name":"Orton","class":"Wyvern Rider","items":["Short Axe","Bullion (M)"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["normal"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ボス","team":"enemy","at":[8,1],"to":[8,1],"difficulties":["hard","lunatic"],"name":"Orton","class":"Wyvern Rider","items":["Short Axe","Bullion (M)"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[4,1],"to":[4,1],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[12,1],"to":[12,1],"difficulties":["lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[5,2],"to":[5,2],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[6,17],"to":[6,17],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_剣士","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[5,20],"to":[5,20],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ダークマージ","team":"enemy","at":[3,19],"to":[3,19],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[11,13],"to":[11,13],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_剣士","team":"enemy","at":[12,14],"to":[12,14],"difficulties":["hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ダークマージ","team":"enemy","at":[10,11],"to":[10,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_剣士","team":"enemy","at":[7,10],"to":[7,10],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[5,12],"to":[5,12],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_魔道士","team":"enemy","at":[3,11],"to":[3,11],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Mage","items":["Fire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[10,7],"to":[10,7],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_剣士","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_ダークマージ","team":"enemy","at":[9,6],"to":[9,6],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Dark Mage","items":["Flux"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_蛮族","team":"enemy","at":[7,5],"to":[7,5],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_005_剣士","team":"enemy","at":[6,6],"to":[6,6],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_005_蛮族","team":"enemy","at":[3,19],"to":[3,19],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_005_蛮族","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_005_剣士","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_005_ダークマージ","team":"enemy","at":[3,19],"to":[3,19],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_005_剣士","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Myrmidon","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_005_蛮族","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[3,2],"to":[3,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[2,3],"to":[2,3],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[3,2],"to":[3,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce09","pid":"PID_005_ドラゴンナイト","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["normal","hard","lunatic"],"name":"Plegian","class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_リヒト","team":"player","name":"Ricken","at":[17,8],"to":[15,10],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Support01","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[17,9],"to":[16,11],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_005_ギャンレルEV","team":"enemy","at":[7,0],"to":[7,2],"difficulties":["normal","hard","lunatic"],"name":"Gangrel","class":"Trickster","items":["Levin Sword","Dragonstone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
