/** Mad King Gangrel: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 011, terrain 011). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_11 = {
 id: 'chapter-11', rom: '011', terrainFile: '011', width: 22, height: 28,
 rows: [
   "2222222222222222222222",
   "22222222g2222222222232",
   "22j22j2gg2222222222232",
   "2222222g22223222222232",
   "222j222e22232222332222",
   "2222222g22222222332222",
   "2222gegg22222223332222",
   "2222g22222223223332222",
   "ggggg22222222223322222",
   "2222222222322222223322",
   "2222222222222222223322",
   "2222222222222222222222",
   "2222223222222222222222",
   "222223332j223233322222",
   "22j2223322223333322222",
   "22222232222j333322jj22",
   "2222222222222332222222",
   "22332H2223222222222222",
   "22222222223222H3222332",
   "2222222222222223222222",
   "2222222222222222222222",
   "6666222222222222222222",
   "6666622222222222222222",
   "666666622j2j2j22266622",
   "6666666662222226666662",
   "6666666662222266666662",
   "6666666662222666666662",
   "2222222222222222222222"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[15,3],"to":[15,3],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[13,4],"to":[13,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[14,4],"to":[14,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[15,4],"to":[15,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[16,4],"to":[16,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[17,4],"to":[17,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[14,3],"to":[14,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[17,3],"to":[17,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[18,3],"to":[18,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[13,2],"to":[13,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[16,2],"to":[16,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[17,2],"to":[17,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_011_ボス","team":"enemy","at":[11,23],"to":[11,23],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Dragonstone"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_011_盗賊","team":"enemy","at":[19,21],"to":[19,21],"difficulties":["normal","hard","lunatic"],"class":"Thief","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Treasure","missionParam":"pos(5,17)","attack":"Null","move":"TrasureToEscape","moveParam":"pos(5,17),0,pos(20,21)"},"group":0},
  {"faction":"Enemy","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[3,23],"to":[3,23],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[5,24],"to":[5,24],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[16,25],"to":[16,25],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[19,24],"to":[19,24],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_傭兵","team":"enemy","at":[8,13],"to":[8,13],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_戦士","team":"enemy","at":[5,12],"to":[5,12],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_戦士","team":"enemy","at":[7,16],"to":[7,16],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_傭兵","team":"enemy","at":[4,15],"to":[4,15],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_勇者","team":"enemy","at":[6,14],"to":[6,14],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Steel Sword","Master Seal"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[18,14],"to":[18,14],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Thunder"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[15,15],"to":[15,15],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[19,17],"to":[19,17],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[16,18],"to":[16,18],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Thunder"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_賢者","team":"enemy","at":[17,16],"to":[17,16],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Elfire","Spirit Dust"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_011_傭兵","team":"enemy","at":[9,20],"to":[9,20],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_011_傭兵","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[10,21],"to":[10,21],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_011_魔道士","team":"enemy","at":[12,21],"to":[12,21],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_011_戦士","team":"enemy","at":[8,22],"to":[8,22],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_011_戦士","team":"enemy","at":[14,22],"to":[14,22],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Support01","pid":"PID_オリヴィエ","team":"player","at":[15,0],"to":[15,2],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Reinforce01","pid":"PID_011_戦士","team":"enemy","at":[2,14],"to":[2,14],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_011_傭兵","team":"enemy","at":[9,13],"to":[9,13],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_011_戦士","team":"enemy","at":[11,15],"to":[11,15],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_011_魔道士","team":"enemy","at":[18,15],"to":[18,15],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Fire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_011_魔道士","team":"enemy","at":[19,15],"to":[19,15],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_011_戦士","team":"enemy","at":[5,2],"to":[5,2],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_011_傭兵","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Armorslayer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_011_勇者","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Steel Axe","Speedwing"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[9,23],"to":[9,23],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[13,23],"to":[13,23],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_011_傭兵","team":"enemy","at":[5,2],"to":[5,2],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_011_戦士","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_011_魔道士","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[9,23],"to":[9,23],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_011_ドラゴンナイト","team":"enemy","at":[13,23],"to":[13,23],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_クロム","team":"player","at":[11,23],"to":[11,23],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_プレイヤー男","team":"player","at":[10,23],"to":[10,23],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_リズ","team":"player","at":[10,22],"to":[10,22],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_011_バジーリオEV","team":"ally","at":[11,25],"to":[11,25],"difficulties":["normal","hard","lunatic"],"class":"Warrior","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_011_フラヴィアEV","team":"ally","at":[10,25],"to":[10,25],"difficulties":["normal","hard","lunatic"],"class":"Hero","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event06","pid":"PID_スミア","team":"player","at":[21,23],"to":[12,23],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event08","pid":"PID_ソワレ","team":"player","at":[21,23],"to":[12,23],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event10","pid":"PID_マリアベル","team":"player","at":[21,23],"to":[12,23],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
