/** Foreseer: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 006, terrain 006). Don't hand-edit: re-extract. */
export const MAP_CHAPTER_6 = {
 id: 'chapter-6', rom: '006', terrainFile: '006', width: 22, height: 22,
 rows: [
   "1111111111111111111111",
   "1xxxxExxxxxExxxHExxxx1",
   "1xxxxExxxxxExxxxExxxx1",
   "1xzxxExzxzxxxxxxExzxz1",
   "1xxxxxxxxxxExxxxExxxx1",
   "1xxxxxxxxxxEExxEExxxx1",
   "1xzxxExzxzxEEGGEExzxz1",
   "1xxxxExxxxxxxxxxxxxxx1",
   "1xxxxExxxxxxxxxxxxxxx1",
   "1EExxEEEEEExEEEEEExxE1",
   "1EExxEEEEEExEEEEEExxE1",
   "1xxxxxxxxxxxxxxxxxxxx1",
   "1xxxxzxxxzxxxzxxxzxxx1",
   "1xxxxzxxxzxxxzxxxzxxx1",
   "1xxxxxxxxxxxxxxxxxxxx1",
   "1EExxEEEEEEEEEEEEExxE1",
   "1EExxEEEEEEEEEEEEExxE1",
   "1EExxEEEEEEEEEEEEExxE1",
   "1111133111333111331111",
   "1111133111333111331111",
   "1111111111111111111111",
   "1111111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[8,4],"to":[8,4],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[8,2],"to":[8,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[9,3],"to":[9,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[7,4],"to":[7,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[8,5],"to":[8,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[19,3],"to":[19,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[17,4],"to":[17,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[19,4],"to":[19,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[18,5],"to":[18,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[19,5],"to":[19,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_006_ボス","team":"enemy","at":[11,20],"to":[11,20],"difficulties":["normal","hard","lunatic"],"name":"Validar","class":"Sorcerer","items":["Elfire","Heal"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[4,7],"to":[4,7],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_ガイア","team":"enemy","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"name":"Gaius","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[3,10],"to":[3,10],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Wind"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_盗賊","team":"enemy","at":[4,15],"to":[4,15],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_盗賊","team":"enemy","at":[19,12],"to":[19,12],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[18,13],"to":[18,13],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[19,14],"to":[19,14],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[11,8],"to":[11,8],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_盗賊","team":"enemy","at":[12,12],"to":[12,12],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[10,14],"to":[10,14],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_盗賊","team":"enemy","at":[7,14],"to":[7,14],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[5,13],"to":[5,13],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[15,13],"to":[15,13],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Thunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ソシアルナイト","team":"enemy","at":[6,20],"to":[6,20],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ソシアルナイト","team":"enemy","at":[7,19],"to":[7,19],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ソシアルナイト","team":"enemy","at":[16,20],"to":[16,20],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ソシアルナイト","team":"enemy","at":[15,19],"to":[15,19],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Cavalier","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[8,20],"to":[8,20],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[9,19],"to":[9,19],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_ダークマージ","team":"enemy","at":[14,20],"to":[14,20],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Dark Mage","items":["Flux"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_戦士","team":"enemy","at":[13,19],"to":[13,19],"difficulties":["normal","hard","lunatic"],"name":"Unknown","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_006_エメリナ","move":"Person","moveParam":"PID_006_エメリナ"},"group":0},
  {"faction":"Enemy","pid":"PID_006_エメリナ","team":"ally","at":[14,2],"to":[14,2],"difficulties":["normal","hard","lunatic"],"name":"Emmeryn","class":"Sage","ai":{"start":"Everytime","mission":"Null","attack":"Null","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_006_マルス","team":"ally","at":[13,7],"to":[13,7],"difficulties":["normal","hard","lunatic"],"name":"Marth","class":"Lord","items":["Parallel Falchion"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Support01","pid":"PID_ベルベット","team":"player","name":"Panne","at":[6,1],"to":[8,1],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
