/** Grima: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM 026, terrain 026). Don't hand-edit: re-extract. */
export const MAP_ENDGAME = {
 id: 'endgame', rom: '026', terrainFile: '026', width: 27, height: 28,
 rows: [
   "QQQQQQPPPPPPPPPPPPPPPQQQQQQ",
   "QQQQQQQPPOOPPNPPOOPPQQQQQQQ",
   "QQQQQQQPPPPPPPPPPPPPQQQQQQQ",
   "QQQQQQQPPPPPPPPPPPPPQQQQQQQ",
   "QQOQQQQQPPPPPPPPPPPQQQQQOQQ",
   "QQOQQQQQPPPPPPPPPPPQQQQQOQQ",
   "QQQQQQQPPPPPPPPPPPPPQQQQQQQ",
   "QQOQQQPPPPPPPPPPPPPPPQQQOQQ",
   "QQOQQPPPPPPPPPPPPPPPPPQQOQQ",
   "QQQQQPPPPPPPPPPPPPPPPPQQQQQ",
   "QQQQQPPPPPPPPPPPPPPPPPQQQQQ",
   "aaQQPPPPPPPPPPPPPPPPPPPQQaa",
   "aaaQPPPPPPPPPPPPPPPPPPPQaaa",
   "aaaQPPPPPPPPPPPPPPPPPPPQaaa",
   "aaaQPPPPPPPPPPPPPPPPPPPQaaa",
   "aaaQPPPPPPPPPPPPPPPPPPPQaaa",
   "aaaQPPPPPPPPPPPPPPPPPPPQaaa",
   "aaaQQQPPPPPPPPPPPPPPPQQQaaa",
   "QQOQQPPPPPPPPPPPPPPPPPQQOQQ",
   "QQOQQPPPPPPPPPPPPPPPPPQQOQQ",
   "QQQQPPPPPPPPPPPPPPPPPPPQQQQ",
   "QQOQPPPPPPPPPPPPPPPPPPPQOQQ",
   "QQOQPPPPPPPPPPPPPPPPPPPQOQQ",
   "QQQQPPPPPPPPPPPPPPPPPPPQQQQ",
   "QQQQQPPPPPPPPPPPPPPPPPQQQQQ",
   "QQQQQPPPPPPPPPPPPPPPPPQQQQQ",
   "QQQQQPPPPOOPPPPPOOPPPPQQQQQ",
   "QQQQQPPPPPPPPPPPPPPPPPQQQQQ"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[13,19],"to":[13,19],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[12,16],"to":[12,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[14,16],"to":[14,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[11,17],"to":[11,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[13,17],"to":[13,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[15,17],"to":[15,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[12,18],"to":[12,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[14,18],"to":[14,18],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[11,19],"to":[11,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[15,19],"to":[15,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[12,20],"to":[12,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[13,20],"to":[13,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[14,20],"to":[14,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","at":[11,21],"to":[11,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","at":[13,21],"to":[13,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_グレゴ","team":"player","at":[15,21],"to":[15,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_026_ボス","team":"enemy","at":[13,1],"to":[13,1],"difficulties":["normal","hard","lunatic"],"class":"Grima","items":["Expiration"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バーサーカー","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[12,3],"to":[12,3],"difficulties":["hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バーサーカー","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[14,3],"to":[14,3],"difficulties":["hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バーサーカー","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[15,1],"to":[15,1],"difficulties":["hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_パラディン","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_スナイパー","team":"enemy","at":[10,1],"to":[10,1],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_グレートナイト","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Axe","Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_アサシン","team":"enemy","at":[17,1],"to":[17,1],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Killing Edge","Killer Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ジェネラル","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_グリフォンナイト","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Hammer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_勇者","team":"enemy","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ボウナイト","team":"enemy","at":[24,4],"to":[24,4],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バトルモンク","team":"enemy","at":[24,5],"to":[24,5],"difficulties":["normal","hard","lunatic"],"class":"War Monk","items":["Killer Axe","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ソードマスター","team":"enemy","at":[24,7],"to":[24,7],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ドラゴンマスター","team":"enemy","at":[24,8],"to":[24,8],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_トリックスター","team":"enemy","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ウォーリアー","team":"enemy","at":[2,19],"to":[2,19],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ダークペガサス","team":"enemy","at":[2,21],"to":[2,21],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ソーサラー","team":"enemy","at":[2,22],"to":[2,22],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Waste","Mire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バーサーカー","team":"enemy","at":[24,18],"to":[24,18],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ヴァルキュリア","team":"enemy","at":[24,19],"to":[24,19],"difficulties":["normal","hard","lunatic"],"class":"Valkyrie","items":["Rexcalibur","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_グレートナイト","team":"enemy","at":[24,21],"to":[24,21],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Axe","Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_賢者","team":"enemy","at":[24,22],"to":[24,22],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Bolganone","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ダークナイト","team":"enemy","at":[9,26],"to":[9,26],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_パラディン","team":"enemy","at":[10,26],"to":[10,26],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_ファルコンナイト","team":"enemy","at":[16,26],"to":[16,26],"difficulties":["normal","hard","lunatic"],"class":"Falcon Knight","items":["Beast Killer","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_026_バーサーカー","team":"enemy","at":[17,26],"to":[17,26],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition001","pid":"PID_ダミー","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition001","pid":"PID_ダミー","team":"enemy","at":[10,1],"to":[10,1],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition001","pid":"PID_ダミー","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition001","pid":"PID_ダミー","team":"enemy","at":[17,1],"to":[17,1],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition002","pid":"PID_ダミー","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition002","pid":"PID_ダミー","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition002","pid":"PID_ダミー","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition002","pid":"PID_ダミー","team":"enemy","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition003","pid":"PID_ダミー","team":"enemy","at":[24,4],"to":[24,4],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition003","pid":"PID_ダミー","team":"enemy","at":[24,5],"to":[24,5],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition003","pid":"PID_ダミー","team":"enemy","at":[24,7],"to":[24,7],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition003","pid":"PID_ダミー","team":"enemy","at":[24,8],"to":[24,8],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition004","pid":"PID_ダミー","team":"enemy","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition004","pid":"PID_ダミー","team":"enemy","at":[2,19],"to":[2,19],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition004","pid":"PID_ダミー","team":"enemy","at":[2,21],"to":[2,21],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition004","pid":"PID_ダミー","team":"enemy","at":[2,22],"to":[2,22],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition005","pid":"PID_ダミー","team":"enemy","at":[24,18],"to":[24,18],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition005","pid":"PID_ダミー","team":"enemy","at":[24,19],"to":[24,19],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition005","pid":"PID_ダミー","team":"enemy","at":[24,21],"to":[24,21],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition005","pid":"PID_ダミー","team":"enemy","at":[24,22],"to":[24,22],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition006","pid":"PID_ダミー","team":"enemy","at":[9,26],"to":[9,26],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition006","pid":"PID_ダミー","team":"enemy","at":[10,26],"to":[10,26],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition006","pid":"PID_ダミー","team":"enemy","at":[16,26],"to":[16,26],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementPosition006","pid":"PID_ダミー","team":"enemy","at":[17,26],"to":[17,26],"difficulties":["normal","hard","lunatic"],"class":"DUMMY","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate001","pid":"PID_026_パラディン","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate002","pid":"PID_026_グレートナイト","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Great Knight","items":["Silver Axe","Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate003","pid":"PID_026_ジェネラル","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate004","pid":"PID_026_バーサーカー","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate005","pid":"PID_026_ウォーリアー","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate006","pid":"PID_026_勇者","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate007","pid":"PID_026_ボウナイト","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate008","pid":"PID_026_スナイパー","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate009","pid":"PID_026_ソードマスター","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate010","pid":"PID_026_アサシン","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Killing Edge","Killer Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate011","pid":"PID_026_トリックスター","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate012","pid":"PID_026_ファルコンナイト","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Falcon Knight","items":["Beast Killer","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate013","pid":"PID_026_ダークペガサス","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate014","pid":"PID_026_ドラゴンマスター","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate015","pid":"PID_026_グリフォンナイト","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Hammer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate016","pid":"PID_026_ヴァルキュリア","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Valkyrie","items":["Rexcalibur","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate017","pid":"PID_026_バトルモンク","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"War Monk","items":["Killer Axe","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate018","pid":"PID_026_賢者","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Bolganone","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate019","pid":"PID_026_ダークナイト","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"ReinforcementCreate020","pid":"PID_026_ソーサラー","team":"enemy","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Waste","Mire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_プレイヤー男","team":"player","at":[12,19],"to":[12,19],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
