/** The Wellspring of Truth: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X022, terrain X022). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_22 = {
 id: 'paralogue-22', rom: 'X022', terrainFile: 'X022', width: 20, height: 27,
 rows: [
   "xxxxxEEEEEEEEEExxxxx",
   "xEEEEExxxxxxxxEEEEEx",
   "xEExxxxxxxxxxxxxxEEx",
   "xEExxxxEEEEEExxxxEEx",
   "xExxxxxxxxxxxxxxxxEx",
   "xExxxExxxxxxxxExxxEx",
   "xExxxExxWWWWxxExxxEx",
   "xExxxExxWWWWxxExxxEx",
   "xExxxxxxWWWWxxxxxxEx",
   "xExxxxxxxxxxxxxxxxEx",
   "xExxxExxxxxxxxExxxEx",
   "xExxxEEEExxEEEExxxEx",
   "xExxxxxxxxxxxxxxxxEx",
   "xExxxxxxxxxxxxxxxxEx",
   "xEExxEEEExxEEEExxEEx",
   "xEExxxxxExxExxxxxEEx",
   "xEExxxxxExxExxxxxEEx",
   "xEEExxEEExxEEExxEEEx",
   "xEEExxxxxxxxxxxxEEEx",
   "xEEExxxxxxxxxxxxEEEx",
   "xEExxxEEExxEEExxxEEx",
   "xEExxxxxxxxxxxxxxEEx",
   "xEExxxxxxxxxxxxxxEEx",
   "xEExxxxxxxxxxxxxxEEx",
   "xEExxxxExxxxExxxxEEx",
   "xEExxxxExxxxExxxxEEx",
   "xEEEEEEEExxEEEEEEEEx"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[9,22],"to":[9,22],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[8,21],"to":[8,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[9,21],"to":[9,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[10,21],"to":[10,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[11,21],"to":[11,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[7,22],"to":[7,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[10,22],"to":[10,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[12,22],"to":[12,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[10,23],"to":[10,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[12,23],"to":[12,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[8,24],"to":[8,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[9,24],"to":[9,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","name":"Panne","at":[10,24],"to":[10,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[11,24],"to":[11,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[10,9],"to":[10,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[8,9],"to":[8,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[7,9],"to":[7,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[7,8],"to":[7,8],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[12,8],"to":[12,8],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[7,6],"to":[7,6],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[12,6],"to":[12,6],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[7,5],"to":[7,5],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_シルエット","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["normal","hard","lunatic"],"name":"? ? ?","class":"Mirage","ai":{"start":"Everytime","mission":"Irregular","attack":"AttackToHeal","move":"Irregular"},"group":0},
  {"faction":"Enemy","pid":"PID_X022_インバース","team":"enemy","at":[12,5],"to":[12,5],"difficulties":["normal","hard","lunatic"],"name":"Aversa","class":"Dark Flier","items":["Bolganone","Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_インバース","move":"Person","moveParam":"PID_インバース"},"group":0},
  {"faction":"Enemy","pid":"PID_インバース","team":"ally","at":[15,24],"to":[15,24],"difficulties":["normal","hard","lunatic"],"name":"Aversa","class":"Dark Flier","items":["Bolganone","Nosferatu"],"ai":{"start":"Turn","startParam":"2","mission":"Null","attack":"Person","attackParam":"PID_X022_インバース","move":"Person","moveParam":"PID_X022_インバース"},"group":0},
 ],
} as const;
