/** A Man for Flowers: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X006, terrain X006). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_6 = {
 id: 'paralogue-6', rom: 'X006', terrainFile: 'X006', width: 32, height: 28,
 rows: [
   "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
   "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
   "1hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh",
   "1111hhhhhhhhhhhhhhhhhhhh11111311",
   "111111hhhhhhhhhhhhhhhh1111111111",
   "11111EEEEEEEEEEEEEEE111111131111",
   "11111EEEEEEEEEEEEEEE131111133333",
   "31311EExxxxxxxxxxxEE111111313333",
   "11111EExEEEEEEEEExEE111111133333",
   "11111EExExxxxxxxxxEE111111313333",
   "11111EExEEEEEEEEExEE111111333333",
   "11111EExxxxxxxxxExEE111111133333",
   "111113xxEGEEEEEEExx1111113113333",
   "111111xxExxxxxxxxxx1111111131131",
   "13111EExEEEEEEEEExEE111111113313",
   "11111EExxxxxxxxxExEE111111111111",
   "11111EExEEEEEEEEExEE111311111113",
   "11111EExxxxxxxxxxxEE111111111111",
   "11111EEEEEEEEEEEEEEE111111111111",
   "11111EEEEEEEEEEEEEEE111111311131",
   "11111hhhhhhhhh111111111111111111",
   "1111hhhhhhhhhhhhhh11111111111111",
   "hhhhhhhhhhhhhhhhhh11111111111111",
   "hhhhhhhhhhhhhhhhhhhhhhhh11111311",
   "hhhhhhhhhhhhhhhhhhhhhhhh11111111",
   "hhhhhhhhhhhhhhhhhhhhhhhh11111111",
   "hhhhhhhhhhhhhhhhhhhhhhhhhhh11111",
   "hhhhhhhhhhhhhhhhhhhhhhhhhhh11111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[26,10],"to":[26,10],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[24,8],"to":[24,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[26,8],"to":[26,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[25,9],"to":[25,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[27,9],"to":[27,9],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[23,10],"to":[23,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[29,10],"to":[29,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[24,11],"to":[24,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[25,11],"to":[25,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[27,11],"to":[27,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[28,11],"to":[28,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[26,12],"to":[26,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[27,12],"to":[27,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X006_ボス","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow","Master Seal"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[4,1],"to":[4,1],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[7,1],"to":[7,1],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[6,2],"to":[6,2],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[5,3],"to":[5,3],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[5,4],"to":[5,4],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[7,4],"to":[7,4],"difficulties":["hard","lunatic"],"class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[4,4],"to":[4,4],"difficulties":["lunatic"],"class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[6,22],"to":[6,22],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[8,23],"to":[8,23],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[7,24],"to":[7,24],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[6,25],"to":[6,25],"difficulties":["normal","hard","lunatic"],"class":"Dark Flier","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_グリフォンナイト","team":"enemy","at":[8,26],"to":[8,26],"difficulties":["normal","hard","lunatic"],"class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[9,24],"to":[9,24],"difficulties":["hard","lunatic"],"class":"Dark Flier","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ダークペガサス","team":"enemy","at":[5,24],"to":[5,24],"difficulties":["lunatic"],"class":"Dark Flier","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[10,7],"to":[10,7],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Bow","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[9,11],"to":[9,11],"difficulties":["normal"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[10,11],"to":[10,11],"difficulties":["normal"],"class":"Assassin","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[11,11],"to":[11,11],"difficulties":["normal"],"class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[13,11],"to":[13,11],"difficulties":["normal"],"class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[9,11],"to":[9,11],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[10,11],"to":[10,11],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Bow","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[11,11],"to":[11,11],"difficulties":["hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[13,11],"to":[13,11],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[10,13],"to":[10,13],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Silver Lance","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[11,13],"to":[11,13],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Bow","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[12,13],"to":[12,13],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[10,15],"to":[10,15],"difficulties":["normal"],"class":"Sorcerer","items":["Waste"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[11,15],"to":[11,15],"difficulties":["normal"],"class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[14,15],"to":[14,15],"difficulties":["normal"],"class":"Sorcerer","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[10,15],"to":[10,15],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Waste"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[11,15],"to":[11,15],"difficulties":["hard","lunatic"],"class":"General","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[14,15],"to":[14,15],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Arcfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[9,17],"to":[9,17],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[12,17],"to":[12,17],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Bow","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[14,17],"to":[14,17],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[14,9],"to":[14,9],"difficulties":["hard","lunatic"],"class":"General","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ソーサラー","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Arcwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[18,12],"to":[18,12],"difficulties":["lunatic"],"class":"General","items":["Spear"],"ai":{"start":"Turn","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_ジェネラル","team":"enemy","at":[18,13],"to":[18,13],"difficulties":["lunatic"],"class":"General","items":["Tomahawk"],"ai":{"start":"Turn","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[17,10],"to":[17,10],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Turn","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X006_アサシン","team":"enemy","at":[17,15],"to":[17,15],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Turn","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_アズール","team":"ally","at":[22,17],"to":[22,17],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Killing Edge","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Person","moveParam":"PID_X006_ボス"},"group":0},
 ],
} as const;
