/** Sickle to Sword: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X001, terrain X001). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_1 = {
 id: 'paralogue-1', rom: 'X001', terrainFile: 'X001', width: 20, height: 18,
 rows: [
   "11111111111111111111",
   "1xEEExxxExxxxxE11131",
   "1ExHExxxExxxxxE11311",
   "1ExxExzxxxxxxxE11111",
   "1EHxExxxExxxxxE11111",
   "1EEGExEEEEEEEEE11311",
   "1xxxExxExxxxxE113311",
   "1xxxExxExzxzxE113111",
   "1xxxxzxExxxxxE111111",
   "1x11xxxxxExExE311111",
   "1E111EEEEE1EEE311111",
   "11111111111111311131",
   "11E11z1111z11E133111",
   "11E13111E1111E133111",
   "11113113E1111E111311",
   "1331EEE333111E131111",
   "1331111133E111111111",
   "11111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[17,15],"to":[17,15],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[16,13],"to":[16,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[18,13],"to":[18,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[18,14],"to":[18,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[18,15],"to":[18,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[15,16],"to":[15,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[16,16],"to":[16,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[18,16],"to":[18,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X001_ボス","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["normal","hard","lunatic"],"name":"Roddick","class":"Barbarian","items":["Steel Axe","Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X001_盗賊","team":"enemy","at":[10,3],"to":[10,3],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Treasure","missionParam":"pos(3,2)","attack":"Null","move":"TrasureToEscape","moveParam":"pos(3,2),0,pos(3,16)"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[17,10],"to":[17,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_盗賊","team":"enemy","at":[18,8],"to":[18,8],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Thief","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[10,12],"to":[10,12],"difficulties":["normal"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[9,15],"to":[9,15],"difficulties":["normal"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[7,13],"to":[7,13],"difficulties":["normal"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[12,11],"to":[12,11],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[10,12],"to":[10,12],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe","Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[9,15],"to":[9,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe","Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[7,13],"to":[7,13],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_盗賊","team":"enemy","at":[4,16],"to":[4,16],"difficulties":["normal","hard"],"name":"Ruffian","class":"Thief","items":["Iron Sword","Chest Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["hard"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["normal","hard"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[1,11],"to":[1,11],"difficulties":["normal","hard"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_盗賊","team":"enemy","at":[4,16],"to":[4,16],"difficulties":["lunatic"],"name":"Ruffian","class":"Thief","items":["Iron Sword","Chest Key"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[1,11],"to":[1,11],"difficulties":["lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[9,7],"to":[9,7],"difficulties":["normal","hard"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe","Door Key"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[11,7],"to":[11,7],"difficulties":["normal","hard"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[9,7],"to":[9,7],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe","Hand Axe","Door Key"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[11,7],"to":[11,7],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe","Hammer"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[6,7],"to":[6,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[5,6],"to":[5,6],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow","Chest Key"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_蛮族","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X001_アーチャー","team":"enemy","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Support01","pid":"PID_ドニ","team":"player","name":"Donnel","at":[16,14],"to":[16,14],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
