/** A Shot from the Dark: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X015, terrain X015). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_15 = {
 id: 'paralogue-15', rom: 'X015', terrainFile: 'X015', width: 27, height: 32,
 rows: [
   "11111111ggg1111111111111111",
   "11111111ggg1111111331111111",
   "11311111ggg1111331313311111",
   "11313111gggg133313EEEEEE131",
   "111113111ggg113131ExxxxE111",
   "111111111gggg11331ExxxxE311",
   "1111313111eee11111ExxxxE111",
   "1131113111eee11111Exxxxx111",
   "1113111111ggg11EEEExxxxE111",
   "11111E1111ggggE111EEEEEE111",
   "11111E11111ggg1111111E11111",
   "111111E1111ggg1111131E11111",
   "111v11E1311ggg1133111E11311",
   "11ExxEEE131ggg1113111E11131",
   "11ExxxxE131gggg111111EE1111",
   "11Exxxxv1111ggg11113111E111",
   "11Exxxxv1111ggg11131111E111",
   "11Exxxxxv111gggg11111111111",
   "11Exxxxxv1131gggg1111111111",
   "11EEEEEE11111gggggg11111111",
   "111vvvE113311gggggggg111111",
   "11111vE111111ggggggggeeg111",
   "111111E111111ggg1ggggeegggg",
   "1111111vv1111ggg1111geegggg",
   "1113111111111ggg1111111gggg",
   "113113111111ggg111113111111",
   "113131311111ggg111111111111",
   "11111111111gggg113111113111",
   "11131311111eee1133111313111",
   "11113311111eee1111111111111",
   "11111311111ggg1111133111111",
   "1111111111gggg1111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[19,28],"to":[19,28],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[19,26],"to":[19,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[17,27],"to":[17,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[20,27],"to":[20,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[16,28],"to":[16,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[18,28],"to":[18,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[22,28],"to":[22,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[17,29],"to":[17,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[20,29],"to":[20,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[16,30],"to":[16,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[18,30],"to":[18,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[20,30],"to":[20,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[22,30],"to":[22,30],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X015_ボス","team":"enemy","at":[4,16],"to":[4,16],"difficulties":["normal","hard","lunatic"],"name":"Ezra","class":"Bow Knight","items":["Silver Bow","Silver Sword","Energy Drop"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[2,26],"to":[2,26],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[4,24],"to":[4,24],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[2,23],"to":[2,23],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword","Master Seal"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[5,23],"to":[5,23],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[11,22],"to":[11,22],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[9,21],"to":[9,21],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[9,23],"to":[9,23],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[12,15],"to":[12,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[11,15],"to":[11,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[13,13],"to":[13,13],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[18,15],"to":[18,15],"difficulties":["normal","hard"],"name":"Ruffian","class":"Paladin","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["normal","hard"],"name":"Ruffian","class":"Paladin","items":["Spear"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[19,13],"to":[19,13],"difficulties":["normal","hard"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[20,14],"to":[20,14],"difficulties":["hard"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[18,15],"to":[18,15],"difficulties":["lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Lance"],"ai":{"start":"TurnBandRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["lunatic"],"name":"Ruffian","class":"Paladin","items":["Spear"],"ai":{"start":"TurnBandRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[19,13],"to":[19,13],"difficulties":["lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"TurnBandRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[20,14],"to":[20,14],"difficulties":["lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"TurnBandRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[16,13],"to":[16,13],"difficulties":["lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"TurnBandRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":1},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["normal"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[13,4],"to":[13,4],"difficulties":["normal"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,4],"to":[17,4],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[17,6],"to":[17,6],"difficulties":["normal"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"6","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["hard"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["hard"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[13,4],"to":[13,4],"difficulties":["hard"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,4],"to":[17,4],"difficulties":["hard"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["hard"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["hard"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[17,6],"to":[17,6],"difficulties":["hard"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["hard"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[13,4],"to":[13,4],"difficulties":["lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,4],"to":[17,4],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[17,6],"to":[17,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_パラディン","team":"enemy","at":[4,2],"to":[4,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_ボウナイト","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["lunatic"],"name":"Ruffian","class":"Bow Knight","items":["Silver Bow","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_ノワール","move":"Person","moveParam":"PID_ノワール"},"group":0},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[5,15],"to":[5,15],"difficulties":["normal"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[6,16],"to":[6,16],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[3,17],"to":[3,17],"difficulties":["normal"],"name":"Ruffian","class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[6,18],"to":[6,18],"difficulties":["normal"],"name":"Ruffian","class":"Falcon Knight","items":["Spear"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[5,15],"to":[5,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[6,16],"to":[6,16],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_グリフォンナイト","team":"enemy","at":[3,17],"to":[3,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Griffon Rider","items":["Tomahawk"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[6,18],"to":[6,18],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Spear"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Spear"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X015_ファルコンナイト","team":"enemy","at":[4,14],"to":[4,14],"difficulties":["lunatic"],"name":"Ruffian","class":"Falcon Knight","items":["Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_ノワール","team":"ally","at":[20,7],"to":[20,7],"difficulties":["normal","hard","lunatic"],"name":"Noire","class":"Archer","ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
