/** A Duel Disgraced: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X008, terrain X008). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_8 = {
 id: 'paralogue-8', rom: 'X008', terrainFile: 'X008', width: 22, height: 24,
 rows: [
   "EEEEEEEEEEEEEEEEEEEEEE",
   "ExxxxxxxxxxxxxxxxxxxxE",
   "ExyxxxzxxxxxxxxzxxxyxE",
   "ExxxxxxxxxxxxxxxxxxxxE",
   "EEEEExzxxxxxxxxzxEEEEE",
   "EHxxExxxxxxxxxxxxExxxE",
   "ExyxEEEEEEGGEEEEEExyxE",
   "ExxxxxxxxxxxxxxxxxxxxE",
   "EEEExxEEEExxEEEExxEEEE",
   "ExxxxxxxxExxExxxxxxxHE",
   "ExyxxxxxxExxExxxxxxyxE",
   "ExxxxxEEEExxEEEExxxxxE",
   "EEEEExxxxxxxxxxxxEEEEE",
   "ExxxEEEEExxxxEEEEExxxE",
   "ExyxxxxxxzxxzxxxxxxyxE",
   "ExxxxxxxxxxxxxxxxxxxxE",
   "EEEEEEExxzxxzxxEEEEEEE",
   "ExxxxxEEExxxxEEExxxxxE",
   "ExyxxxxxxxxxxxxxxxxyxE",
   "ExxxxxEEExxxxEEExxxxxE",
   "EEEEEEEXXXXXXXXEEEEEEE",
   "XXXXXXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXXXXXXXXXXXXXX"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[11,21],"to":[11,21],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,20],"to":[9,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[10,20],"to":[10,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[11,20],"to":[11,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[12,20],"to":[12,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[13,20],"to":[13,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[9,21],"to":[9,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[13,21],"to":[13,21],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[8,22],"to":[8,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[10,22],"to":[10,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[11,22],"to":[11,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[12,22],"to":[12,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[14,22],"to":[14,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X008_ボス","team":"enemy","at":[1,1],"to":[1,1],"difficulties":["normal","hard","lunatic"],"name":"Cassius","class":"Sorcerer","items":["Waste","Dracoshield"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_デジェル","move":"Person","moveParam":"PID_デジェル"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_デジェル","move":"Person","moveParam":"PID_デジェル"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[5,18],"to":[5,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[4,17],"to":[4,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[16,18],"to":[16,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[17,17],"to":[17,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_傭兵","team":"enemy","at":[8,15],"to":[8,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_傭兵","team":"enemy","at":[13,15],"to":[13,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[6,14],"to":[6,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[15,14],"to":[15,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[9,13],"to":[9,13],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[12,13],"to":[12,13],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_傭兵","team":"enemy","at":[10,12],"to":[10,12],"difficulties":["lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[11,12],"to":[11,12],"difficulties":["lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[5,12],"to":[5,12],"difficulties":["normal"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["normal"],"name":"Ruffian","class":"Dark Mage","items":["Ruin"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[16,12],"to":[16,12],"difficulties":["normal"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[17,9],"to":[17,9],"difficulties":["normal"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_ジェネラル","team":"enemy","at":[6,7],"to":[6,7],"difficulties":["normal"],"name":"Ruffian","class":"General","items":["Short Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal"],"name":"Ruffian","class":"Dark Mage","items":["Elthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["normal"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X008_傭兵","team":"enemy","at":[14,7],"to":[14,7],"difficulties":["normal"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["normal"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X008_ソーサラー","team":"enemy","at":[18,7],"to":[18,7],"difficulties":["normal"],"name":"Ruffian","class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[5,12],"to":[5,12],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Ruin"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[3,10],"to":[3,10],"difficulties":["lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[16,12],"to":[16,12],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[17,9],"to":[17,9],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[18,10],"to":[18,10],"difficulties":["lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Ruin"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_ジェネラル","team":"enemy","at":[6,7],"to":[6,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"General","items":["Short Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_ダークマージ","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Elthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_アーチャー","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X008_傭兵","team":"enemy","at":[14,7],"to":[14,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_アーマーナイト","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X008_ソーサラー","team":"enemy","at":[18,7],"to":[18,7],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_デジェル","team":"ally","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"name":"Kjelle","class":"Knight","items":["Steel Lance","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X008_アーチャー","move":"Person","moveParam":"PID_X008_アーチャー"},"group":0},
  {"faction":"Reinforce01","pid":"PID_X008_アーチャー","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_デジェル","move":"Person","moveParam":"PID_デジェル"},"group":0},
  {"faction":"Reinforce02","pid":"PID_X008_アーチャー","team":"enemy","at":[19,2],"to":[19,2],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_デジェル","move":"Person","moveParam":"PID_デジェル"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X008_傭兵","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_X008_アーマーナイト","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_X008_アーマーナイト","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_X008_アーチャー","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_X008_ダークマージ","team":"enemy","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce08","pid":"PID_X008_傭兵","team":"enemy","at":[19,18],"to":[19,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce09","pid":"PID_X008_アーマーナイト","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce10","pid":"PID_X008_ダークマージ","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce11","pid":"PID_X008_傭兵","team":"enemy","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce12","pid":"PID_X008_アーチャー","team":"enemy","at":[19,18],"to":[19,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce13","pid":"PID_X008_アーチャー","team":"enemy","at":[2,14],"to":[2,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce14","pid":"PID_X008_ジェネラル","team":"enemy","at":[19,14],"to":[19,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce15","pid":"PID_X008_ソーサラー","team":"enemy","at":[2,18],"to":[2,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sorcerer","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce16","pid":"PID_X008_傭兵","team":"enemy","at":[19,18],"to":[19,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce17","pid":"PID_X008_アーチャー","team":"enemy","at":[2,14],"to":[2,14],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce18","pid":"PID_X008_ダークマージ","team":"enemy","at":[19,14],"to":[19,14],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Dark Mage","items":["Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce19","pid":"PID_X008_ソーサラー","team":"enemy","at":[2,6],"to":[2,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Sorcerer","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce20","pid":"PID_X008_ジェネラル","team":"enemy","at":[19,6],"to":[19,6],"difficulties":["lunatic"],"name":"Ruffian","class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce21","pid":"PID_X008_ジェネラル","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce22","pid":"PID_X008_ソーサラー","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sorcerer","items":["Waste"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce23","pid":"PID_X008_アーチャー","team":"enemy","at":[2,6],"to":[2,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Archer","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Reinforce24","pid":"PID_X008_アーマーナイト","team":"enemy","at":[19,6],"to":[19,6],"difficulties":["lunatic"],"name":"Ruffian","class":"Knight","items":["Short Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
 ],
} as const;
