/** Twin Wyverns: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X011, terrain X011). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_11 = {
 id: 'paralogue-11', rom: 'X011', terrainFile: 'X011', width: 32, height: 29,
 rows: [
   "11119999999991111199999999999111",
   "11111999999911111199999999911311",
   "11j11ee9eeee1j113119999999111111",
   "1j131eeee9ee11111j1eee9eee1j1111",
   "1111199999999131111ee9eeee1131j1",
   "91119999999999111999999999911111",
   "99ee9999999999ee9999999999999ee9",
   "99ee9999999999ee99999999999999e9",
   "99ee9999999999ee9999999999999ee9",
   "99ee9999999999e99999999999999ee9",
   "99ee9999999999ee9999999999999ee9",
   "99ee1199999991111199999999999111",
   "911111eee9ee11113119999999991311",
   "111311ee9eee11131111eeeeeee11111",
   "13111199999991111111eeeeeee11131",
   "11111999999999911199999999911111",
   "1ee9999999999999ee9999999999ee11",
   "9ee9999999999999ee9999999999ee99",
   "99e9999999999999ee9999999999ee99",
   "99e9999999999999ee9999999999e999",
   "9ee9999999999999ee9999999999ee99",
   "9ee9999999999999ee9999999999ee99",
   "9ee99999999991111111999999911199",
   "91119999999111111311199999111319",
   "11111999991111311111199999131119",
   "11131eeeee1111111111199999111119",
   "11111eeeee1311111131199999111311",
   "13111999991111131111999999911111",
   "11119999999111111111999999911111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[15,25],"to":[15,25],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[13,23],"to":[13,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[14,23],"to":[14,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[16,23],"to":[16,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[15,24],"to":[15,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[16,24],"to":[16,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[13,25],"to":[13,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[17,25],"to":[17,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[14,26],"to":[14,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[17,26],"to":[17,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[13,27],"to":[13,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[15,27],"to":[15,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[16,27],"to":[16,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X011_ボス","team":"enemy","at":[29,1],"to":[29,1],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk","Bullion (M)"],"ai":{"start":"TurnAttackRange","startParam":"5","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[8,10],"to":[8,10],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[9,9],"to":[9,9],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[10,9],"to":[10,9],"difficulties":["hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[21,9],"to":[21,9],"difficulties":["hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[22,9],"to":[22,9],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[23,10],"to":[23,10],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[14,13],"to":[14,13],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[15,12],"to":[15,12],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[16,13],"to":[16,13],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[17,12],"to":[17,12],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[18,13],"to":[18,13],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[29,12],"to":[29,12],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[30,13],"to":[30,13],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[30,11],"to":[30,11],"difficulties":["lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[2,4],"to":[2,4],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":1},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[2,5],"to":[2,5],"difficulties":["hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":1},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[3,3],"to":[3,3],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":1},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[6,2],"to":[6,2],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[7,1],"to":[7,1],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[8,2],"to":[8,2],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[13,4],"to":[13,4],"difficulties":["lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":3},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[14,3],"to":[14,3],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":3},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[15,4],"to":[15,4],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":3},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[16,2],"to":[16,2],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":3},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[21,2],"to":[21,2],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[20,1],"to":[20,1],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[22,1],"to":[22,1],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[23,2],"to":[23,2],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[24,1],"to":[24,1],"difficulties":["lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X011_バーサーカー","team":"enemy","at":[27,5],"to":[27,5],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":5},
  {"faction":"Enemy","pid":"PID_X011_スナイパー","team":"enemy","at":[28,4],"to":[28,4],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":5},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[29,5],"to":[29,5],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":5},
  {"faction":"Enemy","pid":"PID_X011_ソードマスター","team":"enemy","at":[30,5],"to":[30,5],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"4","mission":"Null","attack":"Person","attackParam":"PID_X011_村人","move":"Person","moveParam":"PID_X011_村人"},"group":5},
  {"faction":"Enemy","pid":"PID_ジェローム","team":"ally","at":[19,26],"to":[19,26],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe","Concoction"],"ai":{"start":"Null","mission":"Null","attack":"Null","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X011_村人","team":"ally","at":[3,27],"to":[3,27],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X011_村人","team":"ally","at":[12,26],"to":[12,26],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X011_村人","team":"ally","at":[18,24],"to":[18,24],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X011_村人","team":"ally","at":[27,26],"to":[27,26],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X011_村人","team":"ally","at":[30,24],"to":[30,24],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true},
  {"faction":"Reinforce01","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[1,3],"to":[1,3],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[13,2],"to":[13,2],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[17,3],"to":[17,3],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[27,3],"to":[27,3],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X011_ドラゴンマスター","team":"enemy","at":[30,4],"to":[30,4],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
