/** Noble Lineage: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X007, terrain X007). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_7 = {
 id: 'paralogue-7', rom: 'X007', terrainFile: 'X007', width: 24, height: 24,
 rows: [
   "111111111111111111111111",
   "11111111111111iii1111331",
   "1111113111111iiiii113331",
   "111v111331111iiiii113311",
   "11ivi11331111iiiiv111111",
   "11iiii1111111iiiii131111",
   "1131ii11111111iii1111111",
   "11111111EEEEEE1111111111",
   "11111111EEEEEEEE11v11111",
   "1vv11111EEEEEEEE11111111",
   "11111111xxxxxxxE1111ii11",
   "11111311xxExxzxE11113ii1",
   "11113311Exxxxxxx11113ii1",
   "11111111ExxzxExx11111ii1",
   "11111111ExxxxxxE11111111",
   "1111v111EEExxExE111v1111",
   "11111111EEExxExE11v11111",
   "111311111111111111111311",
   "111111iiii111111vvv11111",
   "1111vvvvii1111111111iii1",
   "1111vvvvi1113311111ivii1",
   "113111iii1311111111ivi11",
   "1131111111111111111iii11",
   "111111111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[12,13],"to":[12,13],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,10],"to":[9,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[13,10],"to":[13,10],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[8,11],"to":[8,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[11,11],"to":[11,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[14,11],"to":[14,11],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[10,12],"to":[10,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[15,12],"to":[15,12],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[14,13],"to":[14,13],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[12,14],"to":[12,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[11,15],"to":[11,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[14,15],"to":[14,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X007_ボス","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk","Master Seal"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[3,6],"to":[3,6],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[5,15],"to":[5,15],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[2,16],"to":[2,16],"difficulties":["lunatic"],"class":"Paladin","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[4,17],"to":[4,17],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[8,22],"to":[8,22],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[9,20],"to":[9,20],"difficulties":["lunatic"],"class":"Hero","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[10,21],"to":[10,21],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[12,22],"to":[12,22],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[14,21],"to":[14,21],"difficulties":["hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[15,22],"to":[15,22],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[18,21],"to":[18,21],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[20,16],"to":[20,16],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[22,15],"to":[22,15],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[20,12],"to":[20,12],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[19,13],"to":[19,13],"difficulties":["hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[22,10],"to":[22,10],"difficulties":["lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[19,9],"to":[19,9],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[21,8],"to":[21,8],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[4,3],"to":[4,3],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[5,2],"to":[5,2],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[3,20],"to":[3,20],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_パラディン","team":"enemy","at":[1,21],"to":[1,21],"difficulties":["normal","hard","lunatic"],"class":"Paladin","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[2,22],"to":[2,22],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_勇者","team":"enemy","at":[19,3],"to":[19,3],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[21,4],"to":[21,4],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[22,2],"to":[22,2],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[10,3],"to":[10,3],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X007_ソードマスター","team":"enemy","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X007_スナイパー","team":"enemy","at":[13,1],"to":[13,1],"difficulties":["normal","hard","lunatic"],"class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X007_村人","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_ブレディ","team":"ally","at":[11,12],"to":[11,12],"difficulties":["normal","hard","lunatic"],"class":"Priest","items":["Mend","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X007_村人","team":"ally","at":[12,10],"to":[12,10],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X007_村人","team":"ally","at":[9,11],"to":[9,11],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X007_村人","team":"ally","at":[14,12],"to":[14,12],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X007_村人","team":"ally","at":[10,14],"to":[10,14],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X007_村人","team":"ally","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
 ],
} as const;
