/** The Radiant Hero: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X023, terrain X023). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_23 = {
 id: 'paralogue-23', rom: 'X023', terrainFile: 'X023', width: 32, height: 32,
 rows: [
   "13111111111133166666666666666666",
   "11111113111331111116666666666666",
   "31331111113113111111116666666666",
   "31131111111111113311113111666666",
   "11311111113111113111131311111166",
   "11111311111111111113111111111111",
   "11113113111111111133133111313311",
   "11111111111111111111311131133111",
   "11111111111111111111311111111313",
   "11311111111111113111111333131133",
   "11111131311111111111111131111131",
   "i1111111111131111131111111113331",
   "iiii11111111BBBB1111131111111111",
   "iiiii111111xxx11BBB1111111311311",
   "iiiiii11111xxxxxx1B1111131111111",
   "iiiiii11B11xxxxxxxB1311111111111",
   "iiiii111Bx3xxxxxx1B1131111111131",
   "iiii1111Bxxxxxxxx1B111111v111111",
   "11111111Bxxxxxxx11B1111vvv111111",
   "11111111Bxx1xxxx111111111vv11111",
   "11111111BB1BBBB11113111111111111",
   "11111311111111111111133111111111",
   "11111111111111113111111311111111",
   "11311131111111131111113111111111",
   "11111111111111111111111113111111",
   "11113111111111111111111111111111",
   "11311111331111111111111111111111",
   "11331311111111111111111111118888",
   "1111133111131111111111111188hhhh",
   "11113111311111311311111888hhhhhh",
   "13313133331111113118888hhhhhhhhh",
   "3311111111111111118hhhhhhhhhhhhh"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[16,26],"to":[16,26],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[13,24],"to":[13,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[15,24],"to":[15,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[17,24],"to":[17,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[19,24],"to":[19,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[13,25],"to":[13,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[14,25],"to":[14,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[15,25],"to":[15,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[16,25],"to":[16,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[17,25],"to":[17,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[18,25],"to":[18,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[19,25],"to":[19,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[13,26],"to":[13,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","name":"Panne","at":[14,26],"to":[14,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[15,26],"to":[15,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_グレゴ","team":"player","name":"Gregor","at":[17,26],"to":[17,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ノノ","team":"player","name":"Nowi","at":[18,26],"to":[18,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_サーリャ","team":"player","name":"Tharja","at":[19,26],"to":[19,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リベラ","team":"player","name":"Libra","at":[13,27],"to":[13,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_オリヴィエ","team":"player","name":"Olivia","at":[14,27],"to":[14,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_セルジュ","team":"player","name":"Cherche","at":[15,27],"to":[15,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヘンリー","team":"player","name":"Henry","at":[16,27],"to":[16,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_サイリ","team":"player","name":"Say'ri","at":[17,27],"to":[17,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_バジーリオ","team":"player","name":"Basilio","at":[18,27],"to":[18,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フラヴィア","team":"player","name":"Flavia","at":[19,27],"to":[19,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ドニ","team":"player","name":"Donnel","at":[13,28],"to":[13,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_アンナ","team":"player","name":"Anna","at":[14,28],"to":[14,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_チキ","team":"player","name":"Tiki","at":[16,28],"to":[16,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ギャンレル","team":"player","name":"Gangrel","at":[18,28],"to":[18,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴァルハルト","team":"player","name":"Walhart","at":[19,28],"to":[19,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X023_ボス","team":"enemy","at":[16,4],"to":[16,4],"difficulties":["normal","hard","lunatic"],"name":"Priam","class":"Hero","items":["IID_ラグネル（敵）","Secret Book","Goddess Icon"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[4,11],"to":[4,11],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[6,11],"to":[6,11],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[8,11],"to":[8,11],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[5,10],"to":[5,10],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Silver Lance","Hammer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[7,10],"to":[7,10],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[6,9],"to":[6,9],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[8,9],"to":[8,9],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[6,8],"to":[6,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[7,7],"to":[7,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[9,8],"to":[9,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[10,7],"to":[10,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[6,6],"to":[6,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Bolganone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[22,11],"to":[22,11],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[28,11],"to":[28,11],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[23,10],"to":[23,10],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[25,10],"to":[25,10],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[27,10],"to":[27,10],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[24,9],"to":[24,9],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[26,9],"to":[26,9],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[24,8],"to":[24,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[26,8],"to":[26,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[25,7],"to":[25,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[23,8],"to":[23,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[27,8],"to":[27,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[22,7],"to":[22,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[28,7],"to":[28,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword","Wyrmslayer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[23,7],"to":[23,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Thoron"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[27,7],"to":[27,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Thoron"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[22,6],"to":[22,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Bolganone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[28,6],"to":[28,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Rexcalibur"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Silver Axe","Beast Killer"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ジェネラル","team":"enemy","at":[19,7],"to":[19,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"General","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ウォーリアー","team":"enemy","at":[18,6],"to":[18,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[15,5],"to":[15,5],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_ソードマスター","team":"enemy","at":[17,5],"to":[17,5],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_勇者","team":"enemy","at":[19,5],"to":[19,5],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Hero","items":["Silver Axe","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_スナイパー","team":"enemy","at":[18,4],"to":[18,4],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Thoron"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[15,3],"to":[15,3],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Rexcalibur"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[17,3],"to":[17,3],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Rexcalibur"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X023_賢者","team":"enemy","at":[20,3],"to":[20,3],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Sage","items":["Bolganone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Support01","pid":"PID_パリス","team":"player","name":"Priam","at":[0,0],"to":[0,0],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
