/** The Secret Seller: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X002, terrain X002). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_2 = {
 id: 'paralogue-2', rom: 'X002', terrainFile: 'X002', width: 24, height: 24,
 rows: [
   "XXXXXXXXXXXXXXXXXXXXXXXX",
   "XhhhhhhhhhhhhhhhXsssXhhX",
   "XhhhhhhhhhhhhhhXXsss1XgX",
   "XhhXXhXXXXhhhh1XXX$XXggX",
   "XXXXXXXXXX1XgXX3XXXXXg11",
   "XXXXX33XXXXggXXXXX33XgXX",
   "XXXX3333XXggXX33X333XgXX",
   "XXX33333XggXX333333XXeXX",
   "XXX33333ggX3X311XXXXggXX",
   "XXXX3333gX3XXX1X33XXgXXX",
   "X33XX33XgXX33XXXX3XggXXX",
   "X33XXXXXgXXXXXXXXXgg11XX",
   "XXXXXXXXggXXXXX3Xggg1geX",
   "XXX33XXX1eXXX3XXggXgggXX",
   "XX333XXXXg1XXXXggXXgXX6X",
   "XX3333XXgg11XXgggXgg666X",
   "X333333ggXX1XggXgggX666X",
   "X333333gXXXXggXXe166666X",
   "X333333ggegggX3XgX66666X",
   "X33333ggXXXXXX3Xg666666X",
   "X333gggXXXXX11Xgg666666X",
   "X33ggXXXXXXXXXXg3666666X",
   "XgggXXXXX3XXXXXg6666666X",
   "XXXXXXXXXXXXXXXg6666666X"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[3,15],"to":[3,15],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[2,14],"to":[2,14],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[1,15],"to":[1,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[4,15],"to":[4,15],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[2,16],"to":[2,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[5,16],"to":[5,16],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[1,17],"to":[1,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[3,17],"to":[3,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[4,17],"to":[4,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[6,17],"to":[6,17],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X002_ボス","team":"enemy","at":[14,21],"to":[14,21],"difficulties":["normal","hard","lunatic"],"name":"Victor","class":"Berserker","items":["Short Axe","Goddess Icon"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[13,20],"to":[13,20],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[12,21],"to":[12,21],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X002_アーチャー","team":"enemy","at":[13,22],"to":[13,22],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[12,9],"to":[12,9],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[16,11],"to":[16,11],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[22,15],"to":[22,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[9,18],"to":[9,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[10,17],"to":[10,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[18,19],"to":[18,19],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[21,16],"to":[21,16],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Village","missionParam":"pos(18,3)","attack":"Null","move":"VillageNoThroughToAttack","moveParam":"pos(18,3)"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_アーチャー","team":"enemy","at":[13,5],"to":[13,5],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X002_アンナ","move":"Person","moveParam":"PID_X002_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_アーチャー","team":"enemy","at":[20,11],"to":[20,11],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X002_アンナ","move":"Person","moveParam":"PID_X002_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_魔道士","team":"enemy","at":[12,15],"to":[12,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X002_アンナ","move":"Person","moveParam":"PID_X002_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_魔道士","team":"enemy","at":[7,21],"to":[7,21],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Mage","items":["Thunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X002_アンナ","move":"Person","moveParam":"PID_X002_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[8,13],"to":[8,13],"difficulties":["normal"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[8,13],"to":[8,13],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[9,13],"to":[9,13],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[6,9],"to":[6,9],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_蛮族","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["lunatic"],"name":"Ruffian","class":"Barbarian","items":["Iron Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_アーチャー","team":"enemy","at":[7,6],"to":[7,6],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_アーチャー","team":"enemy","at":[5,5],"to":[5,5],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Archer","items":["Iron Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_魔道士","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["lunatic"],"name":"Ruffian","class":"Mage","items":["Elwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X002_アンナ","team":"ally","at":[17,4],"to":[17,4],"difficulties":["normal","hard","lunatic"],"name":"Anna","class":"Trickster","items":["Steel Sword","Killing Edge","Heal","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"X002Anna","attackParam":"JID_蛮族男,pos(18,3)","move":"Null"},"group":0},
  {"faction":"Event01","pid":"PID_X002_ボスEV","team":"enemy","at":[11,23],"to":[13,21],"difficulties":["normal","hard","lunatic"],"name":"Vincent","class":"Berserker","ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
 ],
} as const;
