/** Anna the Merchant: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X004, terrain X004). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_4 = {
 id: 'paralogue-4', rom: 'X004', terrainFile: 'X004', width: 18, height: 22,
 rows: [
   "111111111111111111",
   "131EEEEEE1331EEEE1",
   "131ExxHxE1111xxHE1",
   "131ExxxxE111EHxxE1",
   "111ExxxxE111Exxx11",
   "111EE11EE111EEGE11",
   "111111111111111111",
   "1111111EEEE1133111",
   "1EEEE11Exxx1133311",
   "1ExHxE1ExxxE113311",
   "11xxxE1EEGEEEE11E1",
   "11EGEE111111ExxxE1",
   "111111331111ExxxE1",
   "111111331331EEGEE1",
   "1111EEEEE111111111",
   "1111ExxxE111EEE111",
   "1311ExxxE1Exxx1111",
   "13311E11E1ExxxE111",
   "1131111111EEGEE111",
   "111111111111111111",
   "111111133311111111",
   "111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[9,20],"to":[9,20],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[1,20],"to":[1,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[2,19],"to":[2,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[4,20],"to":[4,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[6,19],"to":[6,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[6,20],"to":[6,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[8,19],"to":[8,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[11,20],"to":[11,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[12,19],"to":[12,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[14,20],"to":[14,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[15,20],"to":[15,20],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[16,19],"to":[16,19],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X004_ボス","team":"enemy","at":[10,1],"to":[10,1],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Short Axe","Talisman"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_X004_盗賊","team":"enemy","at":[1,1],"to":[1,1],"difficulties":["normal","hard","lunatic"],"class":"Thief","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Treasure","missionParam":"pos(13,3)","attack":"Null","move":"TrasureToEscape","moveParam":"pos(13,3),0,pos(16,4)"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[4,13],"to":[4,13],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_アンナ","move":"Person","moveParam":"PID_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[9,11],"to":[9,11],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_アンナ","move":"Person","moveParam":"PID_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[6,10],"to":[6,10],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_アンナ","move":"Person","moveParam":"PID_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_アンナ","move":"Person","moveParam":"PID_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[10,14],"to":[10,14],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_アンナ","move":"Person","moveParam":"PID_アンナ"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[2,16],"to":[2,16],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[1,17],"to":[1,17],"difficulties":["lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["hard","lunatic"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[5,15],"to":[5,15],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[6,16],"to":[6,16],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[7,15],"to":[7,15],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[9,17],"to":[9,17],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["normal"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["hard","lunatic"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[13,17],"to":[13,17],"difficulties":["hard","lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[15,16],"to":[15,16],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[16,17],"to":[16,17],"difficulties":["lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[16,14],"to":[16,14],"difficulties":["hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[14,11],"to":[14,11],"difficulties":["normal","hard","lunatic"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[9,8],"to":[9,8],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_アーチャー","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[12,8],"to":[12,8],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[15,9],"to":[15,9],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[14,7],"to":[14,7],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elthunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[6,4],"to":[6,4],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[4,3],"to":[4,3],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[10,3],"to":[10,3],"difficulties":["hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X004_蛮族","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X004_剣士","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["lunatic"],"class":"Mage","items":["Elfire"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X004_魔道士","team":"enemy","at":[13,4],"to":[13,4],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Elwind"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_アンナ","team":"ally","at":[7,12],"to":[7,12],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Steel Sword","Heal","Concoction"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
 ],
} as const;
