/** A Hard Miracle: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X020, terrain X020). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_20 = {
 id: 'paralogue-20', rom: 'X020', terrainFile: 'X020', width: 28, height: 28,
 rows: [
   "7777777777777777777711117777",
   "7777777777777777777111117777",
   "1777777777777777771111117777",
   "1177777777777771111111117777",
   "1117777777777711111111111777",
   "11117777777771111111j1111777",
   "1111177777111111311111111777",
   "11111177731111111311111j1777",
   "11311111113111111111j1111177",
   "1111111111177771111111111177",
   "1111111111777777711111111177",
   "1111131117777777711111113117",
   "11j1111117777777771111111111",
   "1111111117777777777711111111",
   "1111111117777777777771131111",
   "1131111177777777777777111111",
   "1111111777777777777771111131",
   "1111117777777777771111111111",
   "1111777777777777711111111111",
   "11177777777777111111111j1111",
   "1117777771111111111111111111",
   "1111771111111111131111111777",
   "1111111111131111111111777777",
   "11sss11111111111111177777777",
   "11sss11111111311177777777777",
   "111m111111111111777777777777",
   "1111111111111177777777777777",
   "1111111111117777777777777777"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[10,24],"to":[10,24],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,22],"to":[9,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[11,22],"to":[11,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[13,22],"to":[13,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[8,23],"to":[8,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[10,23],"to":[10,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[12,23],"to":[12,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[14,23],"to":[14,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[7,24],"to":[7,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[12,24],"to":[12,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[8,25],"to":[8,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[9,25],"to":[9,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","name":"Panne","at":[11,25],"to":[11,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[13,25],"to":[13,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X020_ボス","team":"enemy","at":[20,5],"to":[20,5],"difficulties":["normal","hard","lunatic"],"name":"Ardri","class":"Sorcerer","items":["Waste","Mire","Talisman"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[6,16],"to":[6,16],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Ruin","Mire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[20,13],"to":[20,13],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Ruin","Mire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[5,11],"to":[5,11],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[2,12],"to":[2,12],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[23,8],"to":[23,8],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[18,9],"to":[18,9],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[21,10],"to":[21,10],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[4,12],"to":[4,12],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Waste"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[5,14],"to":[5,14],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[21,8],"to":[21,8],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ソーサラー","team":"enemy","at":[24,7],"to":[24,7],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Sorcerer","items":["Waste"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[1,7],"to":[1,7],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[2,6],"to":[2,6],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Thoron","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[3,7],"to":[3,7],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[20,2],"to":[20,2],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Rexcalibur","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[21,1],"to":[21,1],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Thoron","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[22,2],"to":[22,2],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[5,4],"to":[5,4],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[12,15],"to":[12,15],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[14,15],"to":[14,15],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance","Bullion (M)"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[12,13],"to":[12,13],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[14,13],"to":[14,13],"difficulties":["normal","hard","lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[11,7],"to":[11,7],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[12,8],"to":[12,8],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Knight","items":["Rexcalibur","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Knight","items":["Thoron","Silver Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[11,7],"to":[11,7],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[12,8],"to":[12,8],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Rexcalibur","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[13,7],"to":[13,7],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Thoron","Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[17,2],"to":[17,2],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[18,1],"to":[18,1],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[24,1],"to":[24,1],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[25,2],"to":[25,2],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[26,1],"to":[26,1],"difficulties":["normal","hard"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[17,2],"to":[17,2],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[18,1],"to":[18,1],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[24,1],"to":[24,1],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Bolganone","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[25,2],"to":[25,2],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Rexcalibur","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークペガサス","team":"enemy","at":[26,1],"to":[26,1],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Flier","items":["Thoron","Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[18,6],"to":[18,6],"difficulties":["hard","lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[17,5],"to":[17,5],"difficulties":["lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_アサシン","team":"enemy","at":[16,6],"to":[16,6],"difficulties":["lunatic"],"name":"Grimleal","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[22,6],"to":[22,6],"difficulties":["hard","lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[23,5],"to":[23,5],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Rexcalibur","Silver Sword"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X020_ダークナイト","team":"enemy","at":[24,6],"to":[24,6],"difficulties":["lunatic"],"name":"Grimleal","class":"Dark Knight","items":["Bolganone","Silver Sword"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_エメリナ","team":"ally","at":[26,18],"to":[26,18],"difficulties":["normal","hard","lunatic"],"name":"Emmeryn","class":"Sage","ai":{"start":"Everytime","mission":"Null","attack":"Null","move":"Null"},"group":0,"stationary":true},
 ],
} as const;
