/** Ambivalence: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X010, terrain X010). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_10 = {
 id: 'paralogue-10', rom: 'X010', terrainFile: 'X010', width: 26, height: 27,
 rows: [
   "22222222222222222222222222",
   "222EEEEEEEEEEEEEEEEEEEE222",
   "22EExxxxxExxxxxxEHxxxxEE22",
   "2EExxyxyxExyxxyxExyxyxxEE2",
   "2ExxxxxxxExxxxxxExxxxxxxE2",
   "2ExxxxxxxExxxxxxExxxxxxxE2",
   "2ExxxEEEEExyxxyxEEGEExxxE2",
   "2ExxxExxxxxxxxxxxxxxExxxE2",
   "2ExxxExxzzxxzzxxzzxxExxxE2",
   "2ExxxExxxxxxxxxxxxxxExxxE2",
   "2ExzxExxExxExxExxExxExzxE2",
   "2ExxxExxExxExxExxExxExxxE2",
   "2ExxxExxExxExxExxExxxxxxE2",
   "2ExzxxxxxxxExxExxExxxxzxE2",
   "2ExxxxxxxxHExxExxExxxxxxE2",
   "2ExxxEEEEEEExxExxEEEEEEEE2",
   "2ExxxxxxxxxxxxExxxxxxxxxE2",
   "2ExxxxxxxxxxxxExxxxxxxxxE2",
   "2EEEEEEEEEEExxEEEEEEEExxE2",
   "2ExxxxxxxxxxxxExxxxxxxxxE2",
   "2EExxxxxxzxxxxExzxxxxxxEE2",
   "22EExxxxxxxxxxExxxxxxxEE22",
   "222EEExxxxEEEEEExxxxEEE222",
   "22222222222222222222222222",
   "22222222222222222222222222",
   "22222222222222222222222222",
   "22222222222222222222222222"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[7,24],"to":[7,24],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[5,23],"to":[5,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[9,23],"to":[9,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[10,23],"to":[10,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[4,24],"to":[4,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[6,24],"to":[6,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[9,24],"to":[9,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[11,24],"to":[11,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[5,25],"to":[5,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[7,25],"to":[7,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[8,25],"to":[8,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[10,25],"to":[10,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X010_ボス","team":"enemy","at":[6,3],"to":[6,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Thoron","Talisman"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"Null"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X010_ホラント","team":"enemy","at":[21,4],"to":[21,4],"difficulties":["normal","hard","lunatic"],"class":"Villager","items":["Silver Lance"],"ai":{"start":"Null","mission":"Null","attack":"ExcludePerson","attackParam":"PID_セレナ","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[12,17],"to":[12,17],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Hammer"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[13,17],"to":[13,17],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Killer Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[7,16],"to":[7,16],"difficulties":["normal","hard"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[7,13],"to":[7,13],"difficulties":["normal","hard"],"class":"Sage","items":["Arcthunder"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[10,10],"to":[10,10],"difficulties":["normal","hard"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[7,16],"to":[7,16],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[7,13],"to":[7,13],"difficulties":["lunatic"],"class":"Sage","items":["Arcthunder"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[10,10],"to":[10,10],"difficulties":["lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[12,11],"to":[12,11],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[13,11],"to":[13,11],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":8},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[17,16],"to":[17,16],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[16,14],"to":[16,14],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[15,13],"to":[15,13],"difficulties":["lunatic"],"class":"Trickster","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[16,12],"to":[16,12],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[18,9],"to":[18,9],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcfire"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[19,8],"to":[19,8],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Killing Edge","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[17,7],"to":[17,7],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[19,10],"to":[19,10],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[21,11],"to":[21,11],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[23,11],"to":[23,11],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Killer Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[22,10],"to":[22,10],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[21,9],"to":[21,9],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[23,9],"to":[23,9],"difficulties":["lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[12,6],"to":[12,6],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk","Master Key"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[10,4],"to":[10,4],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcfire"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[15,4],"to":[15,4],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[14,2],"to":[14,2],"difficulties":["lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":5},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_X010_アサシン","team":"enemy","at":[4,11],"to":[4,11],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_X010_トリックスター","team":"enemy","at":[3,10],"to":[3,10],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[4,9],"to":[4,9],"difficulties":["hard","lunatic"],"class":"Sage","items":["Arcfire"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_X010_賢者","team":"enemy","at":[2,9],"to":[2,9],"difficulties":["lunatic"],"class":"Sage","items":["Arcwind"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":6},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":7},
  {"faction":"Enemy","pid":"PID_X010_バーサーカー","team":"enemy","at":[4,7],"to":[4,7],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":7},
  {"faction":"Enemy","pid":"PID_セレナ","team":"ally","at":[17,24],"to":[17,24],"difficulties":["normal","hard","lunatic"],"class":"Mercenary","items":["Steel Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_セレナ敵対","mission":"X010Serena","missionParam":"PID_X010_ホラント","attack":"Attack","move":"X010Serena","moveParam":"PID_X010_ホラント"},"group":0},
  {"faction":"Reinforce01","pid":"PID_X010_アサシン","team":"enemy","at":[5,3],"to":[5,3],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce01","pid":"PID_X010_バーサーカー","team":"enemy","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_X010_バーサーカー","team":"enemy","at":[18,3],"to":[18,3],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce02","pid":"PID_X010_トリックスター","team":"enemy","at":[20,3],"to":[20,3],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X010_賢者","team":"enemy","at":[11,3],"to":[11,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X010_賢者","team":"enemy","at":[14,3],"to":[14,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X010_アサシン","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce03","pid":"PID_X010_バーサーカー","team":"enemy","at":[14,6],"to":[14,6],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_X010_トリックスター","team":"enemy","at":[18,3],"to":[18,3],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce04","pid":"PID_X010_賢者","team":"enemy","at":[20,3],"to":[20,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcwind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_X010_トリックスター","team":"enemy","at":[5,3],"to":[5,3],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce05","pid":"PID_X010_アサシン","team":"enemy","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_X010_バーサーカー","team":"enemy","at":[5,3],"to":[5,3],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce06","pid":"PID_X010_賢者","team":"enemy","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_X010_賢者","team":"enemy","at":[18,3],"to":[18,3],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Arcfire"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Reinforce07","pid":"PID_X010_アサシン","team":"enemy","at":[20,3],"to":[20,3],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
