/** Scion of Legend: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X005, terrain X005). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_5 = {
 id: 'paralogue-5', rom: 'X005', terrainFile: 'X005', width: 22, height: 24,
 rows: [
   "1111111111111111111111",
   "1111111133111111111131",
   "111111EEEEE11111131111",
   "113111EEEEE13111311111",
   "113111ExxxE11111111111",
   "131311ExxxE11311113311",
   "131331ExxxE11311111131",
   "111331EExEE11111111111",
   "13111111111111w1133111",
   "11333111111111w1111111",
   "113311C11333111ww11111",
   "111111C133133111111131",
   "1331111311111111131111",
   "131111331111ww11113111",
   "1111111111311111113311",
   "1EEEEE1113331111111111",
   "1EEEEE1131111111131111",
   "1ExxxE11311EExEE133111",
   "1Exxxx13111ExxxE111311",
   "1ExxxE13131ExxxE113311",
   "1ExxEE11131ExxxE113311",
   "1EEEEE11311EEEEE131331",
   "11111113311EEEEE111131",
   "1111111111111111111111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[18,6],"to":[18,6],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[18,3],"to":[18,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[20,3],"to":[20,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[16,4],"to":[16,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[19,4],"to":[19,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[18,5],"to":[18,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[17,6],"to":[17,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[20,6],"to":[20,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[19,7],"to":[19,7],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[17,8],"to":[17,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[18,8],"to":[18,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[20,8],"to":[20,8],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X005_ボス","team":"enemy","at":[2,13],"to":[2,13],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow","Second Seal"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1,"boss":true},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[3,12],"to":[3,12],"difficulties":["normal","hard"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[4,11],"to":[4,11],"difficulties":["lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["normal","hard"],"class":"Barbarian","items":["Short Axe"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_ダークマージ","team":"enemy","at":[1,12],"to":[1,12],"difficulties":["normal","hard","lunatic"],"class":"Dark Mage","items":["Elfire"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_ダークマージ","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["normal","hard","lunatic"],"class":"Dark Mage","items":["Ruin"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_バーサーカー","team":"enemy","at":[4,13],"to":[4,13],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_アサシン","team":"enemy","at":[2,11],"to":[2,11],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_アサシン","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X005_剣士","team":"enemy","at":[2,6],"to":[2,6],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X005_賢者Ａ","move":"Person","moveParam":"PID_X005_賢者Ａ"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ダークマージ","team":"enemy","at":[7,10],"to":[7,10],"difficulties":["normal","hard","lunatic"],"class":"Dark Mage","items":["Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X005_賢者Ａ","move":"Person","moveParam":"PID_X005_賢者Ａ"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[8,22],"to":[8,22],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X005_賢者Ｂ","move":"Person","moveParam":"PID_X005_賢者Ｂ"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_剣士","team":"enemy","at":[16,14],"to":[16,14],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X005_賢者Ｃ","move":"Person","moveParam":"PID_X005_賢者Ｃ"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[17,17],"to":[17,17],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X005_賢者Ｃ","move":"Person","moveParam":"PID_X005_賢者Ｃ"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ダークマージ","team":"enemy","at":[16,12],"to":[16,12],"difficulties":["normal","hard","lunatic"],"class":"Dark Mage","items":["Elthunder"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_剣士","team":"enemy","at":[18,12],"to":[18,12],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_バーサーカー","team":"enemy","at":[18,14],"to":[18,14],"difficulties":["hard","lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_アサシン","team":"enemy","at":[20,13],"to":[20,13],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_蛮族","team":"enemy","at":[13,6],"to":[13,6],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_剣士","team":"enemy","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_アサシン","team":"enemy","at":[11,5],"to":[11,5],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_バーサーカー","team":"enemy","at":[11,1],"to":[11,1],"difficulties":["lunatic"],"class":"Berserker","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_バーサーカー","team":"enemy","at":[2,2],"to":[2,2],"difficulties":["normal","hard","lunatic"],"class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[3,1],"to":[3,1],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[1,3],"to":[1,3],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[1,1],"to":[1,1],"difficulties":["hard","lunatic"],"class":"Wyvern Rider","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_アサシン","team":"enemy","at":[18,20],"to":[18,20],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[20,20],"to":[20,20],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[18,22],"to":[18,22],"difficulties":["normal","hard","lunatic"],"class":"Wyvern Rider","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_ドラゴンナイト","team":"enemy","at":[20,22],"to":[20,22],"difficulties":["hard","lunatic"],"class":"Wyvern Rider","items":["Short Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_ウード","team":"ally","at":[11,10],"to":[11,10],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X005_賢者Ａ","team":"ally","at":[8,6],"to":[8,6],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"Heal","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X005_賢者Ｂ","team":"ally","at":[4,18],"to":[4,18],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"Heal","move":"Null"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X005_賢者Ｃ","team":"ally","at":[13,18],"to":[13,18],"difficulties":["normal","hard","lunatic"],"class":"Sage","items":["Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"Heal","move":"Null"},"group":0,"stationary":true},
 ],
} as const;
