/** The Dead King's Lament: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X018, terrain X018). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_18 = {
 id: 'paralogue-18', rom: 'X018', terrainFile: 'X018', width: 32, height: 32,
 rows: [
   "333333333333337777777777hhhhhhhh",
   "333333333333337777777777hhhhhhhh",
   "33333333333333777777777777hhhhhh",
   "33333333333333777777777777hhhhhh",
   "33333333333337777777777777hhhhhh",
   "3333333333337777777777777hhhhhhh",
   "3333333333311777777777777hhhhhhh",
   "3333331111111777777777771hhhhhhh",
   "333331sss1117777777777711hhhhhhh",
   "333311sss1177777777777711hhhhhhh",
   "111111sss11777777777777111hhhhhh",
   "1111111k1111777777777771111hhhhh",
   "1111111111117777777777711111hhhh",
   "11111111111117777777771sss11hhhh",
   "11311111111111777777711sss111hhh",
   "131111111117111777771111m1111hhh",
   "31331111117771j111111111111111hh",
   "333333111177771111111111111111hh",
   "333333311177777111111111111111hh",
   "333333331177777711111111111111hh",
   "333333337777777711111111111111hh",
   "33333337777777111111111111111hhh",
   "33333377777771111111111111111hhh",
   "3333777777777771111111111111hhhh",
   "333377777777777711111111111hhhhh",
   "77337777777777771111111111hhhhhh",
   "77777777777777711111111111hhhhhh",
   "7777777777777771111111111hhhhhhh",
   "7777777777777111111111111hhhhhhh",
   "777777777771111111111111hhhhhhhh",
   "777777111111111111111111hhhhhhhh",
   "33333311111111111111111hhhhhhhhh"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[18,28],"to":[18,28],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[16,26],"to":[16,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[18,26],"to":[18,26],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[15,27],"to":[15,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[17,27],"to":[17,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[19,27],"to":[19,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[20,27],"to":[20,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[16,28],"to":[16,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[20,28],"to":[20,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[21,28],"to":[21,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[14,29],"to":[14,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[16,29],"to":[16,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[18,29],"to":[18,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","name":"Panne","at":[19,29],"to":[19,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","name":"Cordelia","at":[22,29],"to":[22,29],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X018_ボス","team":"enemy","at":[7,11],"to":[7,11],"difficulties":["normal","hard","lunatic"],"name":"Zanth","class":"Berserker","items":["Tomahawk","Bullion (L)"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[16,20],"to":[16,20],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[19,21],"to":[19,21],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[23,21],"to":[23,21],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[25,23],"to":[25,23],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[22,18],"to":[22,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Tomahawk","Hammer"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[26,16],"to":[26,16],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_アサシン","team":"enemy","at":[21,19],"to":[21,19],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_アサシン","team":"enemy","at":[25,20],"to":[25,20],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_賢者","team":"enemy","at":[18,18],"to":[18,18],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sage","items":["Rexcalibur"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_賢者","team":"enemy","at":[24,19],"to":[24,19],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sage","items":["Bolganone"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_スナイパー","team":"enemy","at":[20,16],"to":[20,16],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_スナイパー","team":"enemy","at":[23,17],"to":[23,17],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[9,25],"to":[9,25],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[10,24],"to":[10,24],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[9,23],"to":[9,23],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[30,26],"to":[30,26],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[29,25],"to":[29,25],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[30,24],"to":[30,24],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Spear"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[20,11],"to":[20,11],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[21,12],"to":[21,12],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[22,11],"to":[22,11],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Spear"],"ai":{"start":"TurnAttackRange","startParam":"2","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[13,14],"to":[13,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[12,15],"to":[12,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_バーサーカー","team":"enemy","at":[10,13],"to":[10,13],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Tomahawk"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_ギャンレル","team":"enemy","at":[11,13],"to":[11,13],"difficulties":["normal","hard","lunatic"],"name":"Gangrel","class":"Trickster","items":["Levin Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_アサシン","team":"enemy","at":[11,11],"to":[11,11],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_アサシン","team":"enemy","at":[10,15],"to":[10,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_賢者","team":"enemy","at":[10,12],"to":[10,12],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sage","items":["Thoron"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_賢者","team":"enemy","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sage","items":["Bolganone"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_スナイパー","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_スナイパー","team":"enemy","at":[7,15],"to":[7,15],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow","Longbow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[2,13],"to":[2,13],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[1,14],"to":[1,14],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Spear"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[2,15],"to":[2,15],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[1,16],"to":[1,16],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[12,1],"to":[12,1],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[13,2],"to":[13,2],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[14,1],"to":[14,1],"difficulties":["normal","hard"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[1,18],"to":[1,18],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Spear"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[2,19],"to":[2,19],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[1,20],"to":[1,20],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Tomahawk"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[17,2],"to":[17,2],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Axe"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X018_ドラゴンマスター","team":"enemy","at":[18,1],"to":[18,1],"difficulties":["lunatic"],"name":"Ruffian","class":"Wyvern Lord","items":["Silver Lance"],"ai":{"start":"AttackRange","startParam":"0","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
 ],
} as const;
