/** Daughter to Dragons: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X016, terrain X016). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_16 = {
 id: 'paralogue-16', rom: 'X016', terrainFile: 'X016', width: 28, height: 27,
 rows: [
   "EEEEEEEEEEEEEEEEEEEEEEEEEEEE",
   "ExxxxEExxxxEExxxxEExxxxxxxxE",
   "ExHxxxxxxxxxxxxyxEExyxxxxxxE",
   "ExxxxxxxxxxxxxxxxEExxxxxxxxE",
   "ExxxxxxxxxxxxxxxxEExxxxxxxxE",
   "ExxxxEExxxxEExxxxEEEEEEExxEE",
   "EEGGEEEETTEEEETTEEEEEEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "ExxxxzxxxxxxxxxxzxxxxEExxxxE",
   "ExxxxzxxxxxxxxxxzxxxxEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "EETTEETTEETTEETTEEGGEEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "EEGGEETTEETTEETTEETTEEEExxEE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "ExxxxzxxxxxxxxxxzxxxxxxxxxxE",
   "ExxxxzxxxxxxxxxxzxxxxxxxxxxE",
   "ExxxxxxxxxxxxxxxxxxxxEExxxxE",
   "EEEEEEExxEETTEETTEETTEEEEEEE",
   "ExxxxEExxEExxxxxxEExxEExxxxE",
   "ExHxxxxxxEExxxxxxEExxxxxxxxE",
   "ExHxxxxxxEExxxxxxEExxxxxxxxE",
   "ExxxxEExxEExxxxxxEExxEExxxxE",
   "EEEEEEEEEEEEEEEEEEEEEEEEEEEE"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[23,2],"to":[23,2],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[20,1],"to":[20,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[22,1],"to":[22,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[25,1],"to":[25,1],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[21,2],"to":[21,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[26,2],"to":[26,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[21,3],"to":[21,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[24,3],"to":[24,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[26,3],"to":[26,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[20,4],"to":[20,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[22,4],"to":[22,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[23,4],"to":[23,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[25,4],"to":[25,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X016_ボス","team":"enemy","at":[15,2],"to":[15,2],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Waste","Spirit Dust"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[6,13],"to":[6,13],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Mire","Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[14,13],"to":[14,13],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Mire","Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[11,7],"to":[11,7],"difficulties":["hard","lunatic"],"class":"Sorcerer","items":["Mire","Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[12,24],"to":[12,24],"difficulties":["lunatic"],"class":"Sorcerer","items":["Mire","Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[6,2],"to":[6,2],"difficulties":["lunatic"],"class":"Sorcerer","items":["Mire","Nosferatu"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[11,2],"to":[11,2],"difficulties":["lunatic"],"class":"Sorcerer","items":["Mire","Ruin"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[24,19],"to":[24,19],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X016_ゾンビ","team":"enemy","at":[25,18],"to":[25,18],"difficulties":["normal","hard","lunatic"],"class":"Revenant","items":["Blighted Claws"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X016_ゾンビ","team":"enemy","at":[10,17],"to":[10,17],"difficulties":["normal","hard","lunatic"],"class":"Revenant","items":["Blighted Claws"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_変化壁ンン","mission":"Null","attack":"Person","attackParam":"PID_ンン","move":"Person","moveParam":"PID_ンン"},"group":2},
  {"faction":"Enemy","pid":"PID_X016_マミー","team":"enemy","at":[10,20],"to":[10,20],"difficulties":["normal","hard","lunatic"],"class":"Entombed","items":["Blighted Talons"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_変化壁ンン","mission":"Null","attack":"Person","attackParam":"PID_ンン","move":"Person","moveParam":"PID_ンン"},"group":2},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcthunder","Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_変化壁ンン","mission":"Null","attack":"Person","attackParam":"PID_ンン","move":"Person","moveParam":"PID_ンン"},"group":2},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[4,19],"to":[4,19],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcfire","Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_変化壁ンン","mission":"Null","attack":"Person","attackParam":"PID_ンン","move":"Person","moveParam":"PID_ンン"},"group":2},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[3,23],"to":[3,23],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear","Door Key"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[5,15],"to":[5,15],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[9,14],"to":[9,14],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[11,13],"to":[11,13],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcfire","Silver Sword","Door Key"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[13,12],"to":[13,12],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[15,14],"to":[15,14],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Silver Lance"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[3,13],"to":[3,13],"difficulties":["hard","lunatic"],"class":"Dark Knight","items":["Arcwind","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[18,13],"to":[18,13],"difficulties":["lunatic"],"class":"Dark Knight","items":["Arcthunder","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁１開","mission":"Null","attack":"Attack","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[6,7],"to":[6,7],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcthunder","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[7,9],"to":[7,9],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear","Door Key"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[9,8],"to":[9,8],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[11,9],"to":[11,9],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[13,8],"to":[13,8],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Waste","Chest Key"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[15,9],"to":[15,9],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Silver Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[16,7],"to":[16,7],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcwind","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[2,9],"to":[2,9],"difficulties":["lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[3,8],"to":[3,8],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[18,8],"to":[18,8],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[19,9],"to":[19,9],"difficulties":["lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁２開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[12,23],"to":[12,23],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Silver Lance"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[13,24],"to":[13,24],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[15,24],"to":[15,24],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[12,25],"to":[12,25],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Nosferatu"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[14,25],"to":[14,25],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcfire","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[14,23],"to":[14,23],"difficulties":["lunatic"],"class":"General","items":["Spear"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[15,23],"to":[15,23],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[15,25],"to":[15,25],"difficulties":["lunatic"],"class":"Dark Knight","items":["Arcwind","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁挟撃開","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[3,4],"to":[3,4],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Tomahawk"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[5,3],"to":[5,3],"difficulties":["normal","hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_マミー","team":"enemy","at":[8,4],"to":[8,4],"difficulties":["normal","hard","lunatic"],"class":"Entombed","items":["Blighted Talons"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcwind","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ソーサラー","team":"enemy","at":[10,3],"to":[10,3],"difficulties":["normal","hard","lunatic"],"class":"Sorcerer","items":["Ruin"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[13,3],"to":[13,3],"difficulties":["normal","hard","lunatic"],"class":"Dark Knight","items":["Arcfire","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ジェネラル","team":"enemy","at":[14,4],"to":[14,4],"difficulties":["normal","hard","lunatic"],"class":"General","items":["Spear"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ダークナイト","team":"enemy","at":[4,2],"to":[4,2],"difficulties":["hard","lunatic"],"class":"Dark Knight","items":["Arcthunder","Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X016_ウォーリアー","team":"enemy","at":[13,2],"to":[13,2],"difficulties":["hard","lunatic"],"class":"Warrior","items":["Silver Axe","Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_変化壁３","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_ンン","team":"ally","at":[24,23],"to":[24,23],"difficulties":["normal","hard","lunatic"],"class":"Manakete","items":["Dragonstone"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true},
 ],
} as const;
