/** Ghost of a Blade: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X021, terrain X021). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_21 = {
 id: 'paralogue-21', rom: 'X021', terrainFile: 'X021', width: 19, height: 30,
 rows: [
   "EEEEEEEEEEEEEEEEEEE",
   "EEEEEExxxxxxxEEEEEE",
   "EEEExxxxxxxxxxxEEEE",
   "EEExxxx8xxx8xxxxEEE",
   "EExxxx88xxx88xxxxEE",
   "EExxx8WWxxxWW88xxEE",
   "Exx888WxxxxxWx88xxE",
   "ExxxxxxxDDDxxxx8xxE",
   "Exx88xxxDDDxxxxxxxE",
   "Exx88xWxxxxxWx8xxxE",
   "Exxx888WxxxWW88xxxE",
   "EExxx88xxxxx88xxxEE",
   "EExxxx88xxx88xxxxEE",
   "EEExxxx8xxx88xxxEEE",
   "EEEExxx8xx88xxxEEEE",
   "EEEEExx8xxx8xxEEEEE",
   "EEEExxx8xxx8xxxEEEE",
   "EEEExxx8xxx8xxxEEEE",
   "EEEExxx8xxxxxxxEEEE",
   "EEEExxxxxxxxxxxEEEE",
   "EEExxxxxxxxxxxxxEEE",
   "EEExxxEEExxxExxxEEE",
   "EEExxxExxxxxExxxEEE",
   "EEExxxxxxxxxExxxEEE",
   "EExxxxxxxxxxExxxxEE",
   "EExxxxExxxxxxxxxxEE",
   "EExxxEEExxxEEEExxEE",
   "EExxxxxxxxxxxxxxxEE",
   "EEyxxxxxxxxxxxxxxEE",
   "EEEEEEEEEEEEEEEEEEE"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[4,26],"to":[4,26],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[3,24],"to":[3,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[4,24],"to":[4,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[2,25],"to":[2,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","at":[3,25],"to":[3,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","at":[5,25],"to":[5,25],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","at":[2,27],"to":[2,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","at":[3,27],"to":[3,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","at":[5,27],"to":[5,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","at":[6,27],"to":[6,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","at":[7,27],"to":[7,27],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","at":[3,28],"to":[3,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","at":[4,28],"to":[4,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ベルベット","team":"player","at":[5,28],"to":[5,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ティアモ","team":"player","at":[6,28],"to":[6,28],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X021_ボス","team":"enemy","at":[9,5],"to":[9,5],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Sol Katti","Speedwing"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3,"boss":true},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[13,28],"to":[13,28],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[14,28],"to":[14,28],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[15,27],"to":[15,27],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[13,25],"to":[13,25],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Axe","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[10,24],"to":[10,24],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[11,18],"to":[11,18],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[6,17],"to":[6,17],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[5,16],"to":[5,16],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[6,15],"to":[6,15],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[8,13],"to":[8,13],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[15,13],"to":[15,13],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[4,20],"to":[4,20],"difficulties":["hard","lunatic"],"class":"Hero","items":["Silver Axe","Silver Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[5,21],"to":[5,21],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[9,28],"to":[9,28],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[10,27],"to":[10,27],"difficulties":["hard","lunatic"],"class":"Trickster","items":["Levin Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[9,23],"to":[9,23],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[8,18],"to":[8,18],"difficulties":["lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Everytime","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[1,9],"to":[1,9],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[2,8],"to":[2,8],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[2,7],"to":[2,7],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[16,9],"to":[16,9],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"BandRange","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[15,9],"to":[15,9],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[14,8],"to":[14,8],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[17,8],"to":[17,8],"difficulties":["hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"BandRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[7,8],"to":[7,8],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[6,7],"to":[6,7],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[7,6],"to":[7,6],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Null","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[11,8],"to":[11,8],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Silver Sword","Silver Axe"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[12,7],"to":[12,7],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Null","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[8,5],"to":[8,5],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[10,5],"to":[10,5],"difficulties":["lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_アサシン","team":"enemy","at":[8,2],"to":[8,2],"difficulties":["normal","hard","lunatic"],"class":"Assassin","items":["Silver Sword","Silver Bow"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_ソードマスター","team":"enemy","at":[9,2],"to":[9,2],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Silver Sword"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_勇者","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["normal","hard","lunatic"],"class":"Hero","items":["Tomahawk","Silver Sword"],"ai":{"start":"Null","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X021_トリックスター","team":"enemy","at":[9,1],"to":[9,1],"difficulties":["normal","hard","lunatic"],"class":"Trickster","items":["Levin Sword","Physic"],"ai":{"start":"Null","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_レンハ","team":"ally","at":[14,22],"to":[14,22],"difficulties":["normal","hard","lunatic"],"class":"Swordmaster","items":["Killing Edge"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
