/** A Strangled Peace: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X003, terrain X003). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_3 = {
 id: 'paralogue-3', rom: 'X003', terrainFile: 'X003', width: 24, height: 18,
 rows: [
   "XXXXXXXXXXXXXXXXXXXXXXXX",
   "XXXXXXXXXX333333XXX333XX",
   "XggggggXXXX3333333X333XX",
   "X66XXXgggXXX333333XXXXXX",
   "X7666XXXgXXXXXXX33XXsssX",
   "X77777XXgggXXXXXXXXXsssX",
   "X7777776XXgegXXXXXXXX$XX",
   "X77777776XXXgggXXXXXXXXX",
   "X77777776XXXXXgggggXXXXX",
   "X77777776XXXX33333gegXXX",
   "X77777776XX33333333XgggX",
   "X77777766X333333333XXgXX",
   "X7777776XX33333333XXXeXX",
   "X7777766X333333333XgggXX",
   "X77776XXX3333333666g666X",
   "X7666XXXXX33666666gg666X",
   "XXXXXXXXX666666666g6666X",
   "XXXXXXXXXXXXXXXXXXXXXXXX"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[12,4],"to":[12,4],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[11,2],"to":[11,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[13,2],"to":[13,2],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[12,3],"to":[12,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[14,3],"to":[14,3],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[10,4],"to":[10,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[13,4],"to":[13,4],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[11,5],"to":[11,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[14,5],"to":[14,5],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[13,6],"to":[13,6],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X003_ボス","team":"enemy","at":[21,16],"to":[21,16],"difficulties":["normal","hard","lunatic"],"name":"Risen Chief","class":"Soldier","items":["Silver Lance","Elixir"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_X003_アーチャー","team":"enemy","at":[22,15],"to":[22,15],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[20,14],"to":[20,14],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_傭兵","team":"enemy","at":[15,16],"to":[15,16],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Mercenary","items":["Iron Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[12,16],"to":[12,16],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーマーナイト","team":"enemy","at":[21,8],"to":[21,8],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Knight","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーマーナイト","team":"enemy","at":[15,7],"to":[15,7],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Knight","items":["Javelin"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーマーナイト","team":"enemy","at":[16,1],"to":[16,1],"difficulties":["lunatic"],"name":"Risen","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[18,5],"to":[18,5],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_傭兵","team":"enemy","at":[17,4],"to":[17,4],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーチャー","team":"enemy","at":[19,3],"to":[19,3],"difficulties":["hard","lunatic"],"name":"Risen","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[20,2],"to":[20,2],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_傭兵","team":"enemy","at":[7,1],"to":[7,1],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Mercenary","items":["Steel Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[7,2],"to":[7,2],"difficulties":["hard","lunatic"],"name":"Risen","class":"Fighter","items":["Iron Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーチャー","team":"enemy","at":[5,1],"to":[5,1],"difficulties":["lunatic"],"name":"Risen","class":"Archer","items":["Steel Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[6,5],"to":[6,5],"difficulties":["hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーチャー","team":"enemy","at":[4,3],"to":[4,3],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Archer","items":["Iron Bow"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Person","moveParam":"PID_X003_村人"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_ペガサスナイト","team":"enemy","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Pegasus Knight","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_ペガサスナイト","team":"enemy","at":[2,10],"to":[2,10],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_ペガサスナイト","team":"enemy","at":[3,12],"to":[3,12],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Pegasus Knight","items":["Iron Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_アーマーナイト","team":"enemy","at":[6,14],"to":[6,14],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Knight","items":["Steel Lance"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_戦士","team":"enemy","at":[3,16],"to":[3,16],"difficulties":["normal","hard","lunatic"],"name":"Risen","class":"Fighter","items":["Steel Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Person","attackParam":"PID_X003_村人","move":"Null"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_村人","team":"ally","at":[16,10],"to":[16,10],"difficulties":["normal","hard","lunatic"],"name":"Villager","class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Null","move":"Position","moveParam":"pos(1,16)"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_村人","team":"ally","at":[17,9],"to":[17,9],"difficulties":["normal","hard","lunatic"],"name":"Villager","class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Null","move":"Position","moveParam":"pos(1,16)"},"group":0},
  {"faction":"Enemy","pid":"PID_X003_村人","team":"ally","at":[18,10],"to":[18,10],"difficulties":["normal","hard","lunatic"],"name":"Villager","class":"Villager","ai":{"start":"Everytime","mission":"Null","attack":"Null","move":"Position","moveParam":"pos(1,16)"},"group":0},
 ],
} as const;
