/** Wings of Justice: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM X009, terrain X009). Don't hand-edit: re-extract. */
export const MAP_PARALOGUE_9 = {
 id: 'paralogue-9', rom: 'X009', terrainFile: 'X009', width: 22, height: 26,
 rows: [
   "hhhhhhhhhhhhhhhhhhh333",
   "hhhhhhhhhhhhhhhh333333",
   "hhhh333333113333333333",
   "3133333333333331133333",
   "3333333333331133313333",
   "3333333331113333313133",
   "1113131113311111331333",
   "1331111111111111311333",
   "3111111331111111111113",
   "1111133111111331111111",
   "1111111111111311111111",
   "11vv1111111v1111vvv111",
   "1v111111vvvv1111111v11",
   "1111111111111111111v11",
   "1111113111111111331111",
   "1111113311111311113111",
   "1133111111111111111111",
   "1131111111331111111131",
   "1111111111111vvvv11111",
   "311111v1131111111v1111",
   "1111vv1331111111111111",
   "111v111111111111111111",
   "1311111111111111331111",
   "1131111111111111113111",
   "1111331111331111111111",
   "1111311111111111111131"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","name":"Chrom","at":[11,23],"to":[11,23],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[9,22],"to":[9,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","name":"Lissa","at":[11,22],"to":[11,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","name":"Frederick","at":[13,22],"to":[13,22],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴィオール","team":"player","name":"Virion","at":[7,23],"to":[7,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソワレ","team":"player","name":"Sully","at":[10,23],"to":[10,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ヴェイク","team":"player","name":"Vaike","at":[12,23],"to":[12,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ソール","team":"player","name":"Stahl","at":[15,23],"to":[15,23],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ミリエル","team":"player","name":"Miriel","at":[8,24],"to":[8,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_スミア","team":"player","name":"Sumia","at":[9,24],"to":[9,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_ロンクー","team":"player","name":"Lon'qu","at":[11,24],"to":[11,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_リヒト","team":"player","name":"Ricken","at":[13,24],"to":[13,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Player","pid":"PID_マリアベル","team":"player","name":"Maribelle","at":[14,24],"to":[14,24],"difficulties":["normal","hard","lunatic"],"deploySlot":true},
  {"faction":"Enemy","pid":"PID_X009_ボス","team":"enemy","at":[17,5],"to":[17,5],"difficulties":["normal","hard","lunatic"],"name":"Ruger","class":"Trickster","items":["Levin Sword","Bullion (L)"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"X009Boss","missionParam":"pos(20,1),50","attack":"Null","move":"X009Boss","moveParam":"pos(20,1)"},"group":0,"boss":true},
  {"faction":"Enemy","pid":"PID_シンシア","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["normal"],"name":"Cynthia","class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_偽物３","team":"enemy","at":[4,15],"to":[4,15],"difficulties":["normal"],"name":"Ruffian","class":"Warrior","items":["Silver Axe","Silver Bow","Elixir"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[7,15],"to":[7,15],"difficulties":["normal"],"name":"Ruffian","class":"Hero","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[6,17],"to":[6,17],"difficulties":["normal"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[5,17],"to":[5,17],"difficulties":["normal"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[3,18],"to":[3,18],"difficulties":["normal"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["normal"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_シンシア","team":"enemy","at":[3,14],"to":[3,14],"difficulties":["hard","lunatic"],"name":"Cynthia","class":"Pegasus Knight","items":["Steel Lance"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_偽物３","team":"enemy","at":[4,15],"to":[4,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Warrior","items":["Silver Axe","Silver Bow","Elixir"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[7,15],"to":[7,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[6,17],"to":[6,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[5,17],"to":[5,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[3,18],"to":[3,18],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[2,17],"to":[2,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[4,18],"to":[4,18],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[3,16],"to":[3,16],"difficulties":["lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":3},
  {"faction":"Enemy","pid":"PID_X009_偽物１","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["normal"],"name":"Ruffian","class":"Great Knight","items":["Spear","Second Seal"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[13,15],"to":[13,15],"difficulties":["normal"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["normal"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[15,15],"to":[15,15],"difficulties":["normal"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[16,17],"to":[16,17],"difficulties":["normal"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[17,16],"to":[17,16],"difficulties":["normal"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_偽物１","team":"enemy","at":[17,14],"to":[17,14],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Great Knight","items":["Spear","Second Seal"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[13,15],"to":[13,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[14,16],"to":[14,16],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[15,15],"to":[15,15],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[16,17],"to":[16,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[17,16],"to":[17,16],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[18,17],"to":[18,17],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[14,14],"to":[14,14],"difficulties":["lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"TurnAttackRange","startParam":"3","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":4},
  {"faction":"Enemy","pid":"PID_X009_偽物４","team":"enemy","at":[5,10],"to":[5,10],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sage","items":["Arcfire","Arms Scroll"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[8,11],"to":[8,11],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Tomahawk"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[6,12],"to":[6,12],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[5,12],"to":[5,12],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[4,11],"to":[4,11],"difficulties":["normal","hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[7,10],"to":[7,10],"difficulties":["hard","lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[6,11],"to":[6,11],"difficulties":["lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_偽物２","team":"enemy","at":[14,10],"to":[14,10],"difficulties":["normal","hard"],"name":"Ruffian","class":"War Cleric","items":["Tomahawk","Physic"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[12,11],"to":[12,11],"difficulties":["normal","hard"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[13,12],"to":[13,12],"difficulties":["normal","hard"],"name":"Ruffian","class":"Hero","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["normal","hard"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[15,11],"to":[15,11],"difficulties":["normal","hard"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[16,10],"to":[16,10],"difficulties":["hard"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":2},
  {"faction":"Enemy","pid":"PID_X009_偽物２","team":"enemy","at":[14,10],"to":[14,10],"difficulties":["lunatic"],"name":"Ruffian","class":"War Cleric","items":["Tomahawk","Physic"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"AttackToHeal","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[12,11],"to":[12,11],"difficulties":["lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[13,12],"to":[13,12],"difficulties":["lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[14,12],"to":[14,12],"difficulties":["lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_スナイパー","team":"enemy","at":[15,11],"to":[15,11],"difficulties":["lunatic"],"name":"Ruffian","class":"Sniper","items":["Silver Bow"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_バーサーカー","team":"enemy","at":[16,10],"to":[16,10],"difficulties":["lunatic"],"name":"Ruffian","class":"Berserker","items":["Silver Axe"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_勇者","team":"enemy","at":[13,10],"to":[13,10],"difficulties":["lunatic"],"name":"Ruffian","class":"Hero","items":["Silver Sword"],"ai":{"start":"FlagTrueAttackRange","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_X009_寝返り１","team":"ally","at":[5,7],"to":[5,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Bow Knight","items":["Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り２","team":"ally","at":[7,6],"to":[7,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Paladin","items":["Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り３","team":"ally","at":[7,8],"to":[7,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Great Knight","items":["Silver Axe"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り４","team":"ally","at":[8,7],"to":[8,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Dark Knight","items":["Arcthunder"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り５","team":"ally","at":[10,8],"to":[10,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Paladin","items":["Beast Killer"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り６","team":"ally","at":[11,6],"to":[11,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Paladin","items":["Silver Lance"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り７","team":"ally","at":[12,7],"to":[12,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Bow Knight","items":["Silver Bow"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り８","team":"ally","at":[13,7],"to":[13,7],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Great Knight","items":["Silver Lance"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り９","team":"ally","at":[14,8],"to":[14,8],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Paladin","items":["Silver Sword"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_X009_寝返り１０","team":"ally","at":[15,6],"to":[15,6],"difficulties":["normal","hard","lunatic"],"name":"Mercenary","class":"Dark Knight","items":["Arcwind"],"ai":{"start":"FlagTrue","startParam":"FLAG_敵突撃","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
 ],
} as const;
