/** The Verge of History: terrain (chars index TERRAIN in ./terrain) and placements, from the game's own map data (ROM P002, terrain P002). Don't hand-edit: re-extract. */
export const MAP_PROLOGUE = {
 id: 'prologue', rom: 'P002', terrainFile: 'P002', width: 17, height: 16,
 rows: [
   "111111ttttt111111",
   "11111111111111111",
   "11111111111111111",
   "ggggggg+++ggggggg",
   "ggggggg+++ggggggg",
   "ggggggg+++ggggggg",
   "11111111111gg1111",
   "11111111111gg1111",
   "111BB11BB11++1111",
   "11111111111++1111",
   "11111111111gg1111",
   "111BB11BB11ggg++g",
   "11111111111ggg++g",
   "11111111111gg1111",
   "11111111111gg1111",
   "11111111111gg1111"
 ],
 spawns: [
  {"faction":"Player","pid":"PID_クロム","team":"player","at":[3,13],"to":[3,13],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_プレイヤー男","team":"player","at":[4,14],"to":[4,14],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_リズ","team":"player","at":[1,13],"to":[1,13],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Player","pid":"PID_フレデリク","team":"player","at":[2,14],"to":[2,14],"difficulties":["normal","hard","lunatic"],"forced":true},
  {"faction":"Enemy","pid":"PID_P002_ボス","team":"enemy","at":[8,1],"to":[8,1],"difficulties":["normal","hard","lunatic"],"class":"Barbarian","items":["Hand Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0,"stationary":true,"boss":true},
  {"faction":"Enemy","pid":"PID_P002_剣士","team":"enemy","at":[7,3],"to":[7,3],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Bronze Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_P002_剣士","team":"enemy","at":[9,3],"to":[9,3],"difficulties":["hard","lunatic"],"class":"Myrmidon","items":["Bronze Sword"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_P002_魔道士","team":"enemy","at":[8,2],"to":[8,2],"difficulties":["hard","lunatic"],"class":"Mage","items":["Thunder"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_P002_蛮族","team":"enemy","at":[6,2],"to":[6,2],"difficulties":["lunatic"],"class":"Barbarian","items":["Bronze Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_P002_蛮族","team":"enemy","at":[10,2],"to":[10,2],"difficulties":["lunatic"],"class":"Barbarian","items":["Bronze Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":1},
  {"faction":"Enemy","pid":"PID_P002_魔道士","team":"enemy","at":[10,6],"to":[10,6],"difficulties":["normal","hard","lunatic"],"class":"Mage","items":["Wind"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_P002_蛮族","team":"enemy","at":[7,9],"to":[7,9],"difficulties":["normal"],"class":"Barbarian","items":["Bronze Axe"],"ai":{"start":"AttackRange","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_P002_蛮族","team":"enemy","at":[7,9],"to":[7,9],"difficulties":["hard","lunatic"],"class":"Barbarian","items":["Bronze Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_P002_剣士","team":"enemy","at":[4,10],"to":[4,10],"difficulties":["normal","hard","lunatic"],"class":"Myrmidon","items":["Bronze Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_P002_蛮族","team":"enemy","at":[1,8],"to":[1,8],"difficulties":["hard","lunatic"],"class":"Barbarian","items":["Bronze Axe"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Enemy","pid":"PID_P002_剣士","team":"enemy","at":[9,12],"to":[9,12],"difficulties":["lunatic"],"class":"Myrmidon","items":["Bronze Sword"],"ai":{"start":"Everytime","mission":"Null","attack":"Attack","move":"NearestEnemy"},"group":0},
  {"faction":"Event01","pid":"PID_クロム","team":"player","at":[0,13],"to":[3,13],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_リズ","team":"player","at":[0,13],"to":[1,13],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event01","pid":"PID_フレデリク","team":"player","at":[0,14],"to":[2,14],"difficulties":["normal","hard","lunatic"]},
  {"faction":"Event02","pid":"PID_プレイヤー男","team":"player","at":[0,14],"to":[4,14],"difficulties":["normal","hard","lunatic"]},
 ],
} as const;
