/**
 * Class base stats and weapon types (#122), from Serenes Forest's class base stats
 * (https://serenesforest.net/awakening/classes/base-stats/). Luck has no class base. A promotion adds the difference
 * between the new class's bases and the old one's. Generated by scripts/item-data/class-bases.py: don't hand-edit.
 */
import type { ClassId } from './classes';
import type { Stat } from './stats';

export type ClassBase = { readonly stats: Readonly<Record<Stat, number>>; readonly mov: number; readonly weapons: readonly string[] };

export const CLASS_BASES: Readonly<Partial<Record<ClassId, { readonly any?: ClassBase; readonly M?: ClassBase; readonly F?: ClassBase }>>> = {
  'lord': { M: { stats: { hp: 18, str: 6, mag: 0, skl: 5, spd: 7, lck: 0, def: 7, res: 0 }, mov: 5, weapons: ['sword'] }, F: { stats: { hp: 16, str: 5, mag: 1, skl: 6, spd: 8, lck: 0, def: 6, res: 1 }, mov: 5, weapons: ['sword'] } },
  'great-lord': { M: { stats: { hp: 23, str: 10, mag: 0, skl: 7, spd: 9, lck: 0, def: 10, res: 3 }, mov: 6, weapons: ['sword', 'lance'] }, F: { stats: { hp: 20, str: 8, mag: 1, skl: 9, spd: 11, lck: 0, def: 8, res: 4 }, mov: 6, weapons: ['sword', 'lance'] } },
  'tactician': { any: { stats: { hp: 16, str: 4, mag: 3, skl: 5, spd: 5, lck: 0, def: 5, res: 3 }, mov: 5, weapons: ['sword', 'tome'] } },
  'grandmaster': { any: { stats: { hp: 20, str: 7, mag: 6, skl: 7, spd: 7, lck: 0, def: 7, res: 5 }, mov: 6, weapons: ['sword', 'tome'] } },
  'cavalier': { any: { stats: { hp: 18, str: 6, mag: 0, skl: 5, spd: 6, lck: 0, def: 7, res: 0 }, mov: 7, weapons: ['sword', 'lance'] } },
  'paladin': { any: { stats: { hp: 25, str: 9, mag: 1, skl: 7, spd: 8, lck: 0, def: 10, res: 6 }, mov: 8, weapons: ['sword', 'lance'] } },
  'great-knight': { any: { stats: { hp: 26, str: 11, mag: 0, skl: 6, spd: 5, lck: 0, def: 14, res: 1 }, mov: 7, weapons: ['sword', 'lance', 'axe'] } },
  'knight': { any: { stats: { hp: 18, str: 8, mag: 0, skl: 4, spd: 2, lck: 0, def: 11, res: 0 }, mov: 4, weapons: ['lance'] } },
  'general': { any: { stats: { hp: 28, str: 12, mag: 0, skl: 7, spd: 4, lck: 0, def: 15, res: 3 }, mov: 5, weapons: ['lance', 'axe'] } },
  'myrmidon': { any: { stats: { hp: 16, str: 4, mag: 1, skl: 9, spd: 10, lck: 0, def: 4, res: 1 }, mov: 5, weapons: ['sword'] } },
  'swordmaster': { any: { stats: { hp: 20, str: 7, mag: 2, skl: 11, spd: 13, lck: 0, def: 6, res: 4 }, mov: 6, weapons: ['sword'] } },
  'mercenary': { any: { stats: { hp: 18, str: 5, mag: 0, skl: 8, spd: 7, lck: 0, def: 5, res: 0 }, mov: 5, weapons: ['sword'] } },
  'hero': { any: { stats: { hp: 22, str: 8, mag: 1, skl: 11, spd: 10, lck: 0, def: 8, res: 3 }, mov: 6, weapons: ['sword', 'axe'] } },
  'fighter': { any: { stats: { hp: 20, str: 8, mag: 0, skl: 5, spd: 5, lck: 0, def: 4, res: 0 }, mov: 5, weapons: ['axe'] } },
  'warrior': { any: { stats: { hp: 28, str: 12, mag: 0, skl: 8, spd: 7, lck: 0, def: 7, res: 3 }, mov: 6, weapons: ['axe', 'bow'] } },
  'barbarian': { any: { stats: { hp: 22, str: 8, mag: 0, skl: 3, spd: 8, lck: 0, def: 3, res: 0 }, mov: 5, weapons: ['axe'] } },
  'berserker': { any: { stats: { hp: 30, str: 13, mag: 0, skl: 5, spd: 11, lck: 0, def: 5, res: 1 }, mov: 6, weapons: ['axe'] } },
  'archer': { any: { stats: { hp: 16, str: 5, mag: 0, skl: 8, spd: 6, lck: 0, def: 5, res: 0 }, mov: 5, weapons: ['bow'] } },
  'sniper': { any: { stats: { hp: 20, str: 7, mag: 1, skl: 12, spd: 9, lck: 0, def: 10, res: 3 }, mov: 6, weapons: ['bow'] } },
  'bow-knight': { any: { stats: { hp: 24, str: 8, mag: 0, skl: 10, spd: 10, lck: 0, def: 6, res: 2 }, mov: 8, weapons: ['sword', 'bow'] } },
  'thief': { any: { stats: { hp: 16, str: 3, mag: 0, skl: 6, spd: 8, lck: 0, def: 2, res: 0 }, mov: 5, weapons: ['sword'] } },
  'assassin': { any: { stats: { hp: 21, str: 8, mag: 0, skl: 13, spd: 12, lck: 0, def: 5, res: 1 }, mov: 6, weapons: ['sword', 'bow'] } },
  'trickster': { any: { stats: { hp: 19, str: 4, mag: 4, skl: 10, spd: 11, lck: 0, def: 3, res: 5 }, mov: 6, weapons: ['sword', 'staff'] } },
  'pegasus-knight': { any: { stats: { hp: 16, str: 4, mag: 2, skl: 7, spd: 8, lck: 0, def: 4, res: 6 }, mov: 7, weapons: ['lance'] } },
  'falcon-knight': { any: { stats: { hp: 20, str: 6, mag: 3, skl: 10, spd: 11, lck: 0, def: 6, res: 9 }, mov: 8, weapons: ['lance', 'staff'] } },
  'dark-flier': { any: { stats: { hp: 19, str: 5, mag: 6, skl: 8, spd: 10, lck: 0, def: 5, res: 9 }, mov: 8, weapons: ['lance', 'tome'] } },
  'wyvern-rider': { any: { stats: { hp: 19, str: 7, mag: 0, skl: 6, spd: 5, lck: 0, def: 8, res: 0 }, mov: 7, weapons: ['axe'] } },
  'wyvern-lord': { any: { stats: { hp: 24, str: 11, mag: 0, skl: 8, spd: 7, lck: 0, def: 11, res: 3 }, mov: 8, weapons: ['lance', 'axe'] } },
  'griffon-rider': { any: { stats: { hp: 22, str: 9, mag: 0, skl: 10, spd: 9, lck: 0, def: 8, res: 3 }, mov: 8, weapons: ['axe'] } },
  'mage': { any: { stats: { hp: 16, str: 0, mag: 4, skl: 3, spd: 4, lck: 0, def: 2, res: 3 }, mov: 5, weapons: ['tome'] } },
  'sage': { any: { stats: { hp: 20, str: 1, mag: 7, skl: 5, spd: 7, lck: 0, def: 4, res: 5 }, mov: 6, weapons: ['tome', 'staff'] } },
  'dark-mage': { any: { stats: { hp: 18, str: 1, mag: 3, skl: 2, spd: 3, lck: 0, def: 4, res: 4 }, mov: 5, weapons: ['tome'] } },
  'sorcerer': { any: { stats: { hp: 23, str: 2, mag: 6, skl: 4, spd: 4, lck: 0, def: 7, res: 7 }, mov: 6, weapons: ['tome'] } },
  'dark-knight': { any: { stats: { hp: 25, str: 4, mag: 5, skl: 6, spd: 5, lck: 0, def: 9, res: 5 }, mov: 8, weapons: ['sword', 'tome'] } },
  'priest': { any: { stats: { hp: 16, str: 0, mag: 3, skl: 2, spd: 4, lck: 0, def: 1, res: 6 }, mov: 5, weapons: ['staff'] } },
  'war-monk': { any: { stats: { hp: 24, str: 5, mag: 5, skl: 4, spd: 6, lck: 0, def: 6, res: 6 }, mov: 6, weapons: ['axe', 'staff'] } },
  'troubadour': { any: { stats: { hp: 16, str: 0, mag: 3, skl: 2, spd: 5, lck: 0, def: 1, res: 5 }, mov: 7, weapons: ['staff'] } },
  'valkyrie': { any: { stats: { hp: 19, str: 0, mag: 5, skl: 4, spd: 8, lck: 0, def: 3, res: 8 }, mov: 8, weapons: ['tome', 'staff'] } },
  'villager': { any: { stats: { hp: 16, str: 1, mag: 0, skl: 1, spd: 1, lck: 0, def: 1, res: 0 }, mov: 5, weapons: ['lance'] } },
  'dancer': { any: { stats: { hp: 16, str: 1, mag: 1, skl: 5, spd: 8, lck: 0, def: 3, res: 1 }, mov: 5, weapons: ['sword'] } },
  'lodestar': { any: { stats: { hp: 21, str: 9, mag: 1, skl: 10, spd: 10, lck: 0, def: 8, res: 4 }, mov: 6, weapons: ['sword'] } },
  'dread-fighter': { any: { stats: { hp: 22, str: 8, mag: 4, skl: 7, spd: 9, lck: 0, def: 7, res: 10 }, mov: 6, weapons: ['sword', 'axe', 'tome'] } },
  'bride': { any: { stats: { hp: 21, str: 7, mag: 6, skl: 11, spd: 10, lck: 0, def: 7, res: 6 }, mov: 6, weapons: ['lance', 'bow', 'staff'] } },
};
