/**
 * Chapter data for Premonition, the Prologue and Chapters 1–6 (#109): generated from Fire Emblem Wiki chapter pages at the oldids in
 * each record's `source`, parsed from the templates (ChapData, ChapChars, ChapItems, ChapShop 3DS, ChapUnitCellFE13,
 * BossStats FE13), with boss names and a stat cross-check from SF boss data (all rows agree). Don't hand-edit: regenerate.
 */
import type { ChapterData } from '../chapters';

export const EARLY_MAPS: readonly ChapterData[] = [
  {
    id: "premonition",
    kind: "story",
    order: 0,
    label: "Premonition",
    title: "Invisible Ties",
    location: "Dragon's Table",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "2", "enemies": "1"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "2", "enemies": "1"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "2", "enemies": "1"}},
    recruits: [],
    forced: [],
    items: [],
    shop: null,
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Validar", "class": "Sorcerer", "level": "5", "count": "1", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "notes": "Does not initiate combat."},
      ],
      hard: [
        {"name": "Validar", "class": "Sorcerer", "level": "5", "count": "1", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "notes": "Does not initiate combat."},
      ],
      lunatic: [
        {"name": "Validar", "class": "Sorcerer", "level": "5", "count": "1", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "notes": "Does not initiate combat."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: [],
    bosses: {
      normal: [
        {"class": "Sorcerer", "level": "5", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "skills": [], "name": "Validar"},
      ],
      hard: [
        {"class": "Sorcerer", "level": "5", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "skills": [], "name": "Validar"},
      ],
      lunatic: [
        {"class": "Sorcerer", "level": "5", "stats": {"hp": "39", "str": "5", "mag": "21", "skl": "15", "spd": "13", "lck": "12", "def": "15", "res": "12", "mov": ""}, "items": [{"name": "Grima's Truth"}], "skills": [], "name": "Validar"},
      ],
    },
    unlocks: ["prologue"],
    source: {"page": "Invisible Ties (premonition)", "oldid": 754697},
  },
  {
    id: "prologue",
    kind: "story",
    order: 50,
    label: "Prologue",
    title: "The Verge of History",
    location: "Southtown",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4", "enemies": "5"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4", "enemies": "8"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4", "enemies": "11"}},
    recruits: [
      {"unit": "Chrom", "class": "Lord", "level": "1", "how": "Automatically from turn 1", "inventory": ["Falchion", "Rapier"]},
      {"unit": "Robin", "class": "Tactician", "level": "1", "how": "Automatically from turn 1", "inventory": ["Bronze Sword", "Thunder"]},
      {"unit": "Lissa", "class": "Cleric", "level": "1", "how": "Automatically from turn 1", "inventory": ["Heal", "Vulnerary"]},
      {"unit": "Frederick", "class": "Great Knight", "level": "1", "how": "Automatically from turn 1", "inventory": ["Silver Lance"]},
    ],
    forced: [],
    items: [],
    shop: {"location": "Southtown", "opensAfter": "chapter 3", "armory": [{"item": "Bronze Sword", "cost": 350}, {"item": "Bronze Lance", "cost": 400}, {"item": "Bronze Axe", "cost": 350}, {"item": "Bronze Bow", "cost": 350}, {"item": "Fire", "cost": 540}], "merchant": [{"item": "Iron Sword", "cost": 520}, {"item": "Iron Lance", "cost": 560}, {"item": "Iron Axe", "cost": 600}, {"item": "Iron Bow", "cost": 560}, {"item": "Wyrmslayer", "cost": 1500}, {"item": "Hammer", "cost": 1850}, {"item": "Concoction", "cost": 600}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Garrick", "class": "Barbarian", "level": "3", "count": "1", "stats": {"hp": "20", "str": "8", "mag": "0", "skl": "5", "spd": "7", "lck": "2", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Hand Axe"}]},
        {"name": "Ruffian", "class": "Myrmidon", "level": "1", "count": "2", "stats": {"hp": "15", "str": "4", "mag": "0", "skl": "5", "spd": "6", "lck": "4", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Sword"}], "notes": "The southern one immediately begins moving unprovoked."},
        {"name": "Ruffian", "class": "Mage", "level": "1", "count": "1", "stats": {"hp": "14", "str": "0", "mag": "4", "skl": "3", "spd": "4", "lck": "3", "def": "0", "res": "1", "mov": "5"}, "items": [{"name": "Wind"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Ruffian", "class": "Barbarian", "level": "1", "count": "1", "stats": {"hp": "16", "str": "5", "mag": "0", "skl": "2", "spd": "4", "lck": "2", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Axe"}]},
      ],
      hard: [
        {"name": "Garrick", "class": "Barbarian", "level": "3", "count": "1", "stats": {"hp": "25", "str": "10", "mag": "0", "skl": "6", "spd": "9", "lck": "3", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": ["Gamble"]},
        {"name": "Ruffian", "class": "Myrmidon", "level": "1", "count": "3", "stats": {"hp": "19~20", "str": "5~6", "mag": "0", "skl": "7~8", "spd": "8~9", "lck": "6~7", "def": "1", "res": "0~1", "mov": "5"}, "items": [{"name": "Bronze Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern one immediately begins moving unprovoked.; • The northern two both begin moving if either of them or the nearby Mage is provoked."},
        {"name": "Ruffian", "class": "Mage", "level": "1", "count": "1", "stats": {"hp": "17~18", "str": "0", "mag": "6~7", "skl": "4~5", "spd": "5~6", "lck": "4~5", "def": "0", "res": "1~2", "mov": "5"}, "items": [{"name": "Thunder"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a nearby Myrmidon is provoked."},
        {"name": "Ruffian", "class": "Mage", "level": "1", "count": "1", "stats": {"hp": "17~18", "str": "0", "mag": "6~7", "skl": "4~5", "spd": "5~6", "lck": "4~5", "def": "0", "res": "1~2", "mov": "5"}, "items": [{"name": "Wind"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Ruffian", "class": "Barbarian", "level": "1", "count": "2", "stats": {"hp": "21~22", "str": "7~8", "mag": "0", "skl": "3~4", "spd": "5~6", "lck": "3~4", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
      lunatic: [
        {"name": "Garrick", "class": "Barbarian", "level": "3", "count": "1", "stats": {"hp": "34", "str": "14", "mag": "0", "skl": "8", "spd": "12", "lck": "5", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Short Axe"}], "skills": ["Gamble"]},
        {"name": "Ruffian", "class": "Myrmidon", "level": "1", "count": "4", "stats": {"hp": "26", "str": "9", "mag": "0", "skl": "11", "spd": "12", "lck": "10", "def": "1", "res": "2", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random.)", "notes": "• The southern two immediately begin moving unprovoked.; • The northern two both begin moving if either of them or a nearby Mage or Barbarian is provoked."},
        {"name": "Ruffian", "class": "Mage", "level": "1", "count": "1", "stats": {"hp": "23", "str": "0", "mag": "10", "skl": "8", "spd": "9", "lck": "8", "def": "0", "res": "4", "mov": "5"}, "items": [{"name": "Elthunder"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a nearby Myrmidon or Barbarian is provoked."},
        {"name": "Ruffian", "class": "Barbarian", "level": "1", "count": "4", "stats": {"hp": "30", "str": "11", "mag": "0", "skl": "5", "spd": "9", "lck": "5", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern two immediately begin moving unprovoked.; • The northern two both begin moving if either of them or a nearby Myrmidon or Mage is provoked."},
        {"name": "Ruffian", "class": "Mage", "level": "1", "count": "1", "stats": {"hp": "23", "str": "0", "mag": "10", "skl": "8", "spd": "9", "lck": "8", "def": "0", "res": "4", "mov": "5"}, "items": [{"name": "Elwind"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+"],
    bosses: {
      normal: [
        {"class": "Barbarian", "level": "3", "stats": {"hp": "20", "str": "8", "mag": "0", "skl": "5", "spd": "7", "lck": "2", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": [], "name": "Garrick"},
      ],
      hard: [
        {"class": "Barbarian", "level": "3", "stats": {"hp": "25", "str": "10", "mag": "0", "skl": "6", "spd": "9", "lck": "3", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": ["Gamble"], "name": "Garrick"},
      ],
      lunatic: [
        {"class": "Barbarian", "level": "3", "stats": {"hp": "34", "str": "14", "mag": "0", "skl": "8", "spd": "12", "lck": "5", "def": "3", "res": "0", "mov": ""}, "items": [{"name": "Short Axe"}], "skills": ["Gamble"], "name": "Garrick"},
      ],
    },
    unlocks: ["chapter-1"],
    source: {"page": "The Verge of History", "oldid": 741973},
  },
  {
    id: "chapter-1",
    kind: "story",
    order: 200,
    label: "Chapter 1",
    title: "Unwelcome Change",
    location: "West of Ylisstol",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4+2 (Upon Sully and Virion arriving)", "enemies": "7"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4+2 (Upon Sully and Virion arriving)", "enemies": "8"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "4+2 (Upon Sully and Virion arriving)", "enemies": "8"}},
    recruits: [
      {"unit": "Sully", "class": "Cavalier", "level": "2", "how": "Automatically from turn 2", "inventory": ["Bronze Lance"]},
      {"unit": "Virion", "class": "Archer", "level": "2", "how": "Automatically from turn 2", "inventory": ["Iron Bow", "Elixir"]},
    ],
    forced: ["Chrom"],
    items: [],
    shop: {"location": "West of Ylisstol", "opensAfter": "chapter 3", "armory": [{"item": "Heal", "cost": 600}, {"item": "Vulnerary", "cost": 300}], "merchant": [{"item": "Iron Sword", "cost": 520}, {"item": "Iron Lance", "cost": 560}, {"item": "Iron Axe", "cost": 600}, {"item": "Iron Bow", "cost": 560}, {"item": "Rescue", "cost": 1280}, {"item": "Physic", "cost": 1800}, {"item": "Concoction", "cost": 600}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Risen Chief", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "24", "str": "9", "mag": "0", "skl": "8", "spd": "6", "lck": "5", "def": "4", "res": "0", "mov": "5"}, "items": [{"name": "Hand Axe"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Fighter", "level": "1", "count": "3", "stats": {"hp": "16", "str": "7", "mag": "0", "skl": "5", "spd": "5", "lck": "3", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Axe"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Mercenary", "level": "1", "count": "2", "stats": {"hp": "15", "str": "6", "mag": "0", "skl": "8", "spd": "7", "lck": "3", "def": "2", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Sword"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Archer", "level": "1", "count": "1", "stats": {"hp": "15", "str": "5", "mag": "0", "skl": "8", "spd": "6", "lck": "2", "def": "1", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Bow"}], "notes": "Immediately begins moving unprovoked."},
      ],
      hard: [
        {"name": "Risen Chief", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "29+5 (Granted by HP +5)", "str": "11", "mag": "0", "skl": "10", "spd": "7", "lck": "7", "def": "4", "res": "0", "mov": "5"}, "items": [{"name": "Hand Axe"}], "skills": ["HP +5"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Fighter", "level": "1", "count": "4", "stats": {"hp": "21~22", "str": "9~10", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "5~6", "def": "1~2", "res": "0", "mov": "5"}, "items": [{"name": "Bronze Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Mercenary", "level": "1", "count": "2", "stats": {"hp": "20", "str": "8~9", "mag": "0", "skl": "10~11", "spd": "9~10", "lck": "4~5", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Bronze Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Archer", "level": "1", "count": "1", "stats": {"hp": "19~20", "str": "6~7", "mag": "0", "skl": "10~11", "spd": "7~8", "lck": "3~4", "def": "1~2", "res": "0~1", "mov": "5"}, "items": [{"name": "Bronze Bow"}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
      lunatic: [
        {"name": "Risen Chief", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "37+5 (Granted by HP +5)", "str": "15", "mag": "0", "skl": "13", "spd": "9", "lck": "11", "def": "5", "res": "0", "mov": "5"}, "items": [{"name": "Short Axe"}], "skills": ["HP +5"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Fighter", "level": "1", "count": "3", "stats": {"hp": "29", "str": "13", "mag": "0", "skl": "10", "spd": "8", "lck": "9", "def": "2", "res": "0", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Mercenary", "level": "1", "count": "2", "stats": {"hp": "27", "str": "12", "mag": "0", "skl": "14", "spd": "13", "lck": "8", "def": "3", "res": "1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Archer", "level": "1", "count": "1", "stats": {"hp": "27", "str": "9", "mag": "0", "skl": "14", "spd": "10", "lck": "6", "def": "2", "res": "1", "mov": "5"}, "items": [{"name": "Iron Bow"}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Risen", "class": "Fighter", "level": "1", "count": "1", "stats": {"hp": "29", "str": "13", "mag": "0", "skl": "10", "spd": "8", "lck": "9", "def": "2", "res": "0", "mov": "5"}, "items": [{"name": "Hammer"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+"],
    bosses: {
      normal: [
        {"class": "Fighter", "level": "3", "stats": {"hp": "24", "str": "9", "mag": "0", "skl": "8", "spd": "6", "lck": "5", "def": "4", "res": "0", "mov": "5"}, "items": [{"name": "Hand Axe"}], "skills": [], "name": "Risen Chief"},
      ],
      hard: [
        {"class": "Fighter", "level": "3", "stats": {"hp": "29+5 (Granted by HP +5)", "str": "11", "mag": "0", "skl": "10", "spd": "7", "lck": "7", "def": "4", "res": "0", "mov": "5"}, "items": [{"name": "Hand Axe"}], "skills": ["HP +5"], "name": "Risen Chief"},
      ],
      lunatic: [
        {"class": "Fighter", "level": "3", "stats": {"hp": "37+5 (Granted by HP +5)", "str": "15", "mag": "0", "skl": "13", "spd": "9", "lck": "11", "def": "5", "res": "0", "mov": "5"}, "items": [{"name": "Short Axe"}], "skills": ["HP +5"], "name": "Risen Chief"},
      ],
    },
    unlocks: ["chapter-2"],
    source: {"page": "Unwelcome Change", "oldid": 741770},
  },
  {
    id: "chapter-2",
    kind: "story",
    order: 300,
    label: "Chapter 2",
    title: "Shepherds",
    location: "The Northroad",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "8+1 (Upon Miriel arriving)", "enemies": "12"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "8+1 (Upon Miriel arriving)", "enemies": "14"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "8+1 (Upon Miriel arriving)", "enemies": "16"}},
    recruits: [
      {"unit": "Stahl", "class": "Cavalier", "level": "2", "how": "Automatically from turn 1", "inventory": ["Bronze Sword"]},
      {"unit": "Vaike", "class": "Fighter", "level": "3", "how": "Automatically from turn 1"},
      {"unit": "Miriel", "class": "Mage", "level": "1", "how": "Automatically from turn 2", "inventory": ["Fire", "Iron Axe"]},
    ],
    forced: ["Chrom"],
    items: [
      {"item": "Iron Sword", "how": "Dropped by enemy Mercenary"},
      {"item": "Iron Lance", "how": "Dropped by enemy Soldier"},
    ],
    shop: {"location": "The Northroad", "opensAfter": "chapter 3", "armory": [{"item": "Fire", "cost": 540}, {"item": "Thunder", "cost": 630}, {"item": "Wind", "cost": 450}, {"item": "Flux", "cost": 540}], "merchant": [{"item": "Iron Sword", "cost": 520}, {"item": "Iron Lance", "cost": 560}, {"item": "Iron Axe", "cost": 600}, {"item": "Iron Bow", "cost": 560}, {"item": "Beast Killer", "cost": 1650}, {"item": "Blessed Bow", "cost": 1540}, {"item": "Concoction", "cost": 600}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Risen Chief", "class": "Barbarian", "level": "4", "count": "1", "stats": {"hp": "26", "str": "11", "mag": "0", "skl": "7", "spd": "8", "lck": "3", "def": "4", "res": "1", "mov": ""}, "items": [{"name": "Hand Axe"}]},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "2", "stats": {"hp": "17~18", "str": "6~7", "mag": "0", "skl": "8~9", "spd": "7~8", "lck": "3~4", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Sword"}]},
        {"name": "Risen", "class": "Barbarian", "level": "2", "count": "4", "stats": {"hp": "18~19", "str": "7~8", "mag": "0", "skl": "3~4", "spd": "5~6", "lck": "2~3", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Axe"}]},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "3", "stats": {"hp": "17~18", "str": "6~7", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "4~5", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Lance"}]},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "1", "stats": {"hp": "17~18", "str": "6~7", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "4~5", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Lance", "drop": true}]},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "1", "stats": {"hp": "17~18", "str": "6~7", "mag": "0", "skl": "8~9", "spd": "7~8", "lck": "3~4", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Sword", "drop": true}]},
      ],
      hard: [
        {"name": "Risen Chief", "class": "Barbarian", "level": "4", "count": "1", "stats": {"hp": "31", "str": "13", "mag": "0", "skl": "8", "spd": "10", "lck": "4", "def": "4", "res": "1", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": ["Gamble"]},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "2", "stats": {"hp": "22~23", "str": "8~9", "mag": "0", "skl": "10~11", "spd": "9~10", "lck": "5~6", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern one immediately begins moving unprovoked.; • The northern one begins moving if a northern Barbarian, Soldier, or Mercenary is provoked."},
        {"name": "Risen", "class": "Barbarian", "level": "2", "count": "4", "stats": {"hp": "24~25", "str": "9~10", "mag": "0", "skl": "4~5", "spd": "7", "lck": "3~4", "def": "2~3", "res": "0", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern two immediately begin moving unprovoked.; • The northern two both begin moving if either of them or a northern Mercenary or Soldier is provoked."},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "5", "stats": {"hp": "23~24", "str": "8~9", "mag": "0", "skl": "8~9", "spd": "8~9", "lck": "6~7", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Lance"}], "notes": "• The southern four immediately begin moving unprovoked.; • The northern one begins moving if a northern Mercenary, Barbarian, or Soldier is provoked."},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "1", "stats": {"hp": "23~24", "str": "8~9", "mag": "0", "skl": "8~9", "spd": "8~9", "lck": "6~7", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Lance", "drop": true}], "notes": "Begins moving if a northern Mercenary, Barbarian, or Soldier is provoked."},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "1", "stats": {"hp": "22~23", "str": "8~9", "mag": "0", "skl": "10~11", "spd": "9~10", "lck": "5~6", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword", "drop": true}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a northern Mercenary, Barbarian, or Soldier is provoked."},
      ],
      lunatic: [
        {"name": "Risen Chief", "class": "Barbarian", "level": "4", "count": "1", "stats": {"hp": "40", "str": "17", "mag": "0", "skl": "10", "spd": "13", "lck": "6", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Short Axe"}], "skills": ["Gamble"], "notes": "Will not move until a unit is in range of at least two of the following—him, the two northern Mercenaries, the two northern Barbarians, or the two northern Soldiers—or until one of them is fought; in either case, he begins moving."},
        {"name": "Risen", "class": "Barbarian", "level": "2", "count": "5", "stats": {"hp": "33", "str": "14", "mag": "0", "skl": "7", "spd": "10", "lck": "6", "def": "3", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern three immediately begin moving unprovoked.; • The northern two will not move until a unit is in range of at least two of the following—either of them, the Risen Chief, the two northern Mercenaries, or the two northern Soldiers—or until one of them is fought; in either case, they begin moving."},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "3", "stats": {"hp": "30", "str": "12", "mag": "0", "skl": "15", "spd": "13", "lck": "8", "def": "3", "res": "1", "mov": "5"}, "items": [{"name": "Steel Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern two immediately begin moving unprovoked.; • The northern one will not move until a unit is in range of at least two of the following—him, the Risen Chief, the northern Mercenary, the two northern Barbarians, or the two northern Soldiers—or until one of them is fought; in either case, they begin moving."},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "5", "stats": {"hp": "32", "str": "11", "mag": "0", "skl": "11", "spd": "11", "lck": "9", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Lance"}], "notes": "• The southern four immediately begin moving unprovoked.; • The northern one will not move until a unit is in range of at least two of the following—him, the Risen Chief, the two northern Mercenaries, the two northern Barbarians, or the northern Soldier—or until one of them is fought; in either case, they begin moving."},
        {"name": "Risen", "class": "Soldier", "level": "2", "count": "1", "stats": {"hp": "32", "str": "11", "mag": "0", "skl": "11", "spd": "11", "lck": "9", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Lance"}, {"name": "Iron Lance", "drop": true}], "notes": "Will not move until a unit is in range of at least two of the following—him, the Risen Chief, the two northern Mercenaries, the two northern Barbarians, or the northern Soldier—or until one of them is fought; in either case, they begin moving."},
        {"name": "Risen", "class": "Mercenary", "level": "2", "count": "1", "stats": {"hp": "30", "str": "12", "mag": "0", "skl": "15", "spd": "13", "lck": "8", "def": "3", "res": "1", "mov": "5"}, "items": [{"name": "Steel Sword"}, {"name": "Iron Sword", "drop": true}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Will not move until a unit is in range of at least two of the following—him, the Risen Chief, the northern Mercenary, the two northern Barbarians, or the two northern Soldiers—or until one of them is fought; in either case, they begin moving."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+"],
    bosses: {
      normal: [
        {"class": "Barbarian", "level": "4", "stats": {"hp": "26", "str": "11", "mag": "0", "skl": "7", "spd": "8", "lck": "3", "def": "4", "res": "1", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": [], "name": "Risen Chief"},
      ],
      hard: [
        {"class": "Barbarian", "level": "4", "stats": {"hp": "31", "str": "13", "mag": "0", "skl": "8", "spd": "10", "lck": "4", "def": "4", "res": "1", "mov": ""}, "items": [{"name": "Hand Axe"}], "skills": ["Gamble"], "name": "Risen Chief"},
      ],
      lunatic: [
        {"class": "Barbarian", "level": "4", "stats": {"hp": "40", "str": "17", "mag": "0", "skl": "10", "spd": "13", "lck": "6", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Short Axe"}], "skills": ["Gamble"], "name": "Risen Chief"},
      ],
    },
    unlocks: ["chapter-3"],
    source: {"page": "Shepherds (chapter)", "oldid": 742135},
  },
  {
    id: "chapter-3",
    kind: "story",
    order: 400,
    label: "Chapter 3",
    title: "Warrior Realm",
    location: "The Longfort",
    conditions: {"normal": {"victory": "Defeat Raimi", "defeat": "Chrom or Robin dies, or both door keys are lost before either door can be opened", "deploy": "1–8+1 (Upon Sumia arriving)+1 (Upon Kellam being recruited)", "enemies": "13"}, "hard": {"victory": "Defeat Raimi", "defeat": "Chrom or Robin dies, or both door keys are lost before either door can be opened", "deploy": "1–8+1 (Upon Sumia arriving)+1 (Upon Kellam being recruited)", "enemies": "17"}, "lunatic": {"victory": "Defeat Raimi", "defeat": "Chrom or Robin dies, or both door keys are lost before either door can be opened", "deploy": "1–8+1 (Upon Sumia arriving)", "enemies": "18"}},
    recruits: [
      {"unit": "Sumia", "class": "Pegasus Knight", "level": "1", "how": "Automatically from turn 1", "inventory": ["Iron Lance", "Vulnerary"]},
      {"unit": "Kellam", "class": "Knight", "level": "5", "how": "NPC, talk to with Chrom", "inventory": ["Iron Lance", "Javelin", "Vulnerary"]},
    ],
    forced: ["Chrom"],
    items: [
      {"item": "Door Key", "how": "Dropped by enemy Archer"},
      {"item": "Door Key", "how": "Dropped by enemy Mercenary"},
      {"item": "Hammer", "how": "Dropped by enemy Fighter"},
      {"item": "Heal", "how": "Dropped by enemy Knight; (Lunatic only)"},
    ],
    shop: {"location": "The Longfort", "opensAfter": "this chapter", "armory": [{"item": "Heal", "cost": 600}, {"item": "Vulnerary", "cost": 300}, {"item": "Strength Tonic", "cost": 150}, {"item": "Defense Tonic", "cost": 150}, {"item": "Reeking Box", "cost": 500}], "merchant": [{"item": "Iron Sword", "cost": 520}, {"item": "Iron Lance", "cost": 560}, {"item": "Iron Axe", "cost": 600}, {"item": "Iron Bow", "cost": 560}, {"item": "Rescue", "cost": 1280}, {"item": "Concoction", "cost": 600}, {"item": "HP Tonic", "cost": 150}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Raimi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "28", "str": "12", "mag": "0", "skl": "8", "spd": "2", "lck": "5", "def": "10", "res": "1", "mov": ""}, "items": [{"name": "Javelin"}], "notes": "Stands on a gate."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "1", "stats": {"hp": "18~19", "str": "6~7", "mag": "0", "skl": "8~9", "spd": "6~7", "lck": "2~3", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Bow"}], "notes": "Begins moving if the nearby Soldier or Archer is provoked."},
        {"name": "Feroxi", "class": "Soldier", "level": "3", "count": "3", "stats": {"hp": "18~19", "str": "6~7", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "4~5", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Lance"}], "notes": "• The western one begins moving if a nearby Archer is provoked.; • The eastern two both begin moving if either of them or the nearby Mercenary is provoked."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "1", "stats": {"hp": "18~19", "str": "6~7", "mag": "0", "skl": "8~9", "spd": "6~7", "lck": "2~3", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Bow"}, {"name": "Door Key", "drop": true}], "notes": "Begins moving if the nearby Archer or Soldier is provoked."},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "1", "stats": {"hp": "18~19", "str": "7~8", "mag": "0", "skl": "8~9", "spd": "7~8", "lck": "3~4", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}, {"name": "Door Key", "drop": true}], "notes": "Begins moving if a nearby Soldier is provoked."},
        {"name": "Feroxi", "class": "Knight", "level": "3", "count": "2", "stats": {"hp": "20~21", "str": "9~10", "mag": "0", "skl": "5~6", "spd": "1~2", "lck": "3~4", "def": "8~9", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}]},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "2", "stats": {"hp": "18~19", "str": "7~8", "mag": "0", "skl": "8~9", "spd": "7~8", "lck": "3~4", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "notes": "Begins moving if the nearest Fighter is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "20~21", "str": "9~10", "mag": "0", "skl": "5~6", "spd": "6~7", "lck": "4~5", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "notes": "Begins moving if the nearest Mercenary is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "20~21", "str": "9~10", "mag": "0", "skl": "5~6", "spd": "6~7", "lck": "4~5", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Hammer", "drop": true}], "notes": "Begins moving if the nearest Mercenary is provoked."},
      ],
      hard: [
        {"name": "Raimi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "33", "str": "14", "mag": "0", "skl": "11", "spd": "3", "lck": "7", "def": "11", "res": "1", "mov": ""}, "items": [{"name": "Javelin"}], "skills": ["Indoor Fighter"]},
        {"name": "Feroxi", "class": "Soldier", "level": "3", "count": "4", "stats": {"hp": "24~25", "str": "8~9", "mag": "0", "skl": "8~9", "spd": "8~9", "lck": "6~7", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Lance"}], "notes": "• The western two both begin moving if either of them or a nearby Archer is provoked.; • The eastern two both begin moving if either of them or the nearby Archer or Mercenary is provoked."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "4", "stats": {"hp": "23~24", "str": "8", "mag": "0", "skl": "11~12", "spd": "8", "lck": "4", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Bow"}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southwestern one begins moving if a nearby Soldier or Archer is provoked.; • The southeastern one begins moving if a nearby Soldier or Mercenary is provoked.; • The northern ones begin moving if the nearest Mercenary or Fighter is provoked."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "1", "stats": {"hp": "23~24", "str": "8", "mag": "0", "skl": "11~12", "spd": "8", "lck": "4", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Bow"}, {"name": "Door Key", "drop": true}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a nearby Soldier or Archer is provoked."},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "1", "stats": {"hp": "23~24", "str": "9~10", "mag": "0", "skl": "11~12", "spd": "9~10", "lck": "5~6", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}, {"name": "Door Key", "drop": true}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a nearby Soldier or Archer is provoked."},
        {"name": "Feroxi", "class": "Knight", "level": "3", "count": "2", "stats": {"hp": "26~27", "str": "12~13", "mag": "0", "skl": "7", "spd": "2~3", "lck": "5~6", "def": "9~10", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "2", "stats": {"hp": "23~24", "str": "9~10", "mag": "0", "skl": "11~12", "spd": "9~10", "lck": "5~6", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if the nearest Fighter or Archer is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "25~26", "str": "12~13", "mag": "0", "skl": "7~8", "spd": "7~8", "lck": "6~7", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if the nearest Mercenary or Archer is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "25~26", "str": "12~13", "mag": "0", "skl": "7~8", "spd": "7~8", "lck": "6~7", "def": "2~3", "res": "0~1", "mov": "5"}, "items": [{"name": "Hammer", "drop": true}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if the nearest Mercenary or Archer is provoked."},
      ],
      lunatic: [
        {"name": "Raimi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "42", "str": "18", "mag": "0", "skl": "13", "spd": "5", "lck": "10", "def": "12", "res": "1", "mov": ""}, "items": [{"name": "Short Spear"}], "skills": ["Indoor Fighter"], "notes": "Stands on a gate."},
        {"name": "Feroxi", "class": "Knight", "level": "3", "count": "3", "stats": {"hp": "35", "str": "16", "mag": "0", "skl": "10", "spd": "4", "lck": "9", "def": "11", "res": "1", "mov": "4"}, "items": [{"name": "Steel Lance"}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern one begins moving if a southern Soldier, Archer, Knight, or Mercenary is provoked.; • The northern two begin moving if a northern Mercenary, Fighter, or Archer is provoked."},
        {"name": "Feroxi", "class": "Soldier", "level": "3", "count": "3", "stats": {"hp": "33", "str": "12", "mag": "0", "skl": "12", "spd": "12", "lck": "10", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Steel Lance"}], "notes": "All three begin moving if any of them or a southern Knight, Archer, or Mercenary is provoked."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "4", "stats": {"hp": "31", "str": "11", "mag": "0", "skl": "15", "spd": "11", "lck": "7", "def": "4", "res": "2", "mov": "5"}, "items": [{"name": "Steel Bow"}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The southern two both begin moving if either of them or a southern Knight, Soldier, or Mercenary is provoked.; • The northern two both begin moving if either of them or a northern Mercenary or Fighter is provoked."},
        {"name": "Feroxi", "class": "Archer", "level": "3", "count": "1", "stats": {"hp": "31", "str": "11", "mag": "0", "skl": "15", "spd": "11", "lck": "7", "def": "4", "res": "2", "mov": "5"}, "items": [{"name": "Steel Bow"}, {"name": "Door Key", "drop": true}], "skills": ["Skill +2", "Prescience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a southern Knight, Soldier, Archer, or Mercenary is provoked."},
        {"name": "Feroxi", "class": "Knight", "level": "3", "count": "1", "stats": {"hp": "35", "str": "16", "mag": "0", "skl": "10", "spd": "4", "lck": "9", "def": "11", "res": "1", "mov": "4"}, "items": [{"name": "Steel Lance"}, {"name": "Heal", "drop": true}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a southern Knight, Soldier, Archer, or Mercenary is provoked."},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "1", "stats": {"hp": "31", "str": "13", "mag": "0", "skl": "15", "spd": "13", "lck": "9", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Steel Sword"}, {"name": "Door Key", "drop": true}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a southern Knight, Soldier, or Archer is provoked."},
        {"name": "Feroxi", "class": "Mercenary", "level": "3", "count": "2", "stats": {"hp": "31", "str": "13", "mag": "0", "skl": "15", "spd": "13", "lck": "9", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Steel Sword"}], "skills": ["Patience"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Both begin moving if either of them or a northern Fighter or Archer is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "34", "str": "16", "mag": "0", "skl": "11", "spd": "10", "lck": "10", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a northern Mercenary, Fighter, or Archer is provoked."},
        {"name": "Feroxi", "class": "Fighter", "level": "3", "count": "1", "stats": {"hp": "34", "str": "16", "mag": "0", "skl": "11", "spd": "10", "lck": "10", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Hammer", "drop": true}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving if a northern Mercenary, Fighter, or Archer is provoked."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+", "Counter", "Aegis+", "Pavise+"],
    bosses: {
      normal: [
        {"class": "Knight", "level": "5", "stats": {"hp": "28", "str": "12", "mag": "0", "skl": "9", "spd": "2", "lck": "5", "def": "10", "res": "1", "mov": ""}, "items": [{"name": "Javelin"}], "skills": [], "name": "Raimi"},
      ],
      hard: [
        {"class": "Knight", "level": "5", "stats": {"hp": "33", "str": "14", "mag": "0", "skl": "11", "spd": "3", "lck": "7", "def": "11", "res": "1", "mov": ""}, "items": [{"name": "Javelin"}], "skills": ["Indoor Fighter"], "name": "Raimi"},
      ],
      lunatic: [
        {"class": "Knight", "level": "5", "stats": {"hp": "42", "str": "18", "mag": "0", "skl": "13", "spd": "5", "lck": "10", "def": "12", "res": "1", "mov": ""}, "items": [{"name": "Short Spear"}], "skills": ["Indoor Fighter"], "name": "Raimi"},
      ],
    },
    unlocks: ["chapter-4", "paralogue-1"],
    source: {"page": "Warrior Realm", "oldid": 741809},
  },
  {
    id: "chapter-4",
    kind: "story",
    order: 500,
    label: "Chapter 4",
    title: "Two Falchions",
    location: "Arena Ferox",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–6", "enemies": "9"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–6", "enemies": "9"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–6", "enemies": "9"}},
    recruits: [
      {"unit": "Lon'qu", "class": "Myrmidon", "level": "4", "how": "Automatically at the end of the chapter", "inventory": ["Killing Edge"]},
    ],
    forced: ["Chrom"],
    items: [
      {"item": "Thunder", "how": "Dropped by enemy Mage"},
      {"item": "Vulnerary", "how": "Dropped by enemy Knight"},
    ],
    shop: {"location": "Arena Ferox", "opensAfter": "this chapter", "armory": [{"item": "Iron Lance", "cost": 560}, {"item": "Iron Bow", "cost": 560}, {"item": "Thunder", "cost": 630}], "merchant": [{"item": "Steel Sword", "cost": 840}, {"item": "Steel Lance", "cost": 910}, {"item": "Steel Axe", "cost": 980}, {"item": "Steel Bow", "cost": 910}, {"item": "Elfire", "cost": 980}, {"item": "Wyrmslayer", "cost": 1500}, {"item": "Blessed Lance", "cost": 1540}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Marth", "class": "Lord", "level": "8", "count": "1", "stats": {"hp": "27", "str": "9", "mag": "2", "skl": "12", "spd": "10", "lck": "11", "def": "8", "res": "4", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"]},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "22~23", "str": "10~11", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "5~6", "def": "3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "18~19", "str": "0", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "1~2", "res": "3", "mov": "5"}, "items": [{"name": "Thunder"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "18~19", "str": "0", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "1~2", "res": "3", "mov": "5"}, "items": [{"name": "Thunder", "drop": true}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "22~23", "str": "10~11", "mag": "0", "skl": "6", "spd": "1~2", "lck": "4~5", "def": "9~10", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}, {"name": "Vulnerary", "drop": true}], "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "22~23", "str": "10~11", "mag": "0", "skl": "6", "spd": "1~2", "lck": "4~5", "def": "9~10", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}], "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "22~23", "str": "10~11", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "5~6", "def": "3", "res": "0~1", "mov": "5"}, "items": [{"name": "Hand Axe"}], "notes": "Begins moving unprovoked on turn 3."},
      ],
      hard: [
        {"name": "Marth", "class": "Lord", "level": "8", "count": "1", "stats": {"hp": "31", "str": "11", "mag": "2", "skl": "14", "spd": "12", "lck": "13", "def": "8", "res": "5", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"]},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "27~28", "str": "13", "mag": "0", "skl": "8", "spd": "8", "lck": "7~8", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "22", "str": "0", "mag": "8~9", "skl": "7", "spd": "7", "lck": "6", "def": "1~2", "res": "3~4", "mov": "5"}, "items": [{"name": "Thunder"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "22", "str": "0", "mag": "8~9", "skl": "7", "spd": "7", "lck": "6", "def": "1~2", "res": "3~4", "mov": "5"}, "items": [{"name": "Thunder", "drop": true}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "28", "str": "13", "mag": "0", "skl": "7~8", "spd": "2~3", "lck": "6", "def": "9~10", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}, {"name": "Vulnerary", "drop": true}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "28", "str": "13", "mag": "0", "skl": "7~8", "spd": "2~3", "lck": "6", "def": "9~10", "res": "0~1", "mov": "4"}, "items": [{"name": "Iron Lance"}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "27~28", "str": "13", "mag": "0", "skl": "8", "spd": "8", "lck": "7~8", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Hand Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 3."},
      ],
      lunatic: [
        {"name": "Marth", "class": "Lord", "level": "8", "count": "1", "stats": {"hp": "38", "str": "14", "mag": "2", "skl": "18", "spd": "16", "lck": "17", "def": "8", "res": "7", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"], "notes": "Begins moving unprovoked on turn 4."},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "36", "str": "17", "mag": "0", "skl": "11", "spd": "10", "lck": "11", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "28", "str": "0", "mag": "12", "skl": "10", "spd": "10", "lck": "9", "def": "2", "res": "6", "mov": "5"}, "items": [{"name": "Elthunder"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "28", "str": "0", "mag": "12", "skl": "10", "spd": "10", "lck": "9", "def": "2", "res": "6", "mov": "5"}, "items": [{"name": "Elthunder"}, {"name": "Thunder", "drop": true}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "37", "str": "17", "mag": "0", "skl": "10", "spd": "4", "lck": "9", "def": "11", "res": "1", "mov": "4"}, "items": [{"name": "Steel Lance"}, {"name": "Vulnerary", "drop": true}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Knight", "level": "5", "count": "1", "stats": {"hp": "37", "str": "17", "mag": "0", "skl": "10", "spd": "4", "lck": "9", "def": "11", "res": "1", "mov": "4"}, "items": [{"name": "Steel Lance"}], "skills": ["Defense +2", "Indoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 2."},
        {"name": "Feroxi", "class": "Fighter", "level": "5", "count": "2", "stats": {"hp": "36", "str": "17", "mag": "0", "skl": "11", "spd": "10", "lck": "11", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Short Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Begins moving unprovoked on turn 3."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+", "Counter", "Aegis+", "Pavise+"],
    bosses: {
      normal: [
        {"class": "Lord", "level": "8", "stats": {"hp": "27", "str": "9", "mag": "2", "skl": "12", "spd": "10", "lck": "11", "def": "8", "res": "4", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"], "name": "Marth"},
      ],
      hard: [
        {"class": "Lord", "level": "8", "stats": {"hp": "31", "str": "11", "mag": "2", "skl": "14", "spd": "12", "lck": "13", "def": "8", "res": "5", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"], "name": "Marth"},
      ],
      lunatic: [
        {"class": "Lord", "level": "8", "stats": {"hp": "38", "str": "14", "mag": "2", "skl": "18", "spd": "16", "lck": "17", "def": "8", "res": "7", "mov": "5"}, "items": [{"name": "Parallel Falchion"}], "skills": ["Dual Strike+"], "name": "Marth"},
      ],
    },
    unlocks: ["chapter-5"],
    source: {"page": "Two Falchions", "oldid": 693840},
  },
  {
    id: "chapter-5",
    kind: "story",
    order: 600,
    label: "Chapter 5",
    title: "The Exalt and the King",
    location: "Border Pass",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–9+2 (Upon Ricken and Maribelle arriving)", "enemies": "15 (Shortly increases to 16 before the first turn while Gangrel is on the map; returns to 15 after Gangrel leaves)+5 (Reinforcements)"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–9+2 (Upon Ricken and Maribelle arriving)", "enemies": "19 (Shortly increases to 20 before the first turn while Gangrel is on the map; returns to 19 after Gangrel leaves)+8 (Reinforcements)"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom or Robin dies", "deploy": "1–9+2 (Upon Ricken and Maribelle arriving)", "enemies": "22 (Shortly increases to 23 before the first turn while Gangrel is on the map; returns to 22 after Gangrel leaves)+10 (Reinforcements)"}},
    recruits: [
      {"unit": "Ricken", "class": "Mage", "level": "3", "how": "Automatically from turn 1", "inventory": ["Elwind"]},
      {"unit": "Maribelle", "class": "Troubadour", "level": "3", "how": "Automatically from turn 1", "inventory": ["Mend", "Vulnerary"]},
    ],
    forced: ["Chrom"],
    items: [
      {"item": "Bullion (M)", "how": "Dropped by Orton"},
      {"item": "Hand Axe", "how": "Dropped by enemy Barbarian (reinforcement)"},
    ],
    shop: {"location": "Border Pass", "opensAfter": "this chapter", "armory": [{"item": "Iron Sword", "cost": 520}, {"item": "Iron Axe", "cost": 600}, {"item": "Wind", "cost": 450}], "merchant": [{"item": "Steel Sword", "cost": 840}, {"item": "Steel Lance", "cost": 910}, {"item": "Steel Axe", "cost": 980}, {"item": "Steel Bow", "cost": 910}, {"item": "Elthunder", "cost": 1050}, {"item": "Rescue", "cost": 1280}, {"item": "Elixir", "cost": 900}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Orton", "class": "Wyvern Rider", "level": "9", "count": "1", "stats": {"hp": "29", "str": "12", "mag": "0", "skl": "9", "spd": "8", "lck": "6", "def": "11", "res": "1", "mov": "7"}, "items": [{"name": "Short Axe"}, {"name": "Bullion (M)", "drop": true}]},
        {"name": "Plegian", "class": "Wyvern Rider", "level": "7", "count": "2", "stats": {"hp": "21~22", "str": "9~10", "mag": "0", "skl": "7~8", "spd": "6~7", "lck": "4~5", "def": "7~8", "res": "0~1", "mov": "7"}, "items": [{"name": "Iron Axe"}]},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "5", "stats": {"hp": "23~24", "str": "9~10", "mag": "0", "skl": "4~5", "spd": "6~7", "lck": "2~3", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "3", "stats": {"hp": "21~22", "str": "1", "mag": "5", "skl": "2~3", "spd": "3~4", "lck": "2~3", "def": "4", "res": "3", "mov": "5"}, "items": [{"name": "Flux"}], "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "3", "stats": {"hp": "19~20", "str": "7~8", "mag": "1", "skl": "9~10", "spd": "10~11", "lck": "5~6", "def": "3~4", "res": "1~2", "mov": "5"}, "items": [{"name": "Iron Sword"}], "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "18~19", "str": "0", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "1~2", "res": "3", "mov": "5"}, "items": [{"name": "Fire"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "1", "stats": {"hp": "23~24", "str": "9~10", "mag": "0", "skl": "4~5", "spd": "6~7", "lck": "2~3", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Hand Axe", "drop": true}]},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "2", "stats": {"hp": "19~20", "str": "7~8", "mag": "1", "skl": "9~10", "spd": "10~11", "lck": "5~6", "def": "3~4", "res": "1~2", "mov": "5"}, "items": [{"name": "Iron Sword"}]},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "1", "stats": {"hp": "21~22", "str": "1", "mag": "5", "skl": "2~3", "spd": "3~4", "lck": "2~3", "def": "4", "res": "3", "mov": "5"}, "items": [{"name": "Flux"}]},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "1", "stats": {"hp": "23~24", "str": "9~10", "mag": "0", "skl": "4~5", "spd": "6~7", "lck": "2~3", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}]},
      ],
      hard: [
        {"name": "Orton", "class": "Wyvern Rider", "level": "9", "count": "1", "stats": {"hp": "34", "str": "14", "mag": "0", "skl": "11", "spd": "10", "lck": "8", "def": "12", "res": "1", "mov": "7"}, "items": [{"name": "Short Axe"}, {"name": "Bullion (M)", "drop": true}], "skills": ["Tantivy"], "notes": "Begins moving if an outer Wyvern Rider is provoked."},
        {"name": "Plegian", "class": "Wyvern Rider", "level": "7", "count": "4", "stats": {"hp": "26~27", "str": "11~12", "mag": "0", "skl": "9", "spd": "8", "lck": "6~7", "def": "8~9", "res": "0~1", "mov": "7"}, "items": [{"name": "Iron Axe"}], "skills": ["Strength +2", "Tantivy"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The inner two immediately begin moving unprovoked.; • The outer two both begin moving if either of them or Orton is provoked."},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "6", "stats": {"hp": "29", "str": "12", "mag": "0", "skl": "6", "spd": "8", "lck": "4", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "3", "stats": {"hp": "26", "str": "1", "mag": "6~7", "skl": "4", "spd": "5", "lck": "4", "def": "4~5", "res": "3~4", "mov": "5"}, "items": [{"name": "Flux"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "4", "stats": {"hp": "24", "str": "9", "mag": "1", "skl": "12", "spd": "13", "lck": "8", "def": "3~4", "res": "2~3", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "22", "str": "0", "mag": "8~9", "skl": "7", "spd": "7", "lck": "6", "def": "1~2", "res": "4", "mov": "5"}, "items": [{"name": "Fire"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "2", "stats": {"hp": "29", "str": "12", "mag": "0", "skl": "6", "spd": "8", "lck": "4", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "1", "stats": {"hp": "29", "str": "12", "mag": "0", "skl": "6", "spd": "8", "lck": "4", "def": "3~4", "res": "0~1", "mov": "5"}, "items": [{"name": "Hand Axe", "drop": true}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "2", "stats": {"hp": "24", "str": "9", "mag": "1", "skl": "12", "spd": "13", "lck": "8", "def": "3~4", "res": "2~3", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Wyvern Rider", "level": "7", "count": "2", "stats": {"hp": "26~27", "str": "11~12", "mag": "0", "skl": "9", "spd": "8", "lck": "6~7", "def": "8~9", "res": "0~1", "mov": "7"}, "items": [{"name": "Iron Axe"}], "skills": ["Strength +2", "Tantivy"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "1", "stats": {"hp": "26", "str": "1", "mag": "6~7", "skl": "4", "spd": "5", "lck": "4", "def": "4~5", "res": "3~4", "mov": "5"}, "items": [{"name": "Flux"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
      ],
      lunatic: [
        {"name": "Orton", "class": "Wyvern Rider", "level": "9", "count": "1", "stats": {"hp": "41", "str": "18", "mag": "0", "skl": "13", "spd": "12", "lck": "11", "def": "13", "res": "1", "mov": "7"}, "items": [{"name": "Tomahawk"}, {"name": "Bullion (M)", "drop": true}], "skills": ["Tantivy"], "notes": "Begins moving if an outer Wyvern Rider is provoked."},
        {"name": "Plegian", "class": "Wyvern Rider", "level": "7", "count": "6", "stats": {"hp": "34", "str": "16", "mag": "0", "skl": "12", "spd": "11", "lck": "10", "def": "10", "res": "1", "mov": "7"}, "items": [{"name": "Steel Axe"}], "skills": ["Strength +2", "Tantivy"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "• The inner two immediately begin moving unprovoked.; • The outer four all begin moving if any of them or Orton is provoked."},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "6", "stats": {"hp": "38", "str": "16", "mag": "0", "skl": "8", "spd": "11", "lck": "8", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "3", "stats": {"hp": "34", "str": "1", "mag": "9", "skl": "6", "spd": "7", "lck": "6", "def": "5", "res": "6", "mov": "5"}, "items": [{"name": "Nosferatu"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "5", "stats": {"hp": "31", "str": "12", "mag": "1", "skl": "16", "spd": "17", "lck": "12", "def": "4", "res": "4", "mov": "5"}, "items": [{"name": "Steel Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "All except the one by the northern center fort immediately begin moving unprovoked."},
        {"name": "Plegian", "class": "Mage", "level": "5", "count": "1", "stats": {"hp": "28", "str": "0", "mag": "12", "skl": "10", "spd": "10", "lck": "9", "def": "2", "res": "6", "mov": "5"}, "items": [{"name": "Elfire"}], "skills": ["Magic +2", "Focus"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "2", "stats": {"hp": "38", "str": "16", "mag": "0", "skl": "8", "spd": "11", "lck": "8", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Barbarian", "level": "5", "count": "1", "stats": {"hp": "38", "str": "16", "mag": "0", "skl": "8", "spd": "11", "lck": "8", "def": "4", "res": "1", "mov": "5"}, "items": [{"name": "Short Axe"}, {"name": "Hand Axe", "drop": true}], "skills": ["Gamble"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Myrmidon", "level": "5", "count": "2", "stats": {"hp": "31", "str": "12", "mag": "1", "skl": "16", "spd": "17", "lck": "12", "def": "4", "res": "4", "mov": "5"}, "items": [{"name": "Steel Sword"}], "skills": ["Avoid +10"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Wyvern Rider", "level": "7", "count": "4", "stats": {"hp": "34", "str": "16", "mag": "0", "skl": "12", "spd": "11", "lck": "10", "def": "10", "res": "1", "mov": "7"}, "items": [{"name": "Steel Axe"}], "skills": ["Strength +2", "Tantivy"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
        {"name": "Plegian", "class": "Dark Mage", "level": "5", "count": "1", "stats": {"hp": "34", "str": "1", "mag": "9", "skl": "6", "spd": "7", "lck": "6", "def": "5", "res": "6", "mov": "5"}, "items": [{"name": "Nosferatu"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)"},
      ],
    },
    reinforcements: ["Turn 3", "  1 Barbarian with an Iron Axe (Hard)/Steel Axe (Lunatic) from the southwestern fort (Hard/Lunatic only)", "  1 Barbarian that drops a Hand Axe from the western fort", "    On Lunatic, this Barbarian is equipped with a Short Axe alongside the drop", "  1 Myrmidon from the northern center fort", "Turn 4 (Hard/Lunatic only)", "  2 Wyvern Riders from the northwest forts", "Turn 5", "  1 Dark Mage from the southwestern fort", "  1 Myrmidon from the western fort", "  1 Barbarian with an Iron Axe (Normal/Hard)/Steel Axe (Lunatic) from the northern center fort", "  2 Wyvern Riders; one from the upper northwest fort, and one from the northeast fort (Lunatic only)"],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+", "Counter", "Aegis+", "Pavise+"],
    bosses: {
      normal: [
        {"class": "Wyvern Rider", "level": "9", "stats": {"hp": "29", "str": "12", "mag": "0", "skl": "9", "spd": "8", "lck": "6", "def": "11", "res": "1", "mov": "7"}, "items": [{"name": "Short Axe"}, {"name": "Bullion (M)", "drop": true}], "skills": [], "name": "Orton"},
      ],
      hard: [
        {"class": "Wyvern Rider", "level": "9", "stats": {"hp": "34", "str": "14", "mag": "0", "skl": "11", "spd": "10", "lck": "8", "def": "12", "res": "1", "mov": "7"}, "items": [{"name": "Short Axe"}, {"name": "Bullion (M)", "drop": true}], "skills": ["Tantivy"], "name": "Orton"},
      ],
      lunatic: [
        {"class": "Wyvern Rider", "level": "9", "stats": {"hp": "41", "str": "18", "mag": "0", "skl": "13", "spd": "12", "lck": "11", "def": "13", "res": "1", "mov": "7"}, "items": [{"name": "Tomahawk"}, {"name": "Bullion (M)", "drop": true}], "skills": ["Tantivy"], "name": "Orton"},
      ],
    },
    unlocks: ["chapter-6", "paralogue-2"],
    source: {"page": "The Exalt and the King", "oldid": 741857},
  },
  {
    id: "chapter-6",
    kind: "story",
    order: 700,
    label: "Chapter 6",
    title: "Foreseer",
    location: "Ylisstol",
    conditions: {"normal": {"victory": "Rout the enemy", "defeat": "Chrom, Robin, or Emmeryn dies", "deploy": "1–10+2 (Upon Panne arriving and Gaius being recruited)", "enemies": "24−1 (Upon Gaius being recruited)"}, "hard": {"victory": "Rout the enemy", "defeat": "Chrom, Robin, or Emmeryn dies", "deploy": "1–10+2 (Upon Panne arriving and Gaius being recruited)", "enemies": "24−1 (Upon Gaius being recruited)"}, "lunatic": {"victory": "Rout the enemy", "defeat": "Chrom, Robin, or Emmeryn dies", "deploy": "1–10+2 (Upon Panne arriving and Gaius being recruited)", "enemies": "24−1 (Upon Gaius being recruited)"}},
    recruits: [
      {"unit": "Panne", "class": "Taguel", "level": "6", "how": "Automatically from turn 2", "inventory": ["Beaststone", "Concoction"]},
      {"unit": "Gaius", "class": "Thief", "level": "5", "how": "Enemy, talk to with Chrom", "inventory": ["Iron Sword"]},
    ],
    forced: ["Chrom"],
    items: [
      {"item": "Heal", "how": "Dropped by Validar"},
      {"item": "Iron Sword", "how": "Dropped by Gaius if killed as an enemy"},
      {"item": "Iron Lance", "how": "Dropped by enemy Cavalier"},
      {"item": "Wind", "how": "Dropped by enemy Dark Mage"},
      {"item": "Secret Book", "how": "Open chest in Emmeryn's room"},
    ],
    shop: {"location": "Ylisstol", "opensAfter": "this chapter", "armory": [{"item": "Heal", "cost": 600}, {"item": "Mend", "cost": 1000}, {"item": "Vulnerary", "cost": 300}, {"item": "Magic Tonic", "cost": 150}, {"item": "Resistance Tonic", "cost": 150}], "merchant": [{"item": "Steel Sword", "cost": 840}, {"item": "Steel Lance", "cost": 910}, {"item": "Steel Axe", "cost": 980}, {"item": "Steel Bow", "cost": 910}, {"item": "Elwind", "cost": 910}, {"item": "Rapier", "cost": 1600}, {"item": "Hammer", "cost": 1850}, {"item": "Master Seal", "cost": 2500}, {"item": "Second Seal", "cost": 2500}]},
    eventTiles: 2,
    enemies: {
      normal: [
        {"name": "Validar", "class": "Sorcerer", "level": "1", "count": "1", "stats": {"hp": "32", "str": "3", "mag": "12", "skl": "10", "spd": "9", "lck": "5", "def": "8", "res": "10", "mov": "6"}, "items": [{"name": "Elfire"}, {"name": "Heal", "drop": true}], "notes": "Begins moving unprovoked on turn 4."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "6", "stats": {"hp": "24~25", "str": "10", "mag": "0", "skl": "8~9", "spd": "6", "lck": "5~6", "def": "4~5", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Gaius", "class": "Thief", "level": "5", "count": "1", "stats": {"hp": "22", "str": "7", "mag": "0", "skl": "13", "spd": "15", "lck": "6", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Iron Sword", "drop": true}], "skills": ["Locktouch"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "4", "stats": {"hp": "22", "str": "1", "mag": "5~6", "skl": "4", "spd": "4", "lck": "3", "def": "4~5", "res": "3~4", "mov": "5"}, "items": [{"name": "Flux"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "22", "str": "1", "mag": "5~6", "skl": "4", "spd": "4", "lck": "3", "def": "4~5", "res": "3~4", "mov": "5"}, "items": [{"name": "Wind", "drop": true}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Thief", "level": "6", "count": "4", "stats": {"hp": "20", "str": "7", "mag": "0", "skl": "9", "spd": "13", "lck": "4", "def": "3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Locktouch"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "22", "str": "1", "mag": "5~6", "skl": "4", "spd": "4", "lck": "3", "def": "4~5", "res": "3~4", "mov": "5"}, "items": [{"name": "Thunder"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "3", "stats": {"hp": "22", "str": "7~8", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "4~5", "def": "5~6", "res": "0~1", "mov": "7"}, "items": [{"name": "Iron Lance"}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "1", "stats": {"hp": "22", "str": "7~8", "mag": "0", "skl": "6~7", "spd": "6~7", "lck": "4~5", "def": "5~6", "res": "0~1", "mov": "7"}, "items": [{"name": "Iron Lance", "drop": true}], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "2", "stats": {"hp": "24~25", "str": "10", "mag": "0", "skl": "8~9", "spd": "6", "lck": "5~6", "def": "4~5", "res": "0~1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "notes": "Immediately begins moving unprovoked."},
      ],
      hard: [
        {"name": "Validar", "class": "Sorcerer", "level": "1", "count": "1", "stats": {"hp": "36", "str": "3", "mag": "14", "skl": "11", "spd": "10", "lck": "6", "def": "9", "res": "12", "mov": "6"}, "items": [{"name": "Elfire"}, {"name": "Heal", "drop": true}], "skills": ["Anathema"], "notes": "Begins moving unprovoked on turn 4."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "6", "stats": {"hp": "29~30", "str": "12~13", "mag": "0", "skl": "10~11", "spd": "7~8", "lck": "7~8", "def": "4~5", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Gaius", "class": "Thief", "level": "5", "count": "1", "stats": {"hp": "22", "str": "7", "mag": "0", "skl": "13", "spd": "15", "lck": "6", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Iron Sword", "drop": true}], "skills": ["Locktouch"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "4", "stats": {"hp": "26~27", "str": "1", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "4~5", "res": "4~5", "mov": "5"}, "items": [{"name": "Flux"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "26~27", "str": "1", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "4~5", "res": "4~5", "mov": "5"}, "items": [{"name": "Wind", "drop": true}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Thief", "level": "6", "count": "4", "stats": {"hp": "23~24", "str": "8~9", "mag": "0", "skl": "11~12", "spd": "15~16", "lck": "5~6", "def": "3", "res": "0~1", "mov": "5"}, "items": [{"name": "Iron Sword"}], "skills": ["Locktouch", "Underdog"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "26~27", "str": "1", "mag": "6~7", "skl": "5~6", "spd": "5~6", "lck": "4~5", "def": "4~5", "res": "4~5", "mov": "5"}, "items": [{"name": "Thunder"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "3", "stats": {"hp": "26~27", "str": "9~10", "mag": "0", "skl": "8~9", "spd": "8~9", "lck": "6~7", "def": "6~7", "res": "1~2", "mov": "7"}, "items": [{"name": "Iron Lance"}], "skills": ["Outdoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "1", "stats": {"hp": "26~27", "str": "9~10", "mag": "0", "skl": "8~9", "spd": "8~9", "lck": "6~7", "def": "6~7", "res": "1~2", "mov": "7"}, "items": [{"name": "Iron Lance", "drop": true}], "skills": ["Outdoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "2", "stats": {"hp": "29~30", "str": "12~13", "mag": "0", "skl": "10~11", "spd": "7~8", "lck": "7~8", "def": "4~5", "res": "0~1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
      lunatic: [
        {"name": "Validar", "class": "Sorcerer", "level": "1", "count": "1", "stats": {"hp": "43", "str": "3", "mag": "17", "skl": "13", "spd": "12", "lck": "8", "def": "10", "res": "14", "mov": "6"}, "items": [{"name": "Arcfire"}, {"name": "Heal", "drop": true}], "skills": ["Anathema", "Vengeance"], "notes": "Begins moving unprovoked on turn 4."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "6", "stats": {"hp": "37", "str": "16", "mag": "0", "skl": "13", "spd": "9", "lck": "11", "def": "5", "res": "1", "mov": "5"}, "items": [{"name": "Steel Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Gaius", "class": "Thief", "level": "5", "count": "1", "stats": {"hp": "22", "str": "7", "mag": "0", "skl": "13", "spd": "15", "lck": "6", "def": "5", "res": "2", "mov": "5"}, "items": [{"name": "Iron Sword", "drop": true}], "skills": ["Locktouch"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "4", "stats": {"hp": "34", "str": "1", "mag": "9", "skl": "7", "spd": "7", "lck": "6", "def": "5", "res": "6", "mov": "5"}, "items": [{"name": "Nosferatu"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "34", "str": "1", "mag": "9", "skl": "7", "spd": "7", "lck": "6", "def": "5", "res": "6", "mov": "5"}, "items": [{"name": "Elwind"}, {"name": "Wind", "drop": true}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Thief", "level": "6", "count": "4", "stats": {"hp": "29", "str": "10", "mag": "0", "skl": "15", "spd": "19", "lck": "7", "def": "3", "res": "1", "mov": "5"}, "items": [{"name": "Steel Sword"}], "skills": ["Locktouch", "Underdog"], "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Dark Mage", "level": "6", "count": "1", "stats": {"hp": "34", "str": "1", "mag": "9", "skl": "7", "spd": "7", "lck": "6", "def": "5", "res": "6", "mov": "5"}, "items": [{"name": "Elthunder"}], "skills": ["Hex", "Anathema"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "3", "stats": {"hp": "34", "str": "13", "mag": "0", "skl": "11", "spd": "11", "lck": "10", "def": "7", "res": "2", "mov": "7"}, "items": [{"name": "Steel Lance"}], "skills": ["Outdoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Cavalier", "level": "6", "count": "1", "stats": {"hp": "34", "str": "13", "mag": "0", "skl": "11", "spd": "11", "lck": "10", "def": "7", "res": "2", "mov": "7"}, "items": [{"name": "Steel Lance"}, {"name": "Iron Lance", "drop": true}], "skills": ["Outdoor Fighter"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
        {"name": "Unknown", "class": "Fighter", "level": "6", "count": "2", "stats": {"hp": "37", "str": "16", "mag": "0", "skl": "13", "spd": "9", "lck": "11", "def": "5", "res": "1", "mov": "5"}, "items": [{"name": "Silver Axe"}], "skills": ["HP +5", "Zeal"], "randomSkills": "(Can have 0–1 skill(s) at random)", "notes": "Immediately begins moving unprovoked."},
      ],
    },
    reinforcements: [],
    lunaticPlusPool: ["Pass", "Hawkeye", "Luna+", "Vantage+", "Counter", "Aegis+", "Pavise+"],
    bosses: {
      normal: [
        {"class": "Sorcerer", "level": "1", "stats": {"hp": "32", "str": "3", "mag": "12", "skl": "10", "spd": "9", "lck": "5", "def": "8", "res": "10", "mov": "6"}, "items": [{"name": "Elfire"}, {"name": "Heal", "drop": true}], "skills": [], "name": "Validar"},
      ],
      hard: [
        {"class": "Sorcerer", "level": "1", "stats": {"hp": "36", "str": "3", "mag": "14", "skl": "11", "spd": "10", "lck": "6", "def": "9", "res": "12", "mov": "6"}, "items": [{"name": "Elfire"}, {"name": "Heal", "drop": true}], "skills": ["Anathema"], "name": "Validar"},
      ],
      lunatic: [
        {"class": "Sorcerer", "level": "1", "stats": {"hp": "43", "str": "3", "mag": "17", "skl": "13", "spd": "12", "lck": "8", "def": "10", "res": "14", "mov": "6"}, "items": [{"name": "Arcfire"}, {"name": "Heal", "drop": true}], "skills": ["Anathema", "Vengeance"], "name": "Validar"},
      ],
    },
    unlocks: ["chapter-7"],
    source: {"page": "Foreseer", "oldid": 685293},
  },
];
