"""Class base stats (#122) from SF's /awakening/classes/base-stats/ (saved as <cache>/classbases.html) → src/game-data/class-bases.ts."""
import html
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
s = open(os.path.join(sys.argv[1], 'classbases.html'), encoding='utf-8', errors='replace').read()
cls = io.open(os.path.join(ROOT, 'src', 'game-data', 'classes.ts'), encoding='utf-8').read()
ids = {}
for cid, name in re.findall(r"^\s+'?([a-z-]+)'?: \{ name: (\{[^}]*\}|'[^']+')", cls, re.M):
    for n in re.findall(r"'([^']+)'", name):
        ids.setdefault(n, cid)
out, missing = {}, []
for r in re.findall(r'<tr[^>]*>(.*?)</tr>', s, re.S):
    c = [re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', x))).strip() for x in re.findall(r'<t[hd][^>]*>(.*?)</t[hd]>', r, re.S)]
    if len(c) < 10 or c[0] == 'Class':
        continue
    m = re.match(r'(.*?)(?: \((M|F)\))?$', c[0])
    name, g = m.group(1), m.group(2)
    names = [x.strip() for x in re.split(r'[/,]', name)]
    cid = next((ids[n] for n in names if n in ids), None)
    if not cid:
        missing.append(c[0])
        continue
    stats = dict(zip(['hp', 'str', 'mag', 'skl', 'spd', 'def', 'res', 'mov'], [int(x) for x in c[1:9]]))
    stats['lck'] = 0
    weapons = [w.strip().lower() for w in c[9].split(',') if w.strip()]
    key = cid if not g else cid
    entry = out.setdefault(cid, {})
    entry['M' if g == 'M' else 'F' if g == 'F' else 'any'] = {'stats': stats, 'weapons': weapons}
lines = []
for cid, e in out.items():
    def blk(x):
        st = x['stats']
        return "{ stats: { hp: %d, str: %d, mag: %d, skl: %d, spd: %d, lck: 0, def: %d, res: %d }, mov: %d, weapons: [%s] }" % (st['hp'], st['str'], st['mag'], st['skl'], st['spd'], st['def'], st['res'], st['mov'], ', '.join("'%s'" % w for w in x['weapons']))
    if 'any' in e:
        lines.append(f"  '{cid}': {{ any: {blk(e['any'])} }},")
    else:
        parts = ', '.join(f"{k}: {blk(v)}" for k, v in e.items())
        lines.append(f"  '{cid}': {{ {parts} }},")
head = '''/**
 * Class base stats and weapon types (#122), from Serenes Forest's class base stats
 * (https://serenesforest.net/awakening/classes/base-stats/). Luck has no class base. A promotion adds the difference
 * between the new class's bases and the old one's. Generated by scripts/item-data/class-bases.py: don't hand-edit.
 */
import type { ClassId } from './classes';
import type { Stat } from './stats';

export type ClassBase = { readonly stats: Readonly<Record<Stat, number>>; readonly mov: number; readonly weapons: readonly string[] };

export const CLASS_BASES: Readonly<Partial<Record<ClassId, { readonly any?: ClassBase; readonly M?: ClassBase; readonly F?: ClassBase }>>> = {
'''
io.open(os.path.join(ROOT, 'src', 'game-data', 'class-bases.ts'), 'w', encoding='utf-8', newline='\n').write(head + '\n'.join(lines) + '\n};\n')
print(len(out), 'classes; not matched:', missing)
